#!/bin/sh
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:				C.unix/plog/src/mkprologc
# Purpose:			Build the Prolog compiler saved image
# Author:			Robert John Duncan, Jul 15 1993 (see revisions)
# Documentation:
# Related Files:

corepop11 %nort mkimage -share -nodebug -entrymain \
	prologc syscomp/prologc
rm -f prologc.psv-

# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, Aug 16 1993 - removed backup file
