#!/bin/sh
# --- Copyright University of Sussex 1995. All rights reserved. ----------
# File:            C.unix/com/mkclisp
# Purpose:         Command file to make a Common Lisp saved image
# Author:          Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:   HELP * CLISP
# Related Files:   VMS version

# Command file to make a Common Lisp saved image using $popsys/pop11

$popsys/pop11 %nort %noinit \
	$popliblib/mkimage.p \
	-install -subsystem lisp \
	$popsavelib/clisp.psv \
	$usepop/pop/lisp/src/clisp.p

rm -f $popsavelib/clisp.psv-


# --- Revision History ---------------------------------------------------
# --- John Gibson, Aug 22 1995  Added %noinit
# --- Robert John Duncan, May 29 1991
#		Added -install
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991
#		Uses LIB MKIMAGE instead of LIB MKSSIMAGE
# --- John Williams, Oct 15 1990    Now uses -main
# --- John Williams, Jul 17 1990    Revised for new LIB SUBSYSTEM
