#!/bin/sh
# --- Copyright University of Sussex 1996. All rights reserved. ----------
# File:             C.unix/com/mkpml
# Purpose:          Builds the PML saved image
# Author:           Rob Duncan, Aug 22 1989 (see revisions)
# Related Files:    C.vms/com/mkpml.com

$popsys/pop11 %nort %noinit \
	$popliblib/mkimage.p \
	-nodebug -install -flags ml \( "$@" \) \
	$popsavelib/pml.psv \
	$usepop/pop/pml/src/ml.p

rm -f $popsavelib/pml.psv-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Mar  6 1996		Added -nodebug
# --- John Gibson, Aug 22 1995 		Added %noinit
# --- Robert John Duncan, May 29 1991 - added -install
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
# --- Robert John Duncan, Aug  8 1990 - changed to use "mkssimage"
# --- Rob Duncan, Mar 16 1990 - removed assignments to POPLIB etc.
