#!/bin/sh
# --- Copyright University of Sussex 1991. All rights reserved. ----------
# File:             C.unix/com/mktvi
# Purpose:          Make saved image with LIB * VEDTVI loaded
# Author:           John Williams, Jan 24 1990 (see revisions)
# Documentation:    HELP * TVI
# Related Files:    LIB * MKIMAGE

$popsys/pop11 %nort mkimage -ved $poplocalbin/tvi.psv vedtvi
rm -f $poplocalbin/tvi.psv-

# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, May 29 1991 - added rm backup image
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
