#!/bin/sh
# --- Copyright University of Sussex 1991. All rights reserved. ----------
# File:             C.unix/com/mkvedemacs
# Purpose:          Make saved image with LIB * VEDEMACS loaded
# Author:           John Williams, Jan 24 1990 (see revisions)
# Documentation:    HELP * VEDEMACS
# Related Files:    LIB * MKIMAGE

$popsys/pop11 %nort mkimage -ved $poplocalbin/vedemacs.psv vedemacs
rm -f $poplocalbin/vedemacs.psv-

# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, May 29 1991 - added rm backup image
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
