#!/bin/bash
# called from the directory above from a hudson job

. bin/poplog.sh

make -C config 

# this will build at least pop/pop/basepop11 and startup.psv
make

test/test_uses_compile.sh > report_test_uses_compile.xml
