#!/bin/bash
# called from the directory above from a hudson job

make -C config 

. bin/poplog.sh
make

p=`which pop11` && [ -z "$p" ] && exit 1

test/test_uses_compile.sh > report_test_uses_compile.xml
