p_ADD_MENU $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xm.p
p_ADD_MENU $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xol.p
p_ADD_MENU_BUTTON $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xm.p
p_ADD_MENU_BUTTON $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xol.p
p_ADD_SUBSYSTEM_BUTTON $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xm.p
p_ADD_SUBSYSTEM_BUTTON $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xol.p
p_CONFIRM $usepop/pop/x/ui/lib/S-poplog_uiS-confirm_xm.p
p_CONFIRM $usepop/pop/x/ui/lib/S-poplog_uiS-confirm_xol.p
p_CREATE_BOOLEAN $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_BOOLEAN $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_BOX_BUTTON $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_BOX_BUTTON $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_COMMAND $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_COMMAND $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_CONTROL_AREAS $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xm.p
p_CREATE_CONTROL_AREAS $usepop/pop/x/ui/lib/S-poplog_uiS-controltool_xol.p
p_CREATE_LABEL $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_LABEL $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_LISTOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_LISTOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_MENUOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_MENUOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_NUMERIC_RANGE $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_NUMERIC_RANGE $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_ONEOF_OR_SOMEOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_ONEOF_OR_SOMEOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_ROW_CONTROL $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_ROW_CONTROL $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_CREATE_STR_OR_NUM $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_CREATE_STR_OR_NUM $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_FILETOOL $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xm.p
p_FILETOOL $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xol.p
p_FONTSTRUCT $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_FONTSTRUCT $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_HAS_MENUBAR_MENU $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_HAS_MENUBAR_MENU $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_HAS_SCROLLBAR_MENU $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xm.p
p_HAS_SCROLLBAR_MENU $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xol.p
p_HELPTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xm.p
p_HELPTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xol.p
p_INFORMATION $usepop/pop/x/ui/lib/S-poplog_uiS-information_xm.p
p_INFORMATION $usepop/pop/x/ui/lib/S-poplog_uiS-information_xol.p
p_LABEL_OF $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_LABEL_OF $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_LABEL_OF updaterof $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_LABEL_OF updaterof $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_LABEL_STRING $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_LABEL_STRING $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_LABEL_STRING updaterof $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_LABEL_STRING updaterof $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_LABEL_WIDTH $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_LIBRARYTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-librarytool_xm.p
p_LIBRARYTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-librarytool_xol.p
p_LIST_ITEMS_SET_NUM_VIS $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_LIST_ITEMS_SET_NUM_VIS $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_MESSAGE $usepop/pop/x/ui/lib/S-poplog_uiS-message_xm.p
p_MESSAGE $usepop/pop/x/ui/lib/S-poplog_uiS-message_xol.p
p_NEW_BUTTON $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_NEW_BUTTON $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_NEW_MENUBAR $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_NEW_MENUBAR $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_NEW_MENUBUTTON $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_NEW_MENUBUTTON $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_NEW_MENUSHELL $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_NEW_MENUSHELL $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_POPUP_MENU $usepop/pop/x/ved/lib/S-xvedS-menubar_xm.p
p_POPUP_MENU $usepop/pop/x/ved/lib/S-xvedS-menubar_xol.p
p_PROJECTTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-projecttool_xm.p
p_PROJECTTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-projecttool_xol.p
p_PROJECTTOOL_OP $usepop/pop/x/ui/lib/S-poplog_uiS-projecttool_xm.p
p_PROJECTTOOL_OP $usepop/pop/x/ui/lib/S-poplog_uiS-projecttool_xol.p
p_PROMPTSOURCE $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xm.p
p_PROMPTSOURCE $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xol.p
p_PROMPTSOURCE updaterof $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xm.p
p_PROMPTSOURCE updaterof $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xol.p
p_PROMPTTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xm.p
p_PROMPTTOOL $usepop/pop/x/ui/lib/S-poplog_uiS-prompttool_xol.p
p_PROPSHEET_NEW $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_PROPSHEET_NEW $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_PROPSHEET_NEW_BOX $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_PROPSHEET_NEW_BOX $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_REBUILD_MENUOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_REBUILD_MENUOF $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_SCROLLBAR_VALUE $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xm.p
p_SCROLLBAR_VALUE $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xol.p
p_SCROLL_CB_VERIFY $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xm.p
p_SCROLL_CB_VERIFY $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xol.p
p_SET_FOCUS_ON $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_SET_FOCUS_ON $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_SET_LIBTOOL_FOOTER $usepop/pop/x/ui/lib/S-poplog_uiS-librarytool_xm.p
p_SET_LIBTOOL_FOOTER $usepop/pop/x/ui/lib/S-poplog_uiS-librarytool_xol.p
p_SET_SCROLLBAR $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xm.p
p_SET_SCROLLBAR $usepop/pop/x/ved/lib/S-xvedS-scrollbar_xol.p
p_TEXTFIELD_VALUE $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_TEXTFIELD_VALUE $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_TEXTFIELD_VALUE updaterof $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_TEXTFIELD_VALUE updaterof $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_UPDATE_PREVIEW_ITEM $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xm.p
p_UPDATE_PREVIEW_ITEM $usepop/pop/x/pop/lib/S-propsheetS-switch_vec_xol.p
p_body $usepop/pop/packages/teaching/lib/prodsys.p
p_func $usepop/pop/packages/teaching/lib/prodsys.p
p_name $usepop/pop/packages/teaching/lib/prodsys.p
p_pattern $usepop/pop/packages/teaching/lib/prodsys.p
p_typespec $popautolib/p_typespec.p
pack_bool $usepop/pop/pml/src/util.p
pack_bool updaterof $usepop/pop/pml/src/util.p
package $usepop/pop/lisp/src/packages.p
package updaterof $usepop/pop/lisp/src/packages.p
package_error $popsrc/lispcore.p
package_error $usepop/pop/lisp/src/util.p
package_name $popsrc/lispcore.p
package_nicknames $popsrc/lispcore.p
package_shadowing_symbols $popsrc/lispcore.p
package_use_list $popsrc/lispcore.p
package_used_by_list $popsrc/lispcore.p
packet $usepop/pop/packages/teaching/lib/facets.p
packitem $popautolib/packitem.p
pacopy $usepop/pop/packages/teaching/lib/analogy.p
pad_print $usepop/pop/packages/rclib/auto/rc_lispbrowser.p
pad_print $usepop/pop/packages/rclib/auto/rc_procbrowser.p
pad_spaces $usepop/pop/packages/neural/src/pop/nn_utils.p
padout $popsrc/termcap.p
paintbrush $usepop/pop/packages/rclib/demo/painting_demo.p
paintbrush $usepop/pop/packages/rclib/lib/painting_demo.p
painting_go $usepop/pop/packages/rclib/demo/painting_demo.p
painting_go $usepop/pop/packages/rclib/lib/painting_demo.p
paintof $usepop/pop/lib/turtle/lamlabel.p
paintpicture $usepop/pop/lib/turtle/paintpicture.p
paintpot $usepop/pop/packages/rclib/demo/painting_demo.p
paintpot $usepop/pop/packages/rclib/lib/painting_demo.p
palette $popliblib/aed.p
palette $usepop/pop/packages/rclib/demo/aze.connect4.p
panel_quit_cb $usepop/pop/packages/neural/src/pop/nui_xpanels.p
panel_reactor $usepop/pop/packages/rclib/teach/newtest.p
panel_ss_table $usepop/pop/x/ui/lib/S-poplog_uiS-guiSubsystem.p
panel_update $usepop/pop/packages/rclib/auto/rc_control_panel.p
panic $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
panic $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
paper_names $popautolib/postscript_line_consumer.p
paragraph_action $popliblib/reformat.p
parallel $popliblib/geometry.p
parity_check $usepop/pop/packages/brait/lib/matrix_functions.p
parse $popliblib/tparse.p
parse $usepop/pop/packages/teaching/lib/logic.p
parse $usepop/pop/pml/src/parse.p
parse_abstypedec $usepop/pop/pml/src/parse.p
parse_action $popvedlib/ved_do_text_action.p
parse_andalso_exp $usepop/pop/pml/src/parse.p
parse_args $usepop/pop/packages/vedutils/auto/ved_procheader.p
parse_argument $popvedlib/windows.p
parse_arguments $usepop/pop/packages/master/lib/newmaster/vedcomms.p
parse_arguments $usepop/pop/pml/src/showdef.p
parse_arguments $usepop/pop/pml/src/trace.p
parse_array $popautolib/c_dec.p
parse_array $popautolib/kr_newc_dec.p
parse_array $popautolib/newc_dec.p
parse_array $usepop/pop/packages/newc_dec/auto/newc_dec.p
parse_array_spec $popautolib/fortran_dec.p
parse_body $usepop/pop/lisp/src/eval.p
parse_button_input $usepop/pop/lib/flavours/window_input.p
parse_con_tyexp $usepop/pop/pml/src/parse.p
parse_conbinds $usepop/pop/pml/src/parse.p
parse_continuous_files $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_continuous_lists $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_databind $usepop/pop/pml/src/parse.p
parse_datadesc $usepop/pop/pml/src/parse.p
parse_datatypedec $usepop/pop/pml/src/parse.p
parse_datatypespec $usepop/pop/pml/src/parse.p
parse_date $usepop/pop/packages/master/lib/newmaster/history.p
parse_declarations $usepop/pop/lisp/src/let.p
parse_decs $usepop/pop/pml/src/parse.p
parse_definition $usepop/pop/lisp/src/defun.p
parse_directive $popautolib/format_print.p
parse_discrete_files $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_discrete_lists $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_discrete_singlefiles $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_egs_from_file $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_egs_from_proc $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_egs_from_struct $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_eqtypespec $usepop/pop/pml/src/parse.p
parse_error $usepop/pop/pml/src/parse.p
parse_exceptiondec $usepop/pop/pml/src/parse.p
parse_exceptionspec $usepop/pop/pml/src/parse.p
parse_exnbind $usepop/pop/pml/src/parse.p
parse_exndesc $usepop/pop/pml/src/parse.p
parse_exp $usepop/pop/pml/src/parse.p
parse_external_exception $usepop/pop/pml/src/parse.p
parse_external_structure $usepop/pop/pml/src/parse.p
parse_external_type $usepop/pop/pml/src/parse.p
parse_external_val $usepop/pop/pml/src/parse.p
parse_externaldec $usepop/pop/pml/src/parse.p
parse_fail $usepop/pop/pml/src/parse.p
parse_field_header $usepop/pop/packages/rclib/auto/rc_control_panel.p
parse_fixity_directive $usepop/pop/pml/src/parse.p
parse_fncbind $usepop/pop/pml/src/parse.p
parse_funbind $usepop/pop/pml/src/parse.p
parse_functor_formal $usepop/pop/pml/src/parse.p
parse_functordec $usepop/pop/pml/src/parse.p
parse_fundec $usepop/pop/pml/src/parse.p
parse_id $usepop/pop/pml/src/parse.p
parse_includespec $usepop/pop/pml/src/parse.p
parse_infix_exp $usepop/pop/pml/src/parse.p
parse_infix_pat $usepop/pop/pml/src/parse.p
parse_integer $usepop/pop/lisp/src/read.p
parse_it $usepop/pop/pml/src/parse.p
parse_label $usepop/pop/pml/src/parse.p
parse_lamlist $usepop/pop/lisp/src/lamlists.p
parse_logical_pathname $usepop/pop/lisp/src/pathnames.p
parse_match $usepop/pop/pml/src/parse.p
parse_message $usepop/pop/packages/master/lib/newmaster/recover.p
parse_namestring $usepop/pop/lisp/src/pathnames.p
parse_nonfix_id $usepop/pop/pml/src/parse.p
parse_opendec $usepop/pop/pml/src/parse.p
parse_openspec $usepop/pop/pml/src/parse.p
parse_opr $usepop/pop/pml/src/parse.p
parse_option $popliblib/newpop.p
parse_orelse_exp $usepop/pop/pml/src/parse.p
parse_pat $usepop/pop/pml/src/parse.p
parse_pervasivedec $usepop/pop/pml/src/parse.p
parse_record_exp $usepop/pop/pml/src/parse.p
parse_record_pat $usepop/pop/pml/src/parse.p
parse_record_tyexp $usepop/pop/pml/src/parse.p
parse_recvalbinds $usepop/pop/pml/src/parse.p
parse_rule $usepop/pop/pml/src/parse.p
parse_seq $usepop/pop/pml/src/parse.p
parse_seq_to $usepop/pop/pml/src/parse.p
parse_shareq $usepop/pop/pml/src/parse.p
parse_sharingspec $usepop/pop/pml/src/parse.p
parse_shortid $usepop/pop/pml/src/parse.p
parse_sigbind $usepop/pop/pml/src/parse.p
parse_sigexp $usepop/pop/pml/src/parse.p
parse_signaturedec $usepop/pop/pml/src/parse.p
parse_specs $usepop/pop/pml/src/parse.p
parse_strbind $usepop/pop/pml/src/parse.p
parse_strdesc $usepop/pop/pml/src/parse.p
parse_strexp $usepop/pop/pml/src/parse.p
parse_string $usepop/pop/packages/vedmail/auto/ved_send.p
parse_string $usepop/pop/packages/vedmail/auto/ved_sendmr.p
parse_structuredec $usepop/pop/pml/src/parse.p
parse_structurespec $usepop/pop/pml/src/parse.p
parse_tag_attributes $popautolib/kr_newc_dec.p
parse_tag_attributes $popautolib/newc_dec.p
parse_tag_attributes $usepop/pop/packages/newc_dec/auto/newc_dec.p
parse_template $usepop/pop/packages/neural/src/pop/nn_examplesets.p
parse_tuple_tyexp $usepop/pop/pml/src/parse.p
parse_tycon_bind $usepop/pop/pml/src/parse.p
parse_tycon_id $usepop/pop/pml/src/parse.p
parse_tyexp $usepop/pop/pml/src/parse.p
parse_typebind $usepop/pop/pml/src/parse.p
parse_typed_exp $usepop/pop/pml/src/parse.p
parse_typed_pat $usepop/pop/pml/src/parse.p
parse_typedec $usepop/pop/pml/src/parse.p
parse_typedesc $usepop/pop/pml/src/parse.p
parse_typespec $usepop/pop/pml/src/parse.p
parse_tyvar_seq $usepop/pop/pml/src/parse.p
parse_valbinds $usepop/pop/pml/src/parse.p
parse_valdec $usepop/pop/pml/src/parse.p
parse_valdesc $usepop/pop/pml/src/parse.p
parse_valspec $usepop/pop/pml/src/parse.p
parse_withtype $usepop/pop/pml/src/parse.p
parse_wordtype $popautolib/c_dec.p
parseargument $popvedlib/ved_print.p
parser $usepop/pop/lib/lr_parser/auto/define_parser.p
parser_of $usepop/pop/lib/lr_parser/lib/lr_core.p
parsergbstring $usepop/pop/packages/popvision/lib/Xcolour_to_rgb.p
part_of_justification $usepop/pop/packages/newkit/prb/auto/prb_DDEL.p
part_of_justification $usepop/pop/packages/newkit/prb/incomplete/prb_DDEL.p
part_pdnargs $usepop/pop/lib/objectclass/src/parts.p
part_props $usepop/pop/lib/objectclass/auto/ved_ocg.p
part_updater $usepop/pop/lib/objectclass/src/parts.p
partial $usepop/pop/packages/teaching/lib/solver.p
pass $usepop/pop/packages/rclib/demo/aze.connect4.p
pat_kind $usepop/pop/pml/src/gencode.p
path_and_num $usepop/pop/packages/vedmail/auto/ved_nextmail.p
path_and_num $usepop/pop/packages/vedmail/auto/ved_prevmail.p
pathname $usepop/pop/lisp/src/pathnames.p
pathname_= $usepop/pop/lisp/src/pathnames.p
pathname_field $usepop/pop/lisp/src/pathnames.p
pathname_match_p $usepop/pop/lisp/src/pathnames.p
pathname_search $usepop/pop/packages/master/auto/newmaster_utils.p
pathname_search $usepop/pop/packages/master/lib/newmaster/utils.p
patonback $usepop/pop/packages/teaching/lib/logic.p
pattern_instance $popautolib/pattern_instance.p
pattern_vars $usepop/pop/packages/teaching/lib/prodsys.p
pc_apply $usepop/pop/lisp/src/printcore.p
pc_list_tail_hook $usepop/pop/lisp/src/printcore.p
pc_printed $usepop/pop/lisp/src/printcore.p
pcopy $usepop/pop/packages/teaching/lib/analogy.p
pdcomp $popautolib/pdcomp.p
pdnargs $popsrc/procedure.p
pdnargs updaterof $popsrc/procedure.p
pdpart $popsrc/pdr_util.p
pdpart updaterof $popsrc/pdr_util.p
pdprops $popsrc/pdr_util.p
pdprops updaterof $popsrc/pdr_util.p
pdtolist $popsrc/list_util.p
peek_char $usepop/pop/lisp/src/read.p
peek_pp_state $usepop/pop/lisp/src/pp.p
peekc $usepop/pop/lib/lr_parser/lib/lr_example_2.p
peekitem $usepop/pop/pml/src/parse.p
pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
pen $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
pen $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
pen $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
pen_sector $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
pen_sector $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
pen_sector $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
pen_sector $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
perfect $usepop/pop/packages/teaching/lib/solvems.p
perform $usepop/pop/packages/teaching/lib/solver.p
perpline $popliblib/geometry.p
perpofseg $popliblib/geometry.p
perpofseg updaterof $popliblib/geometry.p
perporient $popliblib/geometry.p
person $usepop/pop/lib/objectclass/lib/objectclass_example.p
pervasive $usepop/pop/pml/src/env.p
phase $popautolib/phase.p
phcopy $usepop/pop/packages/teaching/lib/analogy.p
pic1 $usepop/pop/packages/rclib/auto/rc_shift_window_frame_by.p
pic1 $usepop/pop/packages/teaching/lib/evpics.p
pic2 $usepop/pop/packages/rclib/auto/rc_shift_window_frame_by.p
pic2 $usepop/pop/packages/teaching/lib/evpics.p
pic3 $usepop/pop/packages/teaching/lib/evpics.p
pic4 $usepop/pop/packages/teaching/lib/evpics.p
pic5 $usepop/pop/packages/teaching/lib/evpics.p
pica $usepop/pop/packages/teaching/lib/evpics.p
picb $usepop/pop/packages/teaching/lib/evpics.p
picc $usepop/pop/packages/teaching/lib/evpics.p
pick_proc $usepop/pop/packages/teaching/lib/blocks/utils.p
picline $popliblib/readarray.p
picof $usepop/pop/packages/teaching/lib/picdem.p
picture $usepop/pop/lib/turtle/vturtle.p
picture updaterof $usepop/pop/lib/turtle/vturtle.p
picture1 $usepop/pop/packages/brait/lib/tutorialsupplement.p
picture2 $usepop/pop/packages/brait/lib/tutorialsupplement.p
picture3 $usepop/pop/packages/brait/lib/tutorialsupplement.p
picture_action $popliblib/reformat.p
pipe_in $usepop/pop/packages/popvision/lib/sunrasterfile.p
pipe_out $usepop/pop/packages/popvision/lib/sunrasterfile.p
pipein $popautolib/pipein.p
pipeout $popautolib/pipeout.p
pixel_to_mm $usepop/pop/x/pop/auto/XptConvertUnit.p
place_appropriate_text $popliblib/reformat.p
place_revision_history $popliblib/reformat.p
place_spypoint $usepop/pop/plog/src/spy.p
plan_move_vehicle $usepop/pop/packages/brait/lib/vehicle_agent.p
planetexec $usepop/pop/packages/teaching/lib/planet.p
planmove $usepop/pop/packages/rclib/lib/rc_blocks.p
planmove $usepop/pop/packages/teaching/lib/msblocks.p
planmove $usepop/pop/packages/teaching/lib/msdemo.p
plantA1LOOP $popautolib/in_array.p
plantA1LOOP $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantAKLOOP $popautolib/in_array.p
plantAKLOOP $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantANLOOP $popautolib/in_array.p
plantANLOOP $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantDECR $popautolib/in_array.p
plantDECR $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantFLOOPCODE $popautolib/in_array.p
plantFLOOPCODE $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantINCR $popautolib/in_array.p
plantINCR $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantPROCLIST $popautolib/in_array.p
plantPROCLIST $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plantVLOOPCODE $popautolib/in_array.p
plantVLOOPCODE $usepop/pop/packages/popvision/pre14.51/auto/in_array.p
plant_and_execute $usepop/pop/lib/objectclass/src/utils.p
plant_binary_switch $usepop/pop/pml/src/gencode.p
plant_boolean_switch $usepop/pop/pml/src/gencode.p
plant_call_slot_proc_for_key $usepop/pop/lib/objectclass/src/tree_to_pd.p
plant_callq $usepop/pop/lib/objectclass/src/plant_utils.p
plant_con_switch $usepop/pop/pml/src/gencode.p
plant_const_switch $usepop/pop/pml/src/gencode.p
plant_constant_test $usepop/pop/pml/src/gencode.p
plant_cycle_limit $usepop/pop/packages/newkit/prb/auto/define_rulesystem.p
plant_deferred $usepop/pop/pml/src/vmml.p
plant_exception_test $usepop/pop/pml/src/gencode.p
plant_exn_switch $usepop/pop/pml/src/gencode.p
plant_fail_lab $usepop/pop/pml/src/gencode.p
plant_for_branches $usepop/pop/lib/objectclass/src/tree_to_pd.p
plant_form $popautolib/form.p
plant_go_on $usepop/pop/pml/src/gencode.p
plant_interval $usepop/pop/packages/newkit/prb/auto/define_rulesystem.p
plant_list_switch $usepop/pop/pml/src/gencode.p
plant_method_failure $usepop/pop/lib/objectclass/src/plant_utils.p
plant_mono $usepop/pop/lib/objectclass/src/mono_tree.p
plant_new_var $popautolib/form.p
plant_switch $usepop/pop/pml/src/gencode.p
plant_test_sequence $usepop/pop/pml/src/gencode.p
plantanydaemons $usepop/pop/lib/flavours/flavecore.p
plantinstvarcheck $usepop/pop/lib/flavours/flavecore.p
plantstring $usepop/pop/lib/obsolete/hangman.p
play $usepop/pop/lib/flavours/advent_flavours.p
play $usepop/pop/lib/obsolete/hangman.p
play $usepop/pop/packages/rclib/demo/aze.connect4.p
play $usepop/pop/packages/teaching/lib/rhino.p
play1 $usepop/pop/packages/teaching/lib/rhino.p
pldistance $popliblib/geometry.p
plog_goal_env_bind $popliblib/plog_goals.p
plog_goal_invoke $popliblib/plog_goals.p
plog_goal_newvar $popliblib/ploginpop.p
ploghelp $popautolib/ploghelp.p
ploghelp_symbol_list $popvedlib/ved_ploghelp.p
plogshowlib $popautolib/plogshowlib.p
plogteach $popautolib/plogteach.p
plogwhile $popliblib/ploginpop.p
plookup $usepop/pop/packages/popvision/lib/arraylookup.p
plproject $popliblib/geometry.p
plus_n $usepop/pop/lisp/src/numbers.p
point_to_screen $usepop/pop/x/ved/lib/vedxvedmouse.p
pointer_ang_from_value $usepop/pop/packages/rclib/auto/rc_constrained_pointer.p
pointer_value_from_ang $usepop/pop/packages/rclib/auto/rc_constrained_pointer.p
pointinpic $usepop/pop/packages/teaching/lib/rhino.p
pointof $usepop/pop/lib/turtle/regions.p
pointof $usepop/pop/packages/teaching/lib/picdem.p
poline $popliblib/geometry.p
poly $usepop/pop/lib/obsolete/poly.p
poly $usepop/pop/packages/rclib/lib/rc_polydemo.p
poly $usepop/pop/packages/rclib/lib/rc_polypanel.p
poly_advise $usepop/pop/packages/rclib/lib/rc_polypanel.p
polyexplain $usepop/pop/packages/rclib/lib/rc_polydemo.p
polygetargs $usepop/pop/packages/rclib/lib/rc_polydemo.p
polyoff $usepop/pop/packages/rclib/lib/rc_polydemo.p
polyoff $usepop/pop/packages/rclib/lib/rc_polypanel.p
polyreadline $usepop/pop/packages/rclib/lib/rc_polydemo.p
polyspi $usepop/pop/lib/obsolete/poly.p
polyspi $usepop/pop/packages/rclib/lib/rc_poly.p
polyspi $usepop/pop/packages/rclib/lib/rc_polydemo.p
polyspi $usepop/pop/packages/rclib/lib/rc_polypanel.p
polyspi $usepop/pop/packages/rcmenu/teach/menu_demo.p
pop $usepop/pop/packages/teaching/lib/oldlisp.p
pop11_EMPTY $popsrc/pop11_compile.p
pop11_EMPTY updaterof $popsrc/pop11_compile.p
pop11_FLUSHED $popsrc/pop11_compile.p
pop11_FLUSHED updaterof $popsrc/pop11_compile.p
pop11_cmd $usepop/pop/plog/src/commands.p
pop11_cmd $usepop/pop/pml/src/commands.p
pop11_comp_constructor $popsrc/pop11_syntax.p
pop11_comp_declaration $popsrc/pop11_syntax.p
pop11_comp_expr $popsrc/pop11_compile.p
pop11_comp_expr updaterof $popsrc/pop11_compile.p
pop11_comp_expr_seq $popsrc/pop11_compile.p
pop11_comp_expr_seq_to $popsrc/pop11_compile.p
pop11_comp_expr_to $popsrc/pop11_compile.p
pop11_comp_prec_expr $popsrc/pop11_compile.p
pop11_comp_procedure $popsrc/pop11_syntax.p
pop11_comp_stmnt_seq $popsrc/pop11_compile.p
pop11_comp_stmnt_seq_to $popsrc/pop11_compile.p
pop11_comp_stream $popsrc/pop11_compile.p
pop11_compile $popsrc/pop11_compile.p
pop11_compile_mode_flags $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop11_compile_mode_flags updaterof $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop11_compile_mode_save $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop11_define_declare $popsrc/pop11_syntax.p
pop11_define_props $popsrc/pop11_syntax.p
pop11_exceptions_save $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop11_exec_compile $popsrc/pop11_compile.p
pop11_exec_stmnt_seq_to $popsrc/pop11_compile.p
pop11_ignore_expr_to $usepop/pop/packages/popvision/lib/excall.p
pop11_loop_end $popsrc/pop11_loops.p
pop11_loop_start $popsrc/pop11_loops.p
pop11_need_nextitem $popsrc/pop11_proglist_util.p
pop11_need_nextreaditem $popsrc/pop11_proglist_util.p
pop11_printing_save $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop11_try_nextitem $popsrc/pop11_proglist_util.p
pop11_try_nextitem_noautoload $popautolib/kr_newc_dec.p
pop11_try_nextitem_noautoload $popautolib/newc_dec.p
pop11_try_nextitem_noautoload $usepop/pop/packages/newc_dec/auto/newc_dec.p
pop11_try_nextreaditem $popsrc/pop11_proglist_util.p
pop11_val $usepop/pop/lisp/src/compile.p
pop11_vars_default_check $popsrc/pop11_syntax.p
pop_ast_queue $popsrc/sig_queue.p
pop_ast_queue updaterof $popsrc/sig_queue.p
pop_asts_enabled $popsrc/signals.p
pop_asts_enabled updaterof $popsrc/signals.p
pop_callstack_lim $popsrc/pop_callstack_lim.p
pop_callstack_lim updaterof $popsrc/pop_callstack_lim.p
pop_charerr_device $popsrc/popdevout.p
pop_charerr_device updaterof $popsrc/popdevout.p
pop_charin_device $popsrc/popdevin.p
pop_charin_device updaterof $popsrc/popdevin.p
pop_chario_trap $popsrc/chario.p
pop_charout_device $popsrc/popdevout.p
pop_charout_device updaterof $popsrc/popdevout.p
pop_declare_incremental $popautolib/pop_declare_incremental.p
pop_default_device_encoding $popsrc/miscio.p
pop_default_device_encoding updaterof $popsrc/miscio.p
pop_default_section $popsrc/sect_current.p
pop_default_section updaterof $popsrc/sect_current.p
pop_enable_interrupts $popsrc/sig_async.p
pop_enable_interrupts updaterof $popsrc/sig_async.p
pop_exception_final $usepop/pop/x/ved/src/xved.p
pop_ext_call $popliblib/external_runtime.p
pop_hash_lim $popsrc/pop_hash_lim.p
pop_hash_lim updaterof $popsrc/pop_hash_lim.p
pop_heap_lock_count $popsrc/syslock.p
pop_heap_lock_count updaterof $popsrc/syslock.p
pop_malloc_min_alloc $popsrc/pop_malloc_min_alloc.p
pop_malloc_min_alloc updaterof $popsrc/pop_malloc_min_alloc.p
pop_mishap_doing_lim_convert $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_mishap_doing_lim_convert updaterof $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_module $usepop/pop/plog/src/modules.p
pop_new $usepop/pop/lib/objectclass/auto/instance.p
pop_nofast_trans $popautolib/pop_nofast_trans.p
pop_optimise $popautolib/pop_optimise.p
pop_optimise updaterof $popautolib/pop_optimise.p
pop_pas_mode $popsrc/vm_control.p
pop_pas_mode updaterof $popsrc/vm_control.p
pop_popc_flags $popautolib/compile_mode.p
pop_popc_flags updaterof $popautolib/compile_mode.p
pop_pr_exponent_convert $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_pr_exponent_convert updaterof $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_pr_level $popsrc/print.p
pop_pr_level updaterof $popsrc/print.p
pop_pr_places_convert $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_pr_places_convert updaterof $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_prolog_size $popsrc/plog_area.p
pop_prolog_size updaterof $popsrc/plog_area.p
pop_radians $usepop/pop/packages/popvision/lib/pop_radians.p
pop_radians updaterof $usepop/pop/packages/popvision/lib/pop_radians.p
pop_setpop_compiler $popsrc/subsystem_compile.p
pop_sys_encoding $popsrc/string.p
pop_sys_encoding updaterof $popsrc/string.p
pop_true $popsrc/lispcore.p
pop_ui_add_library $usepop/pop/x/ui/lib/pop_ui_librarytool.p
pop_ui_add_property $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_app_shell $usepop/pop/x/ui/lib/S-poplog_uiS-guiShells.p
pop_ui_app_shell updaterof $usepop/pop/x/ui/lib/S-poplog_uiS-guiShells.p
pop_ui_choose_file $usepop/pop/x/ui/lib/pop_ui_choose_file.p
pop_ui_close_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_compiletool $usepop/pop/x/ui/lib/pop_ui_filetool.p
pop_ui_confirm $usepop/pop/x/ui/lib/pop_ui_confirm.p
pop_ui_current_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_current_project updaterof $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_edittool $usepop/pop/x/ui/lib/pop_ui_filetool.p
pop_ui_filetool $usepop/pop/x/ui/lib/pop_ui_filetool.p
pop_ui_helptool $usepop/pop/x/ui/lib/pop_ui_helptool.p
pop_ui_information $usepop/pop/x/ui/lib/pop_ui_information.p
pop_ui_kill_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_libdescriptors $usepop/pop/x/ui/lib/pop_ui_librarytool.p
pop_ui_librarytool $usepop/pop/x/ui/lib/pop_ui_librarytool.p
pop_ui_logo $usepop/pop/x/ui/lib/pop_ui_logo.p
pop_ui_message $usepop/pop/x/ui/lib/pop_ui_message.p
pop_ui_new_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_open_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_popcontroltool $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
pop_ui_projectmkimagetool $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_projectprefstool $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_projecttool $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_promptsource $usepop/pop/x/ui/lib/pop_ui_prompttool.p
pop_ui_promptsource updaterof $usepop/pop/x/ui/lib/pop_ui_prompttool.p
pop_ui_prompttool $usepop/pop/x/ui/lib/pop_ui_prompttool.p
pop_ui_property_list $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_propertytool $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_read_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_remove_property $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_save_project $usepop/pop/x/ui/lib/pop_ui_projecttool.p
pop_ui_save_properties $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_setup $popliblib/poplog_ui.p
pop_ui_show_property $usepop/pop/x/ui/lib/pop_ui_propertytool.p
pop_ui_subsystem_libraries $usepop/pop/x/ui/lib/pop_ui_librarytool.p
pop_ui_text_input $usepop/pop/x/ui/lib/pop_ui_text_input.p
pop_view $popliblib/current_view.p
poparg1 $popautolib/poparg1.p
popcompiler $popvedlib/popcompiler.p
popcompiler updaterof $popvedlib/popcompiler.p
popcondition $usepop/pop/packages/teaching/lib/oldlisp.p
popconstants $popautolib/popconstants.p
popconstants updaterof $popautolib/popconstants.p
popdeverr $popsrc/popdevout.p
popdeverr updaterof $popsrc/popdevout.p
popdevin $popsrc/popdevin.p
popdevin updaterof $popsrc/popdevin.p
popdevout $popsrc/popdevout.p
popdevout updaterof $popsrc/popdevout.p
popdown_cb $usepop/pop/x/ui/lib/S-poplog_uiS-confirm_xm.p
poperp $popliblib/geometry.p
popindex $popautolib/popindex.p
popmemlim $popsrc/getstore.p
popmemlim updaterof $popsrc/getstore.p
popminmemlim $popsrc/getstore.p
popminmemlim updaterof $popsrc/getstore.p
popname $usepop/pop/packages/teaching/lib/oldlisp.p
popprint $popliblib/popprint.p
poprawdevin $popsrc/poprawdev.p
poprawdevin updaterof $popsrc/poprawdev.p
poprawdevout $popsrc/poprawdev.p
poprawdevout updaterof $popsrc/poprawdev.p
popready $popautolib/popready.p
popshowcodesyspdr $popliblib/showcode.p
popsyscall_convert $usepop/pop/x/ui/lib/pop_ui_propertytool.p
popsyscall_convert updaterof $usepop/pop/x/ui/lib/pop_ui_propertytool.p
poptovar $usepop/pop/pml/src/gencode.p
poptrace $popautolib/poptrace.p
popup_menu_pwm $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
popup_menu_x $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
popup_options $usepop/pop/packages/rclib/teach/rclib_demo.p
popval $popautolib/popval.p
popvedcommand $popsrc/syssetup.p
popwhere $popautolib/popwhere.p
posbounds $usepop/pop/packages/popvision/lib/rc_array.p
posintcheck $popvedlib/veddrawline.p
position $usepop/pop/pml/src/util.p
position $usepop/pop/x/ved/src/xvedresources.p
position updaterof $usepop/pop/x/ved/src/xvedresources.p
post1 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post1 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post1 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post1 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post1 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post1 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post10 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post10 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post10 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post10 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post10 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post10 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post2 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post2 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post2 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post2 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post2 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post2 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post3 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post3 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post3 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post3 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post3 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post3 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post4 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post4 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post4 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post4 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post4 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post4 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post5 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post5 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post5 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post5 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post5 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post5 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post6 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post6 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post6 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post6 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post6 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post6 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post7 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post7 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post7 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post7 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post7 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post7 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post8 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post8 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post8 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post8 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post8 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post8 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post9 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
post9 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
post9 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
post9 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
post9 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
post9 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
post_formatting_actions $popliblib/reformat.p
postfix_lprec $usepop/pop/plog/src/precedence.p
postfix_prec $usepop/pop/plog/src/precedence.p
postscript_line_consumer $popautolib/postscript_line_consumer.p
pp3add $popliblib/geom3d.p
pp_charout $usepop/pop/lisp/src/pp.p
pp_logical_block $usepop/pop/lisp/src/pp.p
pp_state $usepop/pop/lisp/src/pp.p
pp_state updaterof $usepop/pop/lisp/src/pp.p
ppdirection $popliblib/geometry.p
ppline $popliblib/geometry.p
ppppintersect $popliblib/geometry.p
ppr $popautolib/ppr.p
ppr $usepop/pop/packages/teaching/lib/logic.p
pprint_any $usepop/pop/lisp/src/printcore.p
pprint_dispatch $usepop/pop/lisp/src/pp-dispatch.p
pprint_exit $usepop/pop/lisp/src/pp.p
pprint_indent $usepop/pop/lisp/src/pp.p
pprint_logical_block $usepop/pop/lisp/src/pp.p
pprint_newline $usepop/pop/lisp/src/pp.p
pprint_pop $usepop/pop/lisp/src/pp.p
pprint_tab $usepop/pop/lisp/src/pp.p
pprint_test_exit $usepop/pop/lisp/src/pp.p
ppseg $popliblib/geometry.p
ppvec $popliblib/geometry.p
pr_aexp $usepop/pop/pml/src/type_errors.p
pr_andalso_exp $usepop/pop/pml/src/type_errors.p
pr_apat $usepop/pop/pml/src/type_errors.p
pr_appexp $usepop/pop/pml/src/type_errors.p
pr_apppat $usepop/pop/pml/src/type_errors.p
pr_bpactivs $usepop/pop/packages/neural/lib/backprop.p
pr_bpweights $usepop/pop/packages/neural/lib/backprop.p
pr_circular_list $usepop/pop/packages/popvision/lib/snakes.p
pr_clactivs $usepop/pop/packages/neural/lib/complearn.p
pr_clause $usepop/pop/pml/src/type_errors.p
pr_clweights $usepop/pop/packages/neural/lib/complearn.p
pr_constype $usepop/pop/pml/src/print_types.p
pr_exp $usepop/pop/pml/src/type_errors.p
pr_external_require_load_warn $popautolib/external_require.p
pr_field $popsrc/pr_field.p
pr_form $usepop/pop/pml/src/type_errors.p
pr_funtype $usepop/pop/pml/src/print_types.p
pr_header $usepop/pop/packages/newkit/prb/auto/prb_saverules.p
pr_id $usepop/pop/pml/src/type_errors.p
pr_instance $usepop/pop/lisp/src/methods.p
pr_listparts $usepop/pop/packages/neural/src/pop/nui_txtbrowser.p
pr_match $usepop/pop/pml/src/type_errors.p
pr_orelse_exp $usepop/pop/pml/src/type_errors.p
pr_pat $usepop/pop/pml/src/type_errors.p
pr_patt_var_warning $popliblib/readpattern.p
pr_patt_var_warning $usepop/pop/packages/newkit/prb/lib/readpattern.p
pr_pop11_simple $usepop/pop/lisp/src/printcore.p
pr_record $usepop/pop/pml/src/type_errors.p
pr_recordtype $usepop/pop/pml/src/print_types.p
pr_rule $usepop/pop/pml/src/type_errors.p
pr_sequence $usepop/pop/pml/src/type_errors.p
pr_structure $usepop/pop/lisp/src/defstruct.p
pr_sym_name $usepop/pop/lisp/src/print.p
pr_tupletype $usepop/pop/pml/src/print_types.p
pr_type $usepop/pop/pml/src/print_types.p
pr_typed_exp $usepop/pop/pml/src/type_errors.p
pr_typed_pat $usepop/pop/pml/src/type_errors.p
pr_valbind $usepop/pop/pml/src/type_errors.p
pr_vartype $usepop/pop/pml/src/print_types.p
practor $popliblib/actor.p
praxis $popliblib/geom3d.p
prb_ADD $usepop/pop/packages/lib/poprulebase.p
prb_ADD $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_ADDALL $usepop/pop/packages/lib/poprulebase.p
prb_ADDALL $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_ADDIF $usepop/pop/packages/lib/poprulebase.p
prb_ADDIF $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_ADDUNLESS $usepop/pop/packages/lib/poprulebase.p
prb_ADDUNLESS $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_DADD $usepop/pop/packages/newkit/prb/auto/prb_DDEL.p
prb_DADD $usepop/pop/packages/newkit/prb/incomplete/prb_DDEL.p
prb_DDEL $usepop/pop/packages/newkit/prb/auto/prb_DDEL.p
prb_DDEL $usepop/pop/packages/newkit/prb/incomplete/prb_DDEL.p
prb_DEL $usepop/pop/packages/lib/poprulebase.p
prb_DEL $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_DEL_THIS_RULESET $usepop/pop/packages/newkit/sim/lib/prb_DEL_THIS_RULESET.p
prb_EXPLAIN $usepop/pop/packages/lib/poprulebase.p
prb_EXPLAIN $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_MODIFY $usepop/pop/packages/lib/poprulebase.p
prb_MODIFY $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_POPRULESET $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_POPRULESET $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_PUSHRULESET $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_PUSHRULESET $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_QUIT $usepop/pop/packages/lib/poprulebase.p
prb_QUIT $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_QUITIF $usepop/pop/packages/lib/poprulebase.p
prb_QUITIF $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_REPLACE $usepop/pop/packages/lib/poprulebase.p
prb_REPLACE $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_RESTORERULESET $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_RESTORERULESET $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_RMODIFY $usepop/pop/packages/newkit/prb/auto/prb_RMODIFY.p
prb_SAVERULESET $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_SAVERULESET $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_SAY $usepop/pop/packages/lib/poprulebase.p
prb_SAY $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_SAYIF $usepop/pop/packages/lib/poprulebase.p
prb_SAYIF $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_STOP $usepop/pop/packages/lib/poprulebase.p
prb_STOP $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_STOPAGENT $usepop/pop/packages/newkit/sim/lib/sim_agent.p
prb_STOPAGENTIF $usepop/pop/packages/newkit/sim/lib/sim_agent.p
prb_STOPIF $usepop/pop/packages/lib/poprulebase.p
prb_STOPIF $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_SWITCHRULESET $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_SWITCHRULESET $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_TEST_ADD $usepop/pop/packages/lib/poprulebase.p
prb_TEST_ADD $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_XXX $usepop/pop/packages/lib/poprulebase.p
prb_XXX $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_action_type $usepop/pop/packages/lib/poprulebase.p
prb_action_type $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_activation_name $usepop/pop/packages/lib/poprulebase.p
prb_activation_name $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_add $usepop/pop/packages/lib/poprulebase.p
prb_add $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_add_action_vars $usepop/pop/packages/lib/poprulebase.p
prb_add_action_vars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_add_condition_vars $usepop/pop/packages/lib/poprulebase.p
prb_add_condition_vars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_add_db_to_db $usepop/pop/packages/lib/poprulebase.p
prb_add_db_to_db $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_add_list_to_db $usepop/pop/packages/newkit/prb/auto/prb_add_list_to_db.p
prb_add_to_db $usepop/pop/packages/lib/poprulebase.p
prb_add_to_db $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_adding_trace $usepop/pop/packages/lib/poprulebase.p
prb_adding_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_all_conditions_satisfied_trace $usepop/pop/packages/lib/poprulebase.p
prb_all_conditions_satisfied_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_allpresent $usepop/pop/packages/newkit/prb/auto/prb_allpresent.p
prb_applicable $usepop/pop/packages/lib/poprulebase.p
prb_applicable $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_assign_->> $usepop/pop/packages/lib/poprulebase.p
prb_assign_->> $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_assoc $usepop/pop/packages/lib/poprulebase.p
prb_assoc $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_assoc_memb $usepop/pop/packages/newkit/prb/auto/prb_assoc_memb.p
prb_check_cycle_limit_and_vars $usepop/pop/packages/newkit/prb/auto/prb_check_cycle_limit_and_vars.p
prb_check_pop_code $usepop/pop/packages/lib/poprulebase.p
prb_check_pop_code $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_check_section $usepop/pop/packages/lib/poprulebase.p
prb_check_section $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_check_stack $usepop/pop/packages/lib/poprulebase.p
prb_check_stack $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_check_vars_vec $usepop/pop/packages/newkit/prb/auto/prb_check_vars_vec.p
prb_checking_conditions_trace $usepop/pop/packages/lib/poprulebase.p
prb_checking_conditions_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_checking_one_condition_trace $usepop/pop/packages/lib/poprulebase.p
prb_checking_one_condition_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_checkpatterns $usepop/pop/packages/newkit/prb/auto/prb_checkpatterns.p
prb_clearstacks $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_collect_values $usepop/pop/packages/newkit/prb/auto/prb_collect_values.p
prb_compile_procedure $usepop/pop/packages/lib/poprulebase.p
prb_compile_procedure $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_condition_failed_trace $usepop/pop/packages/lib/poprulebase.p
prb_condition_failed_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_condition_satisfied_trace $usepop/pop/packages/lib/poprulebase.p
prb_condition_satisfied_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_condition_type $usepop/pop/packages/lib/poprulebase.p
prb_condition_type $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_consrulefamily $usepop/pop/packages/newkit/prb/auto/prb_consrulefamily.p
prb_current_data_stack $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_current_data_stack updaterof $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_current_rule_stack $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_current_rule_stack updaterof $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_database_keys $usepop/pop/packages/lib/poprulebase.p
prb_database_keys $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_declare $usepop/pop/packages/lib/poprulebase.p
prb_declare $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_declare_lvar $usepop/pop/packages/lib/poprulebase.p
prb_declare_lvar $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_del1 $usepop/pop/packages/lib/poprulebase.p
prb_del1 $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_delete_rule $usepop/pop/packages/newkit/prb/auto/prb_delete_rule.p
prb_deleting_pattern_trace $usepop/pop/packages/lib/poprulebase.p
prb_deleting_pattern_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_deleting_trace $usepop/pop/packages/lib/poprulebase.p
prb_deleting_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_displayrule $usepop/pop/packages/newkit/prb/auto/prb_interact.p
prb_divides_chatty $usepop/pop/packages/lib/poprulebase.p
prb_divides_chatty $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_dl $usepop/pop/packages/lib/poprulebase.p
prb_dl $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_DEL $usepop/pop/packages/lib/poprulebase.p
prb_do_DEL $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_POP11 $usepop/pop/packages/lib/poprulebase.p
prb_do_POP11 $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_POPDATA $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_do_POPRULES $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_do_PUSHDATA $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_do_PUSHRULES $usepop/pop/packages/newkit/prb/lib/prb_extra.p
prb_do_action $usepop/pop/packages/lib/poprulebase.p
prb_do_action $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_action_now $usepop/pop/packages/lib/poprulebase.p
prb_do_action_now $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_action_trace $usepop/pop/packages/lib/poprulebase.p
prb_do_action_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_actions $usepop/pop/packages/lib/poprulebase.p
prb_do_actions $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_all $usepop/pop/packages/newkit/prb/auto/prb_do_all.p
prb_do_cut $usepop/pop/packages/lib/poprulebase.p
prb_do_cut $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_in_data $usepop/pop/packages/lib/poprulebase.p
prb_do_in_data $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_rule_actions $usepop/pop/packages/lib/poprulebase.p
prb_do_rule_actions $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_do_rules $usepop/pop/packages/lib/poprulebase.p
prb_do_rules $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_doing_actions_trace $usepop/pop/packages/lib/poprulebase.p
prb_doing_actions_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_empty $usepop/pop/packages/lib/poprulebase.p
prb_empty $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_eval $usepop/pop/packages/lib/poprulebase.p
prb_eval $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_eval_list $usepop/pop/packages/lib/poprulebase.p
prb_eval_list $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_expound $usepop/pop/packages/newkit/prb/auto/prb_interact.p
prb_extend_popmatchvars $usepop/pop/packages/lib/poprulebase.p
prb_extend_popmatchvars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_extract_vars $usepop/pop/packages/lib/poprulebase.p
prb_extract_vars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_finish $usepop/pop/packages/lib/poprulebase.p
prb_finish $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_finish $usepop/pop/packages/newkit/prb/test/check.p
prb_finish $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_fix_embedded_forms $usepop/pop/packages/lib/poprulebase.p
prb_fix_embedded_forms $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_flush $usepop/pop/packages/lib/poprulebase.p
prb_flush $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_flush1 $usepop/pop/packages/lib/poprulebase.p
prb_flush1 $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_foreach $usepop/pop/packages/newkit/prb/auto/prb_foreach.p
prb_forevery $usepop/pop/packages/lib/poprulebase.p
prb_forevery $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_forget_rules $usepop/pop/packages/lib/poprulebase.p
prb_forget_rules $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_has_variables $usepop/pop/packages/lib/poprulebase.p
prb_has_variables $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_implies $usepop/pop/packages/newkit/prb/auto/prb_implies.p
prb_in_data $usepop/pop/packages/lib/poprulebase.p
prb_in_data $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_in_database $usepop/pop/packages/newkit/prb/auto/prb_in_database.p
prb_instance $usepop/pop/packages/lib/poprulebase.p
prb_instance $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_instance_present $usepop/pop/packages/lib/poprulebase.p
prb_instance_present $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_instantiate_first $usepop/pop/packages/lib/poprulebase.p
prb_instantiate_first $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_interact $usepop/pop/packages/newkit/prb/auto/prb_interact.p
prb_is_var_key $usepop/pop/packages/lib/poprulebase.p
prb_is_var_key $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_istraced $usepop/pop/packages/lib/poprulebase.p
prb_istraced $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_ldeclare $usepop/pop/packages/lib/poprulebase.p
prb_ldeclare $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_list_data $usepop/pop/packages/newkit/prb/auto/prb_list_data.p
prb_make_rule $usepop/pop/packages/newkit/prb/auto/prb_make_rule.p
prb_map_action $usepop/pop/packages/newkit/prb/auto/prb_map_action.p
prb_match_apply $usepop/pop/packages/lib/poprulebase.p
prb_match_apply $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_match_apply_keys $usepop/pop/packages/lib/poprulebase.p
prb_match_apply_keys $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_member $usepop/pop/packages/lib/poprulebase.p
prb_member $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_menu_interact $usepop/pop/packages/newkit/prb/auto/prb_read_info.p
prb_modify_trace $usepop/pop/packages/lib/poprulebase.p
prb_modify_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_new_rule $usepop/pop/packages/lib/poprulebase.p
prb_new_rule $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_newdatabase $usepop/pop/packages/lib/poprulebase.p
prb_newdatabase $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_no_rule_found_action $usepop/pop/packages/lib/poprulebase.p
prb_no_rule_found_action $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_no_rule_found_trace $usepop/pop/packages/lib/poprulebase.p
prb_no_rule_found_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_no_variables $usepop/pop/packages/lib/poprulebase.p
prb_no_variables $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_object_matches $usepop/pop/packages/newkit/prb/lib/prb_trace_procs.p
prb_pattern_matched_trace $usepop/pop/packages/lib/poprulebase.p
prb_pattern_matched_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_pause_read $usepop/pop/packages/newkit/prb/auto/prb_read_info.p
prb_pr_rule $usepop/pop/packages/newkit/prb/auto/prb_pr_rule.p
prb_present $usepop/pop/packages/lib/poprulebase.p
prb_present $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_present_keys $usepop/pop/packages/lib/poprulebase.p
prb_present_keys $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_print_database $usepop/pop/packages/lib/poprulebase.p
prb_print_database $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_print_menu $usepop/pop/packages/newkit/prb/auto/prb_print_menu.p
prb_print_rule $usepop/pop/packages/lib/poprulebase.p
prb_print_rule $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_print_rulefamily $usepop/pop/packages/newkit/prb/lib/newrulefamily.p
prb_print_rulefamily $usepop/pop/packages/newkit/prb/lib/rulefamily.p
prb_print_table $usepop/pop/packages/lib/poprulebase.p
prb_print_table $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_push_or_pop $usepop/pop/packages/newkit/prb/auto/prb_push_or_pop.p
prb_read_VARS $usepop/pop/packages/lib/poprulebase.p
prb_read_VARS $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_read_actions $usepop/pop/packages/lib/poprulebase.p
prb_read_actions $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_read_and_add $usepop/pop/packages/newkit/prb/auto/prb_read_info.p
prb_read_conditions $usepop/pop/packages/lib/poprulebase.p
prb_read_conditions $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_read_header $usepop/pop/packages/newkit/prb/auto/prb_read_header.p
prb_read_info $usepop/pop/packages/newkit/prb/auto/prb_read_info.p
prb_read_vars_spec $usepop/pop/packages/newkit/prb/auto/prb_read_vars_spec.p
prb_readaction $usepop/pop/packages/lib/poprulebase.p
prb_readaction $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_readcondition $usepop/pop/packages/lib/poprulebase.p
prb_readcondition $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_remove_all $usepop/pop/packages/newkit/prb/auto/prb_remove_all.p
prb_replace $usepop/pop/packages/newkit/prb/auto/prb_replace.p
prb_restore_database $usepop/pop/packages/newkit/prb/auto/prb_restore_database.p
prb_restore_database $usepop/pop/packages/newkit/prb/auto/prb_save_database.p
prb_rule_named $usepop/pop/packages/lib/poprulebase.p
prb_rule_named $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_rule_section $usepop/pop/packages/lib/poprulebase.p
prb_rule_section $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_rule_weight $usepop/pop/packages/newkit/prb/auto/prb_rule_weight.p
prb_rule_weight updaterof $usepop/pop/packages/newkit/prb/auto/prb_rule_weight.p
prb_rules $usepop/pop/packages/newkit/prb/teach/prbrunriver.p
prb_rules $usepop/pop/packages/newkit/prb/test/check.p
prb_rules $usepop/pop/packages/newkit/prb/test/prbrunriver.p
prb_rules $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
prb_rules $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
prb_rules $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_rules $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_rules $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_rules_traced $usepop/pop/packages/newkit/prb/lib/prb_trace_procs.p
prb_ruleschanged_trace $usepop/pop/packages/lib/poprulebase.p
prb_ruleschanged_trace $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_run $usepop/pop/packages/lib/poprulebase.p
prb_run $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_run_with_matchvars $usepop/pop/packages/lib/poprulebase.p
prb_run_with_matchvars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_save_database $usepop/pop/packages/newkit/prb/auto/prb_restore_database.p
prb_save_database $usepop/pop/packages/newkit/prb/auto/prb_save_database.p
prb_save_or_restore $usepop/pop/packages/newkit/prb/auto/prb_save_or_restore.p
prb_saverules $usepop/pop/packages/newkit/prb/auto/prb_saverules.p
prb_select_action $usepop/pop/packages/newkit/prb/auto/prb_select_action.p
prb_show_full_trace $usepop/pop/packages/newkit/prb/lib/prb_trace_procs.p
prb_show_rules $usepop/pop/packages/newkit/prb/auto/prb_show_rules.p
prb_sort_traces $usepop/pop/packages/newkit/prb/lib/prb_trace_procs.p
prb_sortrules $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_sortrules $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
prb_sortrules $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
prb_sortrules $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
prb_storedata $usepop/pop/packages/newkit/prb/auto/prb_storedata.p
prb_subflush_fixed $usepop/pop/packages/lib/poprulebase.p
prb_subflush_fixed $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_subflush_var $usepop/pop/packages/lib/poprulebase.p
prb_subflush_var $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_trace $usepop/pop/packages/newkit/prb/auto/prb_trace.p
prb_trace_rule $usepop/pop/packages/newkit/prb/auto/prb_trace_rule.p
prb_trace_rule_stats $usepop/pop/packages/newkit/prb/lib/prb_trace_procs.p
prb_truncate $usepop/pop/packages/newkit/prb/auto/prb_truncate.p
prb_untrace $usepop/pop/packages/newkit/prb/auto/prb_untrace.p
prb_valof $usepop/pop/packages/lib/poprulebase.p
prb_valof $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_value $usepop/pop/packages/lib/poprulebase.p
prb_value $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_variables_in $usepop/pop/packages/lib/poprulebase.p
prb_variables_in $usepop/pop/packages/newkit/prb/lib/poprulebase.p
prb_walk_trace $usepop/pop/packages/newkit/prb/auto/prb_walk_trace.p
prb_which_values $usepop/pop/packages/newkit/prb/auto/prb_which_values.p
prcfloatvec $usepop/pop/packages/popvision/lib/newcfloatarray.p
prchar $usepop/pop/packages/vedutils/auto/ved_keymap.p
prchars $usepop/pop/packages/vedutils/auto/ved_keymap.p
prec_word $usepop/pop/packages/popvision/lib/lapack.p
precedence $usepop/pop/lib/lr_parser/auto/define_parser.p
precedence_table $usepop/pop/plog/src/precedence.p
precedencelist $usepop/pop/lib/flavours/flavecore.p
precomp_clause $usepop/pop/plog/src/gencode.p
pred_declare $usepop/pop/plog/src/predicate_record.p
pred_has_clauses $usepop/pop/plog/src/predicate_record.p
pred_idval $usepop/pop/plog/src/predicate_record.p
pred_idval updaterof $usepop/pop/plog/src/predicate_record.p
pred_isdefined $usepop/pop/plog/src/predicate_record.p
pred_raw_valof $usepop/pop/plog/src/predicate_record.p
pred_raw_valof updaterof $usepop/pop/plog/src/predicate_record.p
pred_spec $usepop/pop/plog/src/predicate_record.p
pred_valof $usepop/pop/plog/src/predicate_record.p
pred_valof updaterof $usepop/pop/plog/src/predicate_record.p
predicate_abolish $usepop/pop/plog/src/predicate_abolish.p
predicate_define $usepop/pop/plog/src/predicate_define.p
predicate_has_clauses $usepop/pop/plog/src/predicate_has_clauses.p
predicate_info $usepop/pop/plog/src/predicate_info.p
predicate_isdefined $usepop/pop/plog/src/predicate_valof.p
predicate_record $usepop/pop/plog/src/predicate_record.p
predicate_table $usepop/pop/plog/src/predicate_record.p
predicate_valof $usepop/pop/plog/src/predicate_valof.p
predict $usepop/pop/packages/teaching/lib/analogy.p
prefix $usepop/pop/lib/obsolete/prefix.p
prefix_field $popliblib/typespec_utils.p
prefix_prec $usepop/pop/plog/src/precedence.p
prefix_rprec $usepop/pop/plog/src/precedence.p
pregen $usepop/pop/pml/src/pregen.p
pregen_app_exp $usepop/pop/pml/src/pregen.p
pregen_const $usepop/pop/pml/src/pregen.p
pregen_dec $usepop/pop/pml/src/pregen.p
pregen_decs $usepop/pop/pml/src/pregen.p
pregen_exp $usepop/pop/pml/src/pregen.p
pregen_fn $usepop/pop/pml/src/pregen.p
pregen_fnc_dec $usepop/pop/pml/src/pregen.p
pregen_fun_bind $usepop/pop/pml/src/pregen.p
pregen_handler $usepop/pop/pml/src/pregen.p
pregen_lastexp $usepop/pop/pml/src/pregen.p
pregen_let_exp $usepop/pop/pml/src/pregen.p
pregen_list_exp $usepop/pop/pml/src/pregen.p
pregen_list_pat $usepop/pop/pml/src/pregen.p
pregen_match $usepop/pop/pml/src/pregen.p
pregen_pat $usepop/pop/pml/src/pregen.p
pregen_record_exp $usepop/pop/pml/src/pregen.p
pregen_record_pat $usepop/pop/pml/src/pregen.p
pregen_seq_exp $usepop/pop/pml/src/pregen.p
pregen_str_bind $usepop/pop/pml/src/pregen.p
pregen_strdec $usepop/pop/pml/src/pregen.p
pregen_strdecs $usepop/pop/pml/src/pregen.p
pregen_strexp $usepop/pop/pml/src/pregen.p
pregen_tuple_exp $usepop/pop/pml/src/pregen.p
pregen_val_bind $usepop/pop/pml/src/pregen.p
pregen_val_dec $usepop/pop/pml/src/pregen.p
pregen_val_exp $usepop/pop/pml/src/pregen.p
premise $usepop/pop/packages/teaching/lib/rmsapps.p
prepare $usepop/pop/lib/obsolete/hangman.p
prepare_addresses_list $usepop/pop/packages/vedmail/auto/ved_tah.p
prepare_addresses_list $usepop/pop/packages/vedmail/auto/ved_tmh.p
prepare_for_printing $usepop/pop/packages/rclib/lib/rc_text_input.p
prepare_for_printing $usepop/pop/packages/rclib/lib/rc_text_input.p
prepare_index_label $popliblib/reformat.p
prepare_internal_label $popliblib/reformat.p
preprocess $popliblib/reformat.p
preprocess $usepop/pop/packages/teaching/lib/blocks/utils.p
present $popliblib/super.p
present $usepop/pop/lib/database/present.p
present_in $popautolib/present_in.p
pretty $popsrc/pretty.p
primitive_type $popautolib/kr_newc_dec.p
primitive_type $popautolib/newc_dec.p
primitive_type $usepop/pop/packages/newc_dec/auto/newc_dec.p
print $popliblib/pop2.p
print $usepop/pop/packages/rcmenu/menus/menu_print.p
print_activs $usepop/pop/packages/neural/src/pop/nui_main.p
print_any $usepop/pop/pml/src/print_data.p
print_bindings $usepop/pop/pml/src/print_bindings.p
print_by_key $usepop/pop/lisp/src/printcore.p
print_case $usepop/pop/lisp/src/print.p
print_case updaterof $usepop/pop/lisp/src/print.p
print_culprit $usepop/pop/plog/src/prolog_exceptions.p
print_directive $usepop/pop/pml/src/print_bindings.p
print_entry $usepop/pop/pml/src/env.p
print_exception $usepop/pop/pml/src/print_data.p
print_fnc $usepop/pop/pml/src/print_bindings.p
print_fnc_args $usepop/pop/pml/src/print_bindings.p
print_fun $usepop/pop/pml/src/print_data.p
print_help $usepop/pop/packages/teaching/lib/finger.p
print_ident $popliblib/readpattern.p
print_ident $usepop/pop/packages/lib/poprulebase.p
print_ident $usepop/pop/packages/newkit/prb/lib/poprulebase.p
print_ident $usepop/pop/packages/newkit/prb/lib/readpattern.p
print_if_non_empty $usepop/pop/packages/lib/poprulebase.p
print_if_non_empty $usepop/pop/packages/newkit/prb/lib/poprulebase.p
print_indent $usepop/pop/lisp/src/pp.p
print_instance $usepop/pop/lib/objectclass/lib/objectclass_example.p
print_instance $usepop/pop/lib/objectclass/lib/objectclass_example.p
print_instance $usepop/pop/lib/objectclass/src/objectclasses.p
print_instance $usepop/pop/lib/objectclass/src/objectclasses.p
print_instance $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
print_instance $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
print_instance $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
print_instance $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
print_instance $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_agent.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/teach/armysim.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
print_instance $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
print_instance $usepop/pop/packages/rclib/auto/rc_constrained_pointer.p
print_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
print_instance $usepop/pop/packages/rclib/auto/rc_slider.p
print_instance $usepop/pop/packages/rclib/auto/rc_slider.p
print_instance $usepop/pop/packages/rclib/demo/painting_demo.p
print_instance $usepop/pop/packages/rclib/demo/painting_demo.p
print_instance $usepop/pop/packages/rclib/lib/painting_demo.p
print_instance $usepop/pop/packages/rclib/lib/painting_demo.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_buttons.p
print_instance $usepop/pop/packages/rclib/lib/rc_linked_pic.p
print_instance $usepop/pop/packages/rclib/lib/rc_linked_pic.p
print_instance $usepop/pop/packages/rclib/lib/rc_panel_slider.p
print_instance $usepop/pop/packages/rclib/lib/rc_panel_slider.p
print_instance $usepop/pop/packages/rclib/lib/rc_point.p
print_instance $usepop/pop/packages/rclib/lib/rc_polyline.p
print_instance $usepop/pop/packages/rclib/lib/rc_polyline.p
print_instance $usepop/pop/packages/rclib/lib/rc_scrolltext.p
print_instance $usepop/pop/packages/rclib/lib/rc_text_input.p
print_instance $usepop/pop/packages/rclib/lib/rc_text_input.p
print_instance $usepop/pop/packages/rclib/lib/rc_window_object.p
print_instance $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
print_instance $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
print_instance $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
print_instance $usepop/pop/packages/rclib/teach/rclib_demo.p
print_instance $usepop/pop/packages/rclib/teach/rclib_demo.p
print_list $usepop/pop/packages/neural/src/pop/nui_utils.p
print_list $usepop/pop/pml/src/print_data.p
print_list_nice $popliblib/tree_identify.p
print_loc $usepop/pop/packages/newkit/sim/lib/sim_harness.p
print_loc_heading $usepop/pop/packages/newkit/sim/lib/sim_harness.p
print_logical_block $usepop/pop/lisp/src/pp.p
print_menu_txt $usepop/pop/packages/neural/src/pop/nui_txtpanels.p
print_newline $usepop/pop/lisp/src/pp.p
print_not_readable $usepop/pop/lisp/src/printcore.p
print_num $usepop/pop/pml/src/print_data.p
print_record $usepop/pop/pml/src/print_data.p
print_ref $usepop/pop/pml/src/print_data.p
print_results $usepop/pop/packages/neural/src/pop/nn_training.p
print_sig $usepop/pop/pml/src/print_bindings.p
print_sig_binding $usepop/pop/pml/src/print_bindings.p
print_signature $usepop/pop/pml/src/print_bindings.p
print_str $usepop/pop/pml/src/print_bindings.p
print_str_bindings $usepop/pop/pml/src/print_bindings.p
print_strenv $usepop/pop/pml/src/print_bindings.p
print_string $usepop/pop/pml/src/print_data.p
print_to_strings $usepop/pop/packages/rclib/auto/print_to_strings.p
print_top_binding $usepop/pop/pml/src/print_bindings.p
print_top_bindings $usepop/pop/pml/src/print_bindings.p
print_tuple $usepop/pop/pml/src/print_data.p
print_tycon $usepop/pop/pml/src/print_bindings.p
print_type $usepop/pop/pml/src/print_types.p
print_unit $usepop/pop/pml/src/print_data.p
print_val $usepop/pop/pml/src/print_bindings.p
print_vehicle_data_log $usepop/pop/packages/brait/lib/vehicle_agent.p
print_weights $usepop/pop/packages/neural/src/pop/nui_main.p
print_window $popvedlib/windows.p
printeval $usepop/pop/packages/teaching/lib/logic.p
printf $popsrc/print.p
printlength $popautolib/printlength.p
printnames $usepop/pop/packages/popvision/lib/arrpack.p
printresdip $usepop/pop/packages/neural/demos/dipole.p
printresvh $usepop/pop/packages/neural/demos/verthorz.p
priormemb $usepop/pop/packages/teaching/lib/eprospect.p
privpix24 $usepop/pop/packages/popvision/lib/rc_array.p
privpix8 $usepop/pop/packages/popvision/lib/rc_array.p
prlist $usepop/pop/packages/teaching/lib/analogy.p
prlpar $usepop/pop/pml/src/print_data.p
prnum $popautolib/prnum.p
prob $usepop/pop/packages/teaching/lib/eprospect.p
prob updaterof $usepop/pop/packages/teaching/lib/eprospect.p
probe_file $usepop/pop/lisp/src/files.p
problem1_fitness $usepop/pop/packages/teaching/teach/ga_dejong.p
problem1_printer $usepop/pop/packages/teaching/teach/ga_dejong.p
problem2_fitness $usepop/pop/packages/teaching/teach/ga_dejong.p
problem2_printer $usepop/pop/packages/teaching/teach/ga_dejong.p
problem3_fitness $usepop/pop/packages/teaching/teach/ga_dejong.p
problem3_printer $usepop/pop/packages/teaching/teach/ga_dejong.p
problem4_fitness $usepop/pop/packages/teaching/teach/ga_dejong.p
proc $usepop/pop/ved/src/vdregexp.p
proc_clauses $usepop/pop/plog/src/procedures.p
proc_clauses updaterof $usepop/pop/plog/src/procedures.p
proc_name $usepop/pop/plog/src/procedures.p
proc_name updaterof $usepop/pop/plog/src/procedures.p
process_args $usepop/pop/lib/objectclass/auto/ved_oc.p
process_contents_and_overview $popliblib/reformat.p
process_date_string $usepop/pop/x/ui/lib/S-poplog_uiS-guiTimeUtils.p
process_decl $popautolib/define_inline.p
process_defer_list $usepop/pop/packages/rclib/lib/rc_mousepic.p
process_directive $popautolib/format_print.p
process_html $usepop/pop/packages/vedmail/auto/ved_decode.p
process_link_args $popsrc/unixextern.p
process_method_init $usepop/pop/lib/objectclass/auto/instance.p
process_qp $usepop/pop/packages/vedmail/auto/ved_decode.p
process_sentence $usepop/pop/packages/rclib/lib/rc_blocks.p
process_spec $usepop/pop/x/pop/auto/XptEvenlySizeWidgets.p
process_time_string $usepop/pop/x/ui/lib/S-poplog_uiS-guiTimeUtils.p
process_ved_ocg_args $usepop/pop/lib/objectclass/auto/ved_ocg.p
processconstraint $usepop/pop/packages/teaching/auto/ved_vcalc.p
processequation $usepop/pop/packages/teaching/auto/ved_vcalc.p
processing $usepop/pop/packages/brait/lib/vehicle_agent.p
processpic $usepop/pop/packages/teaching/lib/analogy.p
processpicture $usepop/pop/lib/turtle/convolve.p
proclaim $usepop/pop/lisp/src/declare.p
prodof $usepop/pop/packages/teaching/auto/ved_vcalc.p
professor $usepop/pop/lib/objectclass/lib/objectclass_example.p
profile $popliblib/profile.p
profile $usepop/pop/packages/newkit/prb/lib/prb_profile.p
profile_apply $popliblib/profile.p
profile_apply $usepop/pop/packages/newkit/prb/lib/prb_profile.p
profile_display $usepop/pop/packages/newkit/prb/lib/prb_profile.p
profile_graph $popliblib/profile_graphical.p
profile_graph_paint $popliblib/profile_graphical.p
profile_ignore $popliblib/profile.p
profile_ignore $usepop/pop/packages/newkit/prb/lib/prb_profile.p
profile_include $popliblib/profile.p
profile_include $usepop/pop/packages/newkit/prb/lib/prb_profile.p
profile_print $popliblib/profile.p
profile_report $popliblib/profile.p
profile_report $popliblib/profile_graphical.p
proglist_new_state $popsrc/hash_include.p
proglist_read_by $popautolib/proglist_read_by.p
proglist_state $popsrc/hash_include.p
proglist_state updaterof $popsrc/hash_include.p
program_error $usepop/pop/lisp/src/util.p
project $popliblib/geom3d.p
project_close $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
project_new $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
project_open $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
project_popup_cb $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
project_save $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
projfile_vedpresent $usepop/pop/x/ui/lib/pop_ui_projecttool.p
projmenu_cb $usepop/pop/x/ui/lib/pop_ui_projecttool.p
prolog $popautolib/define_prolog.p
prolog $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_<= $usepop/pop/plog/src/sortpreds.p
prolog_abolish_command $usepop/pop/plog/src/commands.p
prolog_appargs $popsrc/plogterms.p
prolog_appargs_nd $popsrc/plogterms.p
prolog_apply_continuation $popsrc/plogcore.p
prolog_apppredicates_defined $usepop/pop/plog/src/obsolete.p
prolog_area_accept $usepop/pop/plog/src/prolog_ui.p
prolog_area_size $usepop/pop/plog/src/prolog_ui.p
prolog_area_size updaterof $usepop/pop/plog/src/prolog_ui.p
prolog_arg $popsrc/plogterms.p
prolog_arg_nd $popsrc/plogterms.p
prolog_arg_nd updaterof $popsrc/plogterms.p
prolog_args $popsrc/plogterms.p
prolog_args_nd $popsrc/plogterms.p
prolog_arity $popsrc/plogterms.p
prolog_assert $usepop/pop/plog/src/dbpreds.p
prolog_asserta $usepop/pop/plog/src/dbpreds.p
prolog_assertz $usepop/pop/plog/src/dbpreds.p
prolog_assign $popsrc/plogcore.p
prolog_assign_check $popsrc/plogcore.p
prolog_atom $usepop/pop/plog/src/util.p
prolog_atomic $usepop/pop/plog/src/util.p
prolog_backtrace $usepop/pop/plog/src/prolog_exceptions.p
prolog_barrier_apply $popsrc/plogcore.p
prolog_barrier_invoke $popliblib/plog_goals.p
prolog_body $usepop/pop/plog/src/util.p
prolog_call $usepop/pop/plog/src/spy.p
prolog_checkspec $popsrc/plogterms.p
prolog_clause $usepop/pop/plog/src/dbpreds.p
prolog_clauses $usepop/pop/plog/src/dbpreds.p
prolog_command $usepop/pop/plog/src/commands.p
prolog_compare $usepop/pop/plog/src/sortpreds.p
prolog_compile $popautolib/prolog_compile.p
prolog_compile $usepop/pop/plog/src/prolog_compile.p
prolog_complexterm $popsrc/plogterms.p
prolog_conditional $usepop/pop/plog/src/optcontrol.p
prolog_conjunction $usepop/pop/plog/src/optcontrol.p
prolog_cucharin $usepop/pop/plog/src/iopreds.p
prolog_cut $usepop/pop/plog/src/optcontrol.p
prolog_define $usepop/pop/plog/src/obsolete.p
prolog_deref $popsrc/plogcore.p
prolog_directive $usepop/pop/plog/src/prolog_compile.p
prolog_disjunction $usepop/pop/plog/src/optcontrol.p
prolog_display $usepop/pop/plog/src/write.p
prolog_doeval $usepop/pop/plog/src/prolog_eval.p
prolog_error_handler $usepop/pop/plog/src/prolog_exceptions.p
prolog_eval $usepop/pop/plog/src/prolog_eval.p
prolog_eval $usepop/pop/plog/src/prolog_eval.p
prolog_evaltrue $usepop/pop/plog/src/prolog_eval.p
prolog_exception_final $usepop/pop/plog/src/prolog_exceptions.p
prolog_fail_if $usepop/pop/plog/src/optcontrol.p
prolog_fail_label $usepop/pop/plog/src/gencode.p
prolog_file_type $usepop/pop/plog/src/prolog_compile.p
prolog_find $usepop/pop/plog/src/plogved.p
prolog_full_deref $popsrc/plogterms.p
prolog_functor $popsrc/plogterms.p
prolog_functor updaterof $popsrc/plogterms.p
prolog_general_save $usepop/pop/plog/src/prolog_ui.p
prolog_generalise $usepop/pop/plog/src/util.p
prolog_get $usepop/pop/plog/src/iopreds.p
prolog_getitem $usepop/pop/plog/src/itemise.p
prolog_handlepopescape $usepop/pop/plog/src/macros.p
prolog_head $usepop/pop/plog/src/util.p
prolog_init_ved $usepop/pop/plog/src/plogved.p
prolog_initbuf $usepop/pop/plog/src/itemise.p
prolog_initcomp $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_instance $usepop/pop/plog/src/util.p
prolog_interpreter $usepop/pop/plog/src/dynamic.p
prolog_invisible $usepop/pop/plog/src/procedures.p
prolog_invoke $usepop/pop/plog/src/prolog_invoke.p
prolog_is_functor $popsrc/plogcore.p
prolog_is_pair $popsrc/plogcore.p
prolog_itemread $usepop/pop/plog/src/itemise.p
prolog_keysort $usepop/pop/plog/src/sortpreds.p
prolog_library $usepop/pop/plog/src/compile.p
prolog_list $usepop/pop/plog/src/write.p
prolog_load $usepop/pop/plog/src/prolog_compile.p
prolog_lvars $popautolib/prolog_lvars.p
prolog_macro $usepop/pop/plog/src/macros.p
prolog_macro_apply $usepop/pop/plog/src/macros.p
prolog_maketerm $popsrc/plogterms.p
prolog_mark $usepop/pop/plog/src/plogved.p
prolog_match_constant $popsrc/plogcore.p
prolog_mishap $usepop/pop/plog/src/prolog_exceptions.p
prolog_module $usepop/pop/plog/src/modules.p
prolog_nargs $usepop/pop/plog/src/obsolete.p
prolog_new_proglist $usepop/pop/plog/src/itemise.p
prolog_newvar $popsrc/plogcore.p
prolog_nextitem $usepop/pop/plog/src/itemise.p
prolog_own_exit_on_success $popsrc/plogcore.p
prolog_own_invoke $popsrc/plogcore.p
prolog_poparg1 $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_portray $usepop/pop/plog/src/iopreds.p
prolog_pr_exception $usepop/pop/plog/src/prolog_exceptions.p
prolog_prbanner $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_predicates_defined $usepop/pop/plog/src/obsolete.p
prolog_predword $usepop/pop/plog/src/obsolete.p
prolog_print $usepop/pop/plog/src/write.p
prolog_printq $usepop/pop/plog/src/write.p
prolog_push_continuation $popsrc/plogcore.p
prolog_push_continuation_term $popsrc/plogterms.p
prolog_push_continuations $popsrc/plogcore.p
prolog_query $usepop/pop/plog/src/prolog_compile.p
prolog_raw_clause $usepop/pop/plog/src/dbpreds.p
prolog_raw_valof $usepop/pop/plog/src/prolog_valof.p
prolog_raw_valof updaterof $usepop/pop/plog/src/prolog_valof.p
prolog_read $usepop/pop/plog/src/iopreds.p
prolog_read_command $usepop/pop/plog/src/commands.p
prolog_readline $usepop/pop/plog/src/io.p
prolog_readstring $usepop/pop/plog/src/itemise.p
prolog_readterm $usepop/pop/plog/src/parse.p
prolog_readterm_to $usepop/pop/plog/src/parse.p
prolog_reinitialise $usepop/pop/plog/src/systempreds.p
prolog_remove $usepop/pop/plog/src/dbpreds.p
prolog_rename $usepop/pop/plog/src/io.p
prolog_reset $popsrc/plog_area.p
prolog_restart $usepop/pop/plog/src/systempreds.p
prolog_safeinvoke $usepop/pop/plog/src/prolog_invoke.p
prolog_safereadline $usepop/pop/plog/src/obsolete.p
prolog_save_image $usepop/pop/plog/src/systempreds.p
prolog_set_contn_trap $popsrc/plogcore.p
prolog_setprolog $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_setq $usepop/pop/plog/src/prolog_eval.p
prolog_setup $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_skip $usepop/pop/plog/src/iopreds.p
prolog_sort $usepop/pop/plog/src/sortpreds.p
prolog_spy_ports_save $usepop/pop/plog/src/prolog_ui.p
prolog_standard_repeater $usepop/pop/plog/src/itemise.p
prolog_stream $usepop/pop/plog/src/io.p
prolog_stream updaterof $usepop/pop/plog/src/io.p
prolog_switch_itemiser $usepop/pop/plog/src/itemise.p
prolog_switch_itemiser updaterof $usepop/pop/plog/src/itemise.p
prolog_syntax_accept $usepop/pop/plog/src/prolog_ui.p
prolog_syntax_style $usepop/pop/plog/src/prolog_ui.p
prolog_syntax_style updaterof $usepop/pop/plog/src/prolog_ui.p
prolog_syscompile $usepop/pop/plog/src/prolog_compile.p
prolog_sysinterrupt $usepop/pop/plog/src/prolog_compile.p
prolog_sysinvoke $usepop/pop/plog/src/prolog_invoke.p
prolog_system_procedure $usepop/pop/plog/src/systempreds.p
prolog_termspec $popsrc/plogterms.p
prolog_toplevel_compile $usepop/pop/plog/src/prolog_compile.p
prolog_try_nextitem $usepop/pop/plog/src/itemise.p
prolog_trycompile $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_type $popsrc/plogcore.p
prolog_undefined $usepop/pop/plog/src/obsolete.p
prolog_undefvar $popsrc/plogcore.p
prolog_unify $popsrc/plogcore.p
prolog_unify_patt $popsrc/plogterms.p
prolog_unifyc $popsrc/plogcore.p
prolog_unknown_accept $usepop/pop/plog/src/prolog_ui.p
prolog_unknown_action $usepop/pop/plog/src/prolog_ui.p
prolog_unknown_action updaterof $usepop/pop/plog/src/prolog_ui.p
prolog_val $usepop/pop/plog/src/prolog_eval.p
prolog_valof $usepop/pop/plog/src/prolog_valof.p
prolog_valof updaterof $usepop/pop/plog/src/prolog_valof.p
prolog_var_number $popsrc/plogcore.p
prolog_vars $popautolib/prolog_vars.p
prolog_vedreadterm $usepop/pop/plog/src/plogved.p
prolog_vedsetup $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_version $usepop/pop/plog/src/prolog_subsystem_procedures.p
prolog_write $usepop/pop/plog/src/write.p
prolog_writeq $usepop/pop/plog/src/write.p
prolog_xsetup $usepop/pop/plog/src/prolog_subsystem_procedures.p
prologterm_apply $popsrc/plogterms.p
prologterm_dest_valof $popsrc/plogterms.p
prompt $usepop/pop/plog/src/iopreds.p
prompt_load $usepop/pop/plog/src/prolog_ui.p
prop_arg_list $usepop/pop/packages/neural/src/pop/nn_utils.p
prop_list $usepop/pop/packages/neural/src/pop/nn_utils.p
propagate $usepop/pop/pml/src/types.p
property_active $popsrc/property_active.p
property_active updaterof $popsrc/property_active.p
property_default $popsrc/property_misc.p
property_domain $usepop/pop/lib/objectclass/src/utils.p
property_equal $popsrc/property_equal.p
property_range $usepop/pop/lib/objectclass/src/utils.p
property_size $popsrc/property_misc.p
propit $popautolib/in_property.p
propsheet_activate $usepop/pop/x/pop/lib/propsheet.p
propsheet_apply $usepop/pop/x/pop/lib/propsheet.p
propsheet_box_buttons $usepop/pop/x/pop/lib/propsheet.p
propsheet_box_buttons updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_box_callback $usepop/pop/x/pop/lib/propsheet.p
propsheet_box_can_resize $usepop/pop/x/pop/lib/propsheet.p
propsheet_box_can_resize updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_destroy $usepop/pop/x/pop/lib/propsheet.p
propsheet_field $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_accepter $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_applier $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_columns updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_converter $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_default $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_default updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_formatter $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_ident $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_ident updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_name $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_number $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_record $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_value $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_value updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_field_width updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_handle_standard_button $usepop/pop/x/pop/lib/propsheet.p
propsheet_hide $usepop/pop/x/pop/lib/propsheet.p
propsheet_id $usepop/pop/x/pop/lib/propsheet.p
propsheet_ident_class $usepop/pop/x/pop/lib/propsheet.p
propsheet_ident_class updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_idents $usepop/pop/lisp/src/util.p
propsheet_import_box $usepop/pop/x/pop/lib/propsheet.p
propsheet_init $usepop/pop/x/pop/lib/propsheet.p
propsheet_label $usepop/pop/x/pop/lib/propsheet.p
propsheet_label updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_length $usepop/pop/x/pop/lib/propsheet.p
propsheet_new $usepop/pop/x/pop/lib/propsheet.p
propsheet_new_box $usepop/pop/x/pop/lib/propsheet.p
propsheet_refresh $usepop/pop/x/pop/lib/propsheet.p
propsheet_reset $usepop/pop/x/pop/lib/propsheet.p
propsheet_reset_size $usepop/pop/x/pop/lib/propsheet.p
propsheet_save $usepop/pop/x/pop/lib/propsheet.p
propsheet_sensitive $usepop/pop/x/pop/lib/propsheet.p
propsheet_sensitive updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_set_defaults $usepop/pop/x/pop/lib/propsheet.p
propsheet_set_focus_on $usepop/pop/x/pop/lib/propsheet.p
propsheet_show $usepop/pop/x/pop/lib/propsheet.p
propsheet_subpart $usepop/pop/x/pop/lib/propsheet.p
propsheet_user_data $usepop/pop/x/pop/lib/propsheet.p
propsheet_user_data updaterof $usepop/pop/x/pop/lib/propsheet.p
propsheet_visible $usepop/pop/x/pop/lib/propsheet.p
propsheet_visible updaterof $usepop/pop/x/pop/lib/propsheet.p
proptool_create $usepop/pop/x/ui/lib/pop_ui_propertytool.p
proptool_is_created $usepop/pop/x/ui/lib/pop_ui_propertytool.p
proptool_names $usepop/pop/x/ui/lib/pop_ui_propertytool.p
proptool_needs_saving $usepop/pop/x/ui/lib/pop_ui_propertytool.p
proptool_save_pr $usepop/pop/x/ui/lib/pop_ui_propertytool.p
proptool_save_to_file $usepop/pop/x/ui/lib/pop_ui_propertytool.p
protected $usepop/pop/lib/objectclass/src/utils.p
proto_number $popliblib/unix_sockets.p
provide $usepop/pop/lisp/src/modules.p
prpart $usepop/pop/packages/vedutils/auto/ved_keymap.p
prqueue $popliblib/newqueue.p
prrpar $usepop/pop/pml/src/print_data.p
prs $usepop/pop/pml/src/print_data.p
prseq $usepop/pop/packages/neural/src/pop/nui_utils.p
prsnake $usepop/pop/packages/popvision/lib/snakes.p
prstring $popliblib/popprint.p
prtable $usepop/pop/packages/vedutils/auto/ved_keymap.p
prtablefor $usepop/pop/packages/teaching/lib/logic.p
prune $usepop/pop/packages/teaching/lib/psys.p
prune $usepop/pop/packages/teaching/lib/solver.p
prune $usepop/pop/packages/teaching/lib/waltz.p
prune_branches $usepop/pop/lib/objectclass/src/instantiate.p
prune_dirs $usepop/pop/packages/vedutils/auto/ved_browse.p
prune_leader $usepop/pop/packages/vedmail/auto/ved_Reply.p
prune_leader $usepop/pop/packages/vedmail/auto/ved_reply.p
prune_window $usepop/pop/packages/neural/src/pop/nn_gfxutils.p
prunesitename $usepop/pop/packages/vedmail/auto/ved_Reply.p
prunesitename $usepop/pop/packages/vedmail/auto/ved_reply.p
prwarning $popliblib/prwarning.p
przfloatvec $usepop/pop/packages/popvision/lib/newzfloatarray.p
pshow $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
pstart $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
pstart $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
pstart $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
pstart $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
psys_DEL $usepop/pop/packages/teaching/lib/newpsys.p
psys_MODIFY $usepop/pop/packages/teaching/lib/newpsys.p
psys_action_type $usepop/pop/packages/teaching/lib/newpsys.p
psys_add $usepop/pop/packages/teaching/lib/newpsys.p
psys_allpresent $usepop/pop/packages/teaching/lib/newpsys.p
psys_applicable $usepop/pop/packages/teaching/lib/newpsys.p
psys_assoc $usepop/pop/packages/teaching/lib/newpsys.p
psys_assoc_memb $usepop/pop/packages/teaching/lib/newpsys.p
psys_check_condition $usepop/pop/packages/teaching/lib/newpsys.p
psys_delete_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_displayrule $usepop/pop/packages/teaching/lib/newpsys.p
psys_divides_chatty $usepop/pop/packages/teaching/lib/newpsys.p
psys_dl $usepop/pop/packages/teaching/lib/newpsys.p
psys_do_action $usepop/pop/packages/teaching/lib/newpsys.p
psys_do_actions $usepop/pop/packages/teaching/lib/newpsys.p
psys_do_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_do_rules $usepop/pop/packages/teaching/lib/newpsys.p
psys_eval $usepop/pop/packages/teaching/lib/newpsys.p
psys_eval_list $usepop/pop/packages/teaching/lib/newpsys.p
psys_expound $usepop/pop/packages/teaching/lib/newpsys.p
psys_finish $usepop/pop/packages/teaching/lib/newpsys.p
psys_flush $usepop/pop/packages/teaching/lib/newpsys.p
psys_foreach $usepop/pop/packages/teaching/lib/newpsys.p
psys_forevery $usepop/pop/packages/teaching/lib/newpsys.p
psys_has_variables $usepop/pop/packages/teaching/lib/newpsys.p
psys_implies $usepop/pop/packages/teaching/lib/newpsys.p
psys_instance $usepop/pop/packages/teaching/lib/newpsys.p
psys_interact $usepop/pop/packages/teaching/lib/newpsys.p
psys_istraced $usepop/pop/packages/teaching/lib/newpsys.p
psys_make_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_new_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_pr_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_present $usepop/pop/packages/teaching/lib/newpsys.p
psys_print_menu $usepop/pop/packages/teaching/lib/newpsys.p
psys_push_or_pop $usepop/pop/packages/teaching/lib/newpsys.p
psys_read_and_add $usepop/pop/packages/teaching/lib/newpsys.p
psys_readaction $usepop/pop/packages/teaching/lib/newpsys.p
psys_readcondition $usepop/pop/packages/teaching/lib/newpsys.p
psys_replace $usepop/pop/packages/teaching/lib/newpsys.p
psys_rule_named $usepop/pop/packages/teaching/lib/newpsys.p
psys_run $usepop/pop/packages/teaching/lib/newpsys.p
psys_save_or_restore $usepop/pop/packages/teaching/lib/newpsys.p
psys_show_rules $usepop/pop/packages/teaching/lib/newpsys.p
psys_trace $usepop/pop/packages/teaching/lib/newpsys.p
psys_trace_rule $usepop/pop/packages/teaching/lib/newpsys.p
psys_truncate $usepop/pop/packages/teaching/lib/newpsys.p
psys_untrace $usepop/pop/packages/teaching/lib/newpsys.p
psys_value $usepop/pop/packages/teaching/lib/newpsys.p
psys_walk_trace $usepop/pop/packages/teaching/lib/newpsys.p
ptalong $popliblib/geometry.p
ptcons1 $usepop/pop/packages/rclib/lib/rc_constrained_mover.p
ptcons_dragpic $usepop/pop/packages/rclib/lib/rc_constrained_mover.p
ptinside $usepop/pop/lib/turtle/findregions.p
ptyfork $popliblib/ptyfork.p
push_arg $usepop/pop/lib/objectclass/src/plant_utils.p
push_module $usepop/pop/plog/src/modules.p
push_view $popliblib/current_view.p
pushnew $usepop/pop/lisp/src/util.p
pushproc_c $usepop/pop/packages/popvision/lib/arrpack.p
pushproc_o $usepop/pop/packages/popvision/lib/arrpack.p
put_chatty_message $usepop/pop/packages/teaching/auto/ved_vcalc.p
put_data_at_exec $popliblib/odbc.p
put_drawing_message $popvedlib/ved_draw.p
put_proc $usepop/pop/packages/teaching/lib/blocks/utils.p
putf $usepop/pop/lisp/src/symbols.p
putfirst $usepop/pop/lib/turtle/lamlabel.p
putin $usepop/pop/packages/teaching/lib/river.p
putnum $usepop/pop/packages/neural/lib/netfileutil.p
putontable $usepop/pop/lib/obsolete/hand.p
pved $popvedlib/pved.p
pwd $popautolib/pwd.p
pwd_cmd $usepop/pop/plog/src/commands.p
pwd_cmd $usepop/pop/pml/src/commands.p
pwm_activs_event_handler $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
pwm_bias_event_handler $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
pwm_extent_event_handler $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
pwm_topology_event_handler $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
pwm_weights_event_handler $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
pwmneural_shutdown $usepop/pop/packages/neural/src/pop/nui_main.p
pwmneural_startup $usepop/pop/packages/neural/src/pop/nui_main.p
