#!/bin/sh
# --- Copyright University of Sussex 1990.  All rights reserved. ---------
# File:            C.unix/com/mkcifer
# Purpose:         make a saved image for VED with LIB CIFER
# Author:          Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:   HELP * CIFER
# Related Files:   VMS version


$popsys/pop11 %nort %noinit << \\\\

lib cifer
false -> popgctrace;

if syssave('$poplocalbin/cifer.psv') then
	syssetup();
	ved_cifer();                    ;;; program the VDU
	unless poparglist == [] then
		popval([ved ^^poparglist])
	endunless;
	setpop();
endif;
sysexit();

\\

rm -f $poplocalbin/cifer.psv-
echo "cifer.psv made"

# --- Revision History ---------------------------------------------------
# --- John Gibson, May 24 1991		Added %nort arg
# --- John Williams, Oct  9 1990	%noinit instead of =noinit
# --- John Williams, Oct  4 1990 	now uses =noinit and -syssetup-
