#!/bin/sh
# --- Copyright University of Sussex 1990.  All rights reserved. ---------
# File:            C.unix/com/mkflavours
# Purpose:         Make a saved image for the flavours system
# Author:          Mark Rubinstein, Apr 17 1986 (see revisions)
# Documentation:   TEACH * FLAVOURS
# Related Files:   LIB * FLAVOURS


$popsys/pop11 %nort %noinit << \\\\

lib flavours

;;; comment out the next two lines if you don't want the browser saved.
lib browseself_message
false -> vedsetupdone;

"flavours" -> vedteachname;

if sys_lock_system('$poplocalbin/flavours.psv', true, 'FLAVOURS') then
	popheader <> '\n\t' <> pop_system_version -> popheader;
	syssetup();
	setpop();
endif;

sysexit();

\\

rm -f $poplocalbin/flavours.psv-
echo "flavours.psv done"


# --- Revision History ---------------------------------------------------
# --- John Gibson, May 24 1991		Added %nort arg
# --- John Williams, Oct  9 1990
#		%noinit instead of =noinit
# --- John Williams, Oct  4 1990
#		Now uses =noinit and -syssetup-
# --- John Gibson, Jun 21 1989
#		Made 2nd arg to sys_lock_system true instead of false
# --- Mark Rubinstein, May 16 1986
#		Assigned false -> vedsetupdone after loading the browser,
#			because LIB SHOWTREE calls vedsetup.
