#!/bin/sh
##
## $local/com/LINK_LIKE_BHAM
## http://www.cs.bham.ac.uk/research/poplog/com/LINK_LIKE_BHAM
## Included in $usepop/INSTALL/LINK_LIKE_BHAM
## Aaron Sloman
## 17 Jan 2005

## Restore bham script for making saved images
cp -p $usepop/pop/com/mkstartup.bham $usepop/pop/com/mkstartup

echo "Bham version of \$usepop/pop/com/mkstartup set up"
