#!/bin/sh
##
## $local/com/LINK_NOMOTIF_POPLOG
## http://www.cs.bham.ac.uk/research/poplog/com/LINK_NOMOTIF_POPLOG
## Included in $usepop/INSTALL/LINK_NOMOTIF_POPLOG
## Relink poplog and then rebuild saved images without motif.
## 17 Jan 2005

## This script links poplog without dependence on motif, using the
##      $popcom/mkstartup
## script (invoked by newpop)


echo ""
echo "======================================================"
echo ""

echo running "./LINK_USING_NEWPOP nomotif"
./LINK_USING_NEWPOP nomotif

echo "done LINK NOMOTIF POPLOG"
echo "==================================================="
echo ""
