#!/bin/sh
##
## $local/com/LINK_BHAM_MOTIF_POPLOG
## http://www.cs.bham.ac.uk/research/poplog/com/LINK_BHAM_MOTIF_POPLOG
## Alos in $usepop/INSTALL/LINK_BHAM_MOTIF_POPLOG
## Relink poplog and then rebuild saved images with motif.
## Use bham version of mkstartup
##
## Aaron Sloman (http://www.cs.bham.ac.uk/~axs/)
##17 Jan 2005

./LINK_LIKE_BHAM

echo "now running ./LINK_MOTIF_POPLOG"

./LINK_MOTIF_POPLOG
