nil -> proglist; ;;; prevent compilation
$poplocal/local/rclib/auto/rclibautoindex.p
Files in $poplocal/local/rclib/auto
ARGS.p                          async_apply.p
async_compile.p                 async_interpret_action.p
async_unix_obey.p               async_vedinput.p
create_action_button.p          create_blob_button.p
create_button_column.p          create_button_row.p
create_modified_instance.p      create_option_button.p
create_radio_button_columns.p   create_select_button.p
create_someof_button_columns.p  define_rc_defaults.p
define_rcdefaults.p             fast_interpolate_coords.p
files_matching.p                forevery.p
happy_face.p                    interpret_specs.p
is_pattern_string.p             isrc_panel_field.p
isrc_window_object.p            loadrcdemo.p
max_string_length.p             menu_choosefile1.p
menu_choosefile2.p              menu_do_scroll.p
menu_vedinput.p                 pattern_instance.p
print_to_strings.p              rc_add_handler.p
rc_add_kill_button.p            rc_app_mouse.p
rc_background.p                 rc_between.p
rc_black_white_inverted.p       rc_blob_demo.p
rc_browse_files.p               rc_browser_action.p
rc_button_in_panelfield.p       rc_change_picture.p
rc_check_current_window.p       rc_check_window_object.p
rc_check_window.p               rc_circle.p
rc_coloured_circles.p           rc_coloured_panel.p
rc_confirm.p                    rc_consolidate_all_input.p
rc_consolidate_input.p          rc_constrained_pointer.p
rc_constrained_rotater.p        rc_control_panel.p
rc_current_handlers.p           rc_defaults.p
rc_default_window_object.p      rc_delete_handler.p
rc_destroy.p                    rc_dial.p
rc_display_file.p               rc_display_strings.p
rc_distance.p                   rc_do_unix.p
rc_drag_window.p                rc_draw_arc_segment.p
rc_draw_arc_segments.p          rc_draw_bar.p
rc_draw_blob.p                  rc_draw_blob_sector.p
rc_draw_centred_rect.p          rc_draw_centred_square.p
rc_draw_circle.p                rc_draw_coloured_circle.p
rc_draw_coloured_line.p         rc_draw_coloured_pointlist.p
rc_draw_coloured_square.p       rc_draw_filled_centred_rect.p
rc_draw_filled_rect.p           rc_draw_filled_triangle.p
rc_drawline_absolute.p          rc_drawline_relative.p
rc_drawlines_interactive.p      rc_draw_lines.p
rc_draw_ob.p                    rc_draw_pointer.p
rc_draw_pointlist.p             rc_draw_rect.p
rc_draw_rotated_rect.p          rc_draw_Rrect.p
rc_draw_Rsquare.p               rc_draw_scaled_blob.p
rc_draw_semi_circle.p           rc_draw_square.p
rc_drawtree.p                   rc_draw_triangle.p
rc_draw_unscaled_blob.p         rc_flush_everything.p
rc_font_dimensions.p            rc_font.p
rc_foreground.p                 rc_get_coords.p
rc_getfile.p                    rc_getinput.p
rc_handle_vedwarpcontext.p      rc_hide_panel.p
rc_insert_strings_scrolltext.p  rc_interpolate_coords.p
rc_interpret_key.p              rc_item_in_panelfield.p
rc_kill_panel.p                 rc_kill_selected_windows.p
rc_label_dial.p                 rc_lengthen_window_by.p
rclibautoindex.p                rc_line_function.p
rc_line_style.p                 rc_line_width.p
rc_lispbrowser.p                rc_make_current_window.p
rc_make_draggable.p             rc_message.p
rc_message_wait.p               rc_mouse_coords.p
rc_new_graphic_widget.p         rc_opaque_slider.p
rc_panelcontents.p              rc_panel_field_value.p
rc_popup_panel.p                rc_popup_query.p
rc_popup_readin.p               rc_popup_readline.p
rc_popup_strings.p              rc_poster.p
rc_print_a_string.p             rc_print_strings.p
rc_procbrowser.p                rc_query_mouse.p
rc_readline.p                   rc_redraw_this_panel.p
rc_reset_panel.p                rc_rotate_vector.p
rc_run_deferred_events.p        rc_scratch_panel.p
rc_scratch_window.p             rc_screensize.p
rc_set_panel_entity.p           rc_set_planemask.p
rc_set_radio_panelfield.p       rc_set_someof_panelfield.p
rc_setup_linefunction.p         rc_set_window_scale.p
rc_shift_window_frame_by.p      rc_showtree.p
rc_slider.p                     rc_square_slider.p
rc_sync_display.p               rc_testbrowser.p
rc_text_area.p                  rc_title.p
rc_transfer_window_contents.p   rc_transform_lines.p
rc_transform_pictures.p         rc_unset_someof_panelfield.p
rc_val_in_panelfield.p          rc_vedfileselect.p
rc_warp_to.p                    rc_widen_window_by.p
rc_window_coords.p              rc_window_dimensions.p
rc_xterm.p                      sad_face.p
self_caller.p                   SETWINDOW.p
ved_browser.p                   ved_buffer_pathname.p
veddiscin.p                     veddiscout.p
ved_killwin.p                   ved_open_file.p
ved_procbrowser.p               ved_rcdemo.p
ved_read_from_file.p            vedreadlinefrom.p
ved_write_to_file.p
