#!/bin/sh
##
## $local/com/LINK_NOBHAM_POPLOG
## http://www.cs.bham.ac.uk/research/poplog/com/LINK_NOMOTIF_POPLOG
## Included in $usepop/INSTALL/LINK_NOMOTIF_POPLOG
## Relink poplog and then rebuild saved images without motif.
## 17 Jan 2005

## This script links poplog without dependence on X11, using the
##      $popcom/mkstartup
## script (invoked by newpop)
## Use the non-bham version.

echo ""
echo "======================================================"
echo ""

echo running "./LINK_USING_NEWPOP nox"
./LINK_USING_NEWPOP nox

echo "done LINK POPLOG WITHOUT X WINDOW FACILITIES"
echo "==================================================="
echo ""
