#!/bin/sh
##
## $local/com/LINK_ORIGINAL_NOMOTIF_POPLOG
## http://www.cs.bham.ac.uk/research/poplog/com/LINK_ORIGINAL_NOMOTIF_POPLOG
## Included in $usepop/INSTALL/LINK_ORIGINAL_NOMOTIF_POPLOG
## Relink poplog and then rebuild saved images, without motif.
## Use previous (non-bham) version of mkstartup
##
## Aaron Sloman (http://www.cs.bham.ac.uk/~axs/)
## 17 Jan 2005

./LINK_LIKE_CORE

echo "now running ./LINK_NOMOTIF_POPLOG"

./LINK_NOMOTIF_POPLOG
