#!/bin/bash
IM=$1
 if [ ! ${IM} ]; then IM=newpop11 ; fi
if [ ! ${POP__cc} ]; then POP__cc=cc; fi
$POP__cc -Wl,-x,-export-dynamic -o $IM \
poplink_1.o \
poplink_2.o \
poplink_3.o \
$popobjlib/vedsrc.olb \
$popobjlib/src.olb \
poplink_4.o \
poplink_dat.o \
-L$popexternlib/ \
-lpop \
-ldl \
-lm -lc
ST=$status
if [[ $ST == 0 ]]; then rm -f $IM.stb ; fi
exit $ST
