#!/bin/bash
## 4 Feb 2008
## A.Sloman
# Use this to run system commands pgcomp, pglibr, etc. with
# setarch in cases where they would otherwise produce segmentation
# fault
# e.g. popsetarch pglibr -r ../obj/src.wlp *.w

setarch i386 -R $*

# --- Revision History ---------------------------------------------------
