#!/bin/sh
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:             C.unix/src/mknewpop
# Purpose:          Make the NEWPOP saved image
# Author:           Robert John Duncan, Sep 20 1991 (see revisions)
# Related Files:    C.vms/src/mknewpop.com, LIB * NEWPOP

IMAGE=$popsys/newpop.psv
corepop11 %nort $popliblib/mkimage.p -entrymain $IMAGE $popliblib/newpop.p
rm -f $IMAGE-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Jul 10 1993
#		Now builds image in popsys on corepop11
# --- John Gibson, Jan 19 1993
#		Added -entrymain arg
# --- Robert John Duncan, Jan 10 1992
#		Changed always to use safepop11
