#!/bin/sh
# --- Copyright University of Sussex 1995.  All rights reserved. ---------
# File:            C.unix/com/makeimages
# Purpose:         Build standard Poplog saved images
# Author:          Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:
# Related Files:   $poplocal/local/com/makeimages

cd $popcom

for f in mkplog mkclisp mkpml
do
	if [ -f $f ]
	then
		echo "Running $f"
		./$f
	fi
done

echo "$popcom/makeimages done"


# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, Aug 10 1995 - changed to do just the languages
# --- John Williams, Aug  6 1990 - now checks existence of scripts
# --- John Williams, Aug 30 1989 - put explicit './' in commands
# --- Rob Duncan, Aug 22 1989 - added mkpml
# --- Simon Nichols, Jun  1 1987 added mkpwmtool
# --- Aaron Sloman, Aug 15 1986 fixed environment - put in echo commands
# --- John Williams, Aug  4 1986 removed reference to LIB LISP
