#!/bin/sh
# --- Copyright University of Sussex 1990.  All rights reserved. ---------
# File:            C.unix/com/mkeliza
# Purpose:         Build saved image for eliza
# Author:          Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:   TEACH * ELIZA
# Related Files:   C.vms/com/mkeliza.com


$popsys/pop11 %nort %noinit << \\\\

lib elizaprog
uses eliza_speak
false -> popgctrace;

if syssave('$popsavelib/eliza.psv') then
	eliza();
	sysexit();
endif;
sysexit();

\\

rm -f $popsavelib/eliza.psv*-
echo "eliza made"


# --- Revision History ---------------------------------------------------
# --- John Gibson, May 24 1991		Added %nort arg
# --- John Williams, Oct  9 1990    %noinit instead of =noinit
# --- John Williams, Oct  4 1990 	now uses =noinit
