#!/bin/sh
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:             C.unix/com/mkploglisp
# Purpose:          Build a Prolog+Lisp saved image
# Author:           John Williams, Jul 18 1990 (see revisions)
# Documentation:    HELP * MKPLOGLISP
# Related Files:    C.vms/com/mkploglisp.com, C.unix/com/mklisplog

$popsys/pop11 +$popsavelib/prolog %nort \
	mkimage -subsystem top $popsavelib/ploglisp lispinplog

rm -f $popsavelib/ploglisp.psv-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Jan 19 1993 		Added -subsystem arg
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
# --- Simon Nichols, Oct 12 1990 - rewritten to use save/2
# --- John Williams, Oct  9 1990 - %noinit instead of =noinit
# --- John Williams, Oct  4 1990 - now uses -syssetup-
# --- Simon Nichols, Sep 10 1990 - changed "noinit" to "=noinit"
