#!/bin/sh
# --- Copyright University of Sussex 1996.  All rights reserved. ---------
# File:             C.unix/com/mkplog
# Purpose:          make a prolog saved image using $popsys/pop11
# Author:           Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:    HELP * PROLOG
# Related Files:    C.vms/com/mkplog.com

$popsys/pop11 %nort %noinit \
	$popliblib/mkimage.p \
	-nodebug -install -flags prolog \( "$@" \) \
	$popsavelib/prolog.psv \
	$usepop/pop/plog/src/prolog.p

rm -f $popsavelib/prolog.psv-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Mar  6 1996  Added -nodebug
# --- John Gibson, Aug 22 1995  Added %noinit
# --- Robert John Duncan, May 29 1991 - added -install
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
# --- Simon Nichols, Jul 17 1990 - revised for new LIB SUBSYSTEM
# --- Rob Duncan, Mar 16 1990 - removed assignments to POPLIB etc.
# --- Rob Duncan, Aug 22 1989 moved most work into "prolog.p"
# --- Rob Duncan, Feb  9 1988 tidied up to fit better with the new version
#     of prolog.p; added the SIZE output at the end
# --- Aaron Sloman, Aug 15 1986 fixed environment
