#!/bin/sh
# --- Copyright University of Sussex 1995. All rights reserved. ----------
# File:             C.unix/com/mkstartup
# Purpose:          Build the Poplog Startup saved image
# Author:           Robert John Duncan, May 21 1991 (see revisions)
# Documentation:
# Related Files:    C.vms/com/mkstartup.com, LIB * STARTUP

$popsys/basepop11 %nort %noinit \
	$popliblib/mkimage.p \
	-nodebug -nonwriteable -install $popsavelib/startup.psv \
	startup

rm -f $popsavelib/startup.psv-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Aug 22 1995  Added %noinit
# --- John Gibson, Apr 21 1993	Added -nodebug
# --- John Gibson, Aug  8 1992	Put -nonwriteable back
# --- Robert John Duncan, Jul  7 1992 - took out -nonwriteable again until
#			we can be sure it's safe
# --- John Gibson, Mar 21 1992 Added -nonwriteable
# --- Robert John Duncan, Oct 24 1991 - changed to use basepop11
# --- Robert John Duncan, Aug 28 1991 - added lib startup
# --- Robert John Duncan, May 29 1991 - added -install
# --- John Gibson, May 24 1991		Added %nort arg
