#!/bin/sh
# --- Copyright University of Sussex 1991. All rights reserved. ----------
### --- Copyright University of Birmingham 2005.
### $usepop/pop/com/mkxvedpro
# Purpose:          Make an XVed saved image with prolog included
# Author:           Aaron Sloman 17 Jan 2005
# Related Files:    $popcom/mkxved $popcom/mkplog

$popsys/pop11 %nort %noinit \
	$popliblib/mkimage.p \
	-nodebug -nonwriteable -install -flags prolog  \( "$@" \) \
	-entry xved_standalone_setup \
			$popsavelib/xvedpro.psv \
			mkxved \
			$usepop/pop/plog/src/prolog.p \
	 		$usepop/pop/packages/vedutils/lib/fixvedploghelp.p

rm -f $popsavelib/xvedpro.psv-


## ved_help replaced by ved_ploghelp
