#!/bin/sh
### --- Copyright University of Birmingham 2005.
### $poplocal/local/com/mkxvedlisp
# Purpose:          Make an XVed saved image with lisp included
# Author:           Aaron Sloman 17 Jan 2005
#                   Requested by Matthias Scheutz
# Related Files:    mkxvedpro, mkclisp

$popsys/pop11 %nort %noinit \
    $popliblib/mkimage.p \
    -nodebug -install -subsystem lisp  \
    -entry xved_standalone_setup \
        $popsavelib/xvedlisp.psv \
                            mkxved \
            $usepop/pop/lisp/src/clisp.p

rm -f $popsavelib/xvedlisp.psv-

#   -nodebug -nonwriteable -install -subsystem lisp  \( "$@" \) \
