#!/bin/sh
# --- Copyright University of Sussex 1991. All rights reserved. ----------
# File:             C.unix/com/pop_system_v
# Purpose:          Test for System V UNIX
# Author:           Simon Nichols, Jun  5 1990 (see revisions)
# Related Files:    C.unix/com/pop_os C.unix/com/pop_processor

exit `basepop11 ':loadlib("sysdefs"); npr(if DEF SYSTEM_V then 0 else 1 endif)'`

# --- Revision History ---------------------------------------------------
# --- Simon Nichols, Sep 23 1991
#		Changed to use basepop11 (and thus no need to unset pop_pop11).
# --- Simon Nichols, Aug  8 1991
#		Changed the way pop_pop11 is unset (the unset command is not
#		available in all shells).
# --- John Gibson, Aug  3 1991
#		Unsets pop_pop11
# --- Simon Nichols, Oct  5 1990
#       Renamed pop_system_v and moved to $popcom.
