
all: config make

# TODO config will be made by configure in the root directory
config: config.sample
	ln -s config.sample config

# TODO make will be made by parsing config
make: make.sample
	ln -s make.sample make

