tab_mode $usepop/pop/ved/src/vdkeys.p
tabify $popautolib/tabify.p
tabifyline $popautolib/tabify.p
table_action $popliblib/reformat.p
tabs $popautolib/tabs.p
tabs_to_spaces $usepop/pop/packages/vedmail/auto/ved_send.p
tabs_to_spaces $usepop/pop/packages/vedmail/auto/ved_sendmr.p
take $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
take $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
take $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
take $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
takeout $usepop/pop/packages/teaching/lib/river.p
tallpr $usepop/pop/packages/neural/src/pop/nui_utils.p
tan $popsrc/trigc.p
tanh $popsrc/trigh.p
target $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
target $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
target $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
target $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tc1 $usepop/pop/ved/src/vdtermcap.p
tc2 $usepop/pop/ved/src/vdtermcap.p
tc3 $usepop/pop/ved/src/vdtermcap.p
tdraw $usepop/pop/lib/turtle/tdraw.p
teach $popautolib/teach.p
teach $usepop/pop/packages/rcmenu/menus/menu_teach.p
teach_all $usepop/pop/packages/neural/src/pop/nui_main.p
teach_select $usepop/pop/packages/neural/src/pop/nui_main.p
teecompat $usepop/pop/lib/turtle/lamlabel.p
telephone_book $usepop/pop/lib/objectclass/lib/objectclass_example.p
telephone_number $usepop/pop/lib/objectclass/lib/objectclass_example.p
telephone_number updaterof $usepop/pop/lib/objectclass/lib/objectclass_example.p
tell $usepop/pop/plog/src/io.p
template_filetype $usepop/pop/packages/neural/src/pop/nn_examplesets.p
termcap_compile $popsrc/termcap.p
termcap_getentry $popsrc/termcap.p
termcap_getflag $popsrc/termcap.p
termcap_getnum $popsrc/termcap.p
termcap_getstring $popsrc/termcap.p
termcap_name $popsrc/termcap.p
termcap_name updaterof $popsrc/termcap.p
terminpdr $usepop/pop/lisp/src/tmacs.p
test $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
test $usepop/pop/packages/popvision/lib/apppolygon.p
test $usepop/pop/packages/teaching/lib/gramdemo.p
test1 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test1 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test1 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test2 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test2 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test2 $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test_acceptor $usepop/pop/packages/rclib/auto/rc_display_file.p
test_acceptor $usepop/pop/packages/rclib/auto/rc_display_strings.p
test_all $usepop/pop/packages/neural/src/pop/nui_main.p
test_arg $usepop/pop/packages/vedutils/auto/ved_tli.p
test_blob $usepop/pop/packages/rclib/auto/rc_draw_blob.p
test_blob $usepop/pop/packages/rclib/auto/rc_draw_scaled_blob.p
test_cat $usepop/pop/packages/teaching/lib/facets.p
test_compile $usepop/pop/packages/teaching/auto/ved_vcalc.p
test_fac $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test_interactive $usepop/pop/packages/neural/src/pop/nui_main.p
test_length $usepop/pop/packages/rclib/auto/rc_draw_blob.p
test_length $usepop/pop/packages/rclib/auto/rc_draw_scaled_blob.p
test_move $usepop/pop/packages/rclib/auto/rc_coloured_circles.p
test_move $usepop/pop/packages/rclib/auto/rc_draw_blob.p
test_moves $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
test_name $usepop/pop/packages/teaching/teach/induce_rules.p
test_popen $popautolib/sys_popen.p
test_pp $usepop/pop/packages/newkit/prb/test/testpoprulebase.p
test_select $usepop/pop/packages/neural/src/pop/nui_main.p
test_unify $usepop/pop/pml/src/types.p
test_values $usepop/pop/packages/teaching/teach/induce_rules.p
test_word $usepop/pop/packages/teaching/lib/facets.p
testall $usepop/pop/packages/teaching/auto/ttt.p
testbit $popsrc/testbit.p
testbit updaterof $popsrc/testbit.p
testdef $popsrc/pop11_syntax.p
testeq $usepop/pop/packages/teaching/lib/logic.p
testflag $popautolib/popdefineprocedure.p
testflag updaterof $popautolib/popdefineprocedure.p
testfn $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
testglobal1 $usepop/pop/packages/newkit/prb/test/syntaxtests.p
testglobal2 $usepop/pop/packages/newkit/prb/test/syntaxtests.p
testit $usepop/pop/packages/rclib/auto/print_to_strings.p
testitem $usepop/pop/pml/src/parse.p
testline $usepop/pop/packages/teaching/auto/ttt.p
testmember $usepop/pop/packages/teaching/lib/gramdemo.p
testpic $usepop/pop/packages/rclib/lib/rc_linked_pic.p
testpopneural $usepop/pop/packages/neural/demos/testfile.p
testproc $usepop/pop/packages/newkit/sim/auto/veddiscout.p
testproc $usepop/pop/packages/rclib/auto/veddiscout.p
testproc $usepop/pop/packages/vedutils/auto/veddiscout.p
testproc $usepop/pop/x/pop/lib/rc_drawgraph.p
testrs $usepop/pop/packages/newkit/prb/auto/define_rulesystem.p
testrs $usepop/pop/packages/newkit/prb/test/syntaxtests.p
testrules $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
text_accepter $usepop/pop/x/ui/lib/pop_ui_text_input.p
text_box_busy $usepop/pop/x/ui/lib/pop_ui_text_input.p
text_box_busy updaterof $usepop/pop/x/ui/lib/pop_ui_text_input.p
text_field_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
text_input_cb $usepop/pop/x/ui/lib/pop_ui_text_input.p
textfield_string_x $usepop/pop/packages/neural/src/pop/nui_xpanels.p
textfield_string_x updaterof $usepop/pop/packages/neural/src/pop/nui_xpanels.p
textin_field_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
textrightlim $usepop/pop/ved/src/vdscroll.p
the_box $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
the_box $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
the_date $usepop/pop/packages/master/lib/newmaster/utils.p
the_hand $usepop/pop/packages/rclib/lib/rc_hand.p
the_proc $usepop/pop/packages/teaching/lib/blocks/utils.p
the_user $usepop/pop/packages/master/lib/newmaster/utils.p
the_year $usepop/pop/packages/master/lib/newmaster/utils.p
thick2 $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
thing_data $usepop/pop/packages/newkit/prb/lib/prbriver.p
thing_data $usepop/pop/packages/newkit/prb/teach/prbrunriver.p
thing_data $usepop/pop/packages/newkit/prb/test/prbriver.p
thing_data $usepop/pop/packages/newkit/prb/test/prbriver2.p
thing_data $usepop/pop/packages/newkit/prb/test/prbrunriver.p
think $usepop/pop/lib/database/think.p
think $usepop/pop/packages/teaching/lib/elizaprog-2005.p
think $usepop/pop/packages/teaching/lib/elizaprog.p
thislinestart $popliblib/reformat.p
thisname $usepop/pop/packages/vedutils/auto/ved_browse.p
thisname $usepop/pop/packages/vedutils/auto/ved_vman.p
threshold $usepop/pop/lib/turtle/convolve.p
threshold_drop_func $usepop/pop/packages/brait/lib/activation_functions.p
threshold_rise_func $usepop/pop/packages/brait/lib/activation_functions.p
throw $popautolib/catch.p
throw $popsrc/lispcore.p
tidy $usepop/pop/packages/teaching/lib/stroppy.p
tidy_addresses_in_line $usepop/pop/packages/vedmail/auto/ved_tah.p
tidy_addresses_in_line $usepop/pop/packages/vedmail/auto/ved_tmh.p
tilde $usepop/pop/pml/src/lex.p
time $popliblib/time.p
time_rotate $usepop/pop/packages/rclib/teach/rclib_demo.p
timediff $popautolib/timediff.p
times_n $usepop/pop/lisp/src/numbers.p
title $usepop/pop/lib/lr_parser/lib/lr_trace.p
title $usepop/pop/packages/master/auto/newmaster_utils.p
title_to_widget $usepop/pop/x/ui/lib/pop_ui_propertytool.p
tjump $usepop/pop/lib/turtle/tjump.p
tl $popsrc/list_hdtl.p
tl updaterof $popsrc/list_hdtl.p
tlclip $usepop/pop/packages/popvision/lib/rc_array.p
tlookup $usepop/pop/packages/popvision/lib/arraylookup.p
tlookup1a $usepop/pop/packages/popvision/lib/arraylookup.p
tlookup1b $usepop/pop/packages/popvision/lib/arraylookup.p
tlookup1c $usepop/pop/packages/popvision/lib/arraylookup.p
tmac $usepop/pop/lisp/src/itemise.p
tmpclr_cache_prop $popliblib/odbc.p
tmpval_cache_prop $popliblib/odbc.p
to_be $usepop/pop/packages/teaching/lib/elizaprog-2005.p
to_be $usepop/pop/packages/teaching/lib/elizaprog.p
to_bigendian $usepop/pop/packages/popvision/lib/sunrasterfile.p
to_proc $usepop/pop/packages/teaching/lib/blocks/utils.p
to_string $popliblib/showtree.p
tobytevec $usepop/pop/packages/popvision/lib/arraylookup.p
tofloat $usepop/pop/packages/popvision/include/mlp.ph
tofloat $usepop/pop/packages/popvision/lib/float_arrayprocs.p
tofloatvec $usepop/pop/packages/popvision/lib/arraylookup.p
toggle $usepop/pop/pml/src/lexitems.p
toggle updaterof $usepop/pop/pml/src/lexitems.p
toggle_clock $usepop/pop/packages/rcmenu/menus/menu_user.p
toggle_delete $popvedlib/ved_draw.p
toggle_field $usepop/pop/packages/neural/src/pop/nn_dtconverters.p
toggle_field updaterof $usepop/pop/packages/neural/src/pop/nn_dtconverters.p
toggle_to_real $usepop/pop/packages/neural/src/pop/nn_dtconverters.p
token_valof $usepop/pop/lisp/src/tokens.p
tokens_part $usepop/pop/lib/lr_parser/auto/define_parser.p
tool_demos $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
tool_help $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
tool_libraries $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
toolong $usepop/pop/packages/teaching/lib/elizaprog-2005.p
toolong $usepop/pop/packages/teaching/lib/elizaprog.p
top_level_after_hook $usepop/pop/lisp/src/compile.p
top_level_before_hook $usepop/pop/lisp/src/compile.p
top_level_eval $usepop/pop/lisp/src/compile.p
top_level_listen $usepop/pop/lisp/src/compile.p
top_level_loop $usepop/pop/lisp/src/compile.p
top_level_print $usepop/pop/lisp/src/compile.p
top_level_read $usepop/pop/lisp/src/readutils.p
toplevel $usepop/pop/packages/rcmenu/menus/menu_toplevel.p
topological_sort $usepop/pop/lib/objectclass/src/inheritance.p
topology_mouse_at_cb $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_mouse_out $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_move_to $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_press_at $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_quit $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_quit_cb $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_release_at $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_resized $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
topology_resized_cb $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
trace $popsrc/trace.p
trace_add $usepop/pop/pml/src/trace.p
trace_apply $usepop/pop/lib/lr_parser/lib/lr_trace.p
trace_check $usepop/pop/pml/src/trace.p
trace_command $usepop/pop/pml/src/trace.p
trace_every_method $usepop/pop/lib/objectclass/auto/trace_method.p
trace_match $usepop/pop/packages/lib/poprulebase.p
trace_match $usepop/pop/packages/newkit/prb/lib/poprulebase.p
trace_matches $usepop/pop/lib/objectclass/src/preferences.p
trace_me $usepop/pop/lib/objectclass/auto/trace_method.p
trace_message $usepop/pop/pml/src/trace.p
trace_method $usepop/pop/lib/objectclass/auto/trace_method.p
trace_print $usepop/pop/pml/src/trace.p
trailer $usepop/pop/packages/master/lib/newmaster/utils.p
train $usepop/pop/packages/rclib/demo/rc_neural.p
train $usepop/pop/packages/rclib/teach/rc_neural.p
train_all $usepop/pop/packages/rclib/demo/rc_neural.p
train_all $usepop/pop/packages/rclib/teach/rc_neural.p
train_net $usepop/pop/packages/rclib/demo/rc_neural.p
train_net $usepop/pop/packages/rclib/teach/rc_neural.p
trans $popvedlib/vedinkeys.p
transform_body $usepop/pop/plog/src/transform.p
transform_param $popautolib/format_print.p
transform_pic $usepop/pop/packages/rclib/auto/rc_transform_pictures.p
transform_places $usepop/pop/packages/rclib/lib/rc_text_input.p
transformtree $popliblib/showtree.p
translate $usepop/pop/packages/teaching/lib/oldlisp.p
translate_argument $usepop/pop/packages/master/lib/newmaster/history.p
translate_flags $popvedlib/ved_print.p
translate_logical_pathname $usepop/pop/lisp/src/pathnames.p
translate_pathname $usepop/pop/lisp/src/pathnames.p
translations_string $usepop/pop/x/ved/src/xvedresources.p
transpatt $popautolib/sys_file_match.p
transportable $usepop/pop/packages/teaching/lib/river.p
tree1 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
tree1 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree1 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree1 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree1 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
tree1 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree2 $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
tree2 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree2 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree2 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree2 $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
tree2 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree3 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree3 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree3 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree3 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree4 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree4 $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree4 $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree4 $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree_detect $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree_detect $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree_detect $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree_detect $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree_range $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
tree_range $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
tree_range $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
tree_range $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
tree_to_pd $usepop/pop/lib/objectclass/src/tree_to_pd.p
treedetection $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
treedetection $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
treedetection $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
treedetection $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_action_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_action_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_action_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_agent $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_agent $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
trial_agent $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_agent $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_agent $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_coords $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_coords $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_coords $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_coords $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_coords $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_coords $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_dog $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_dog $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_dog $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_dog $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_dog $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_dog $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_dog_rulesystem $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_instinct_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_instinct_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_instinct_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_obstacle $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_obstacle $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_obstacle $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_obstacle $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_obstacle $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_obstacle $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_obstacle_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_obstacle_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_obstacle_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_pen $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_pen $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_perception_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_perception_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_perception_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_post $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_post $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_post $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_post $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_post $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_post $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_sheep $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_sheep $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_sheep $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_sheep $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
trial_sheep $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_sheep $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_sheep $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_sheep_rulesystem $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_social_rules $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_social_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_social_rules $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_target $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_target $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_target $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_target $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
trial_tree $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
trial_tree $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
trial_tree $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
trial_tree $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
trial_tree $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
trial_tree $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
triangle $usepop/pop/packages/teaching/lib/evpics.p
tried $usepop/pop/packages/teaching/lib/psys.p
trim_flags $popvedlib/ved_grep.p
trim_n $usepop/pop/packages/popvision/lib/fft.p
trim_n2_ref $usepop/pop/packages/popvision/lib/fft.p
trip $usepop/pop/packages/rclib/auto/create_modified_instance.p
tripcoords updaterof $usepop/pop/packages/rclib/auto/create_modified_instance.p
trnAgentList $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
true $usepop/pop/plog/src/controlpreds.p
true_in_view $popliblib/current_view.p
true_vars $usepop/pop/packages/newkit/sim/lib/sim_harness.p
truename $usepop/pop/lisp/src/files.p
truncate $usepop/pop/lisp/src/numbers.p
truncate_path $usepop/pop/lib/objectclass/src/method_table.p
truthtable $usepop/pop/packages/teaching/lib/logic.p
try $usepop/pop/packages/teaching/lib/elizaprog-2005.p
try $usepop/pop/packages/teaching/lib/elizaprog.p
try $usepop/pop/packages/teaching/lib/logic.p
try $usepop/pop/packages/teaching/lib/psys.p
try_action $usepop/pop/packages/teaching/lib/finger.p
try_active_data $popvedlib/ved_do_text_action.p
try_file_delete $popliblib/newpop.p
try_file_move $popliblib/newpop.p
try_hide $usepop/pop/packages/rcmenu/auto/define_menu.p
try_instantiate $usepop/pop/packages/teaching/lib/elizaprog-2005.p
try_instantiate $usepop/pop/packages/teaching/lib/elizaprog.p
try_non_decimal $usepop/pop/lisp/src/itemise.p
try_parse_aexp $usepop/pop/pml/src/parse.p
try_parse_apat $usepop/pop/pml/src/parse.p
try_parse_dec $usepop/pop/pml/src/parse.p
try_parse_spec $usepop/pop/pml/src/parse.p
try_set_default $usepop/pop/packages/lib/poprulebase.p
try_set_default $usepop/pop/packages/newkit/prb/lib/poprulebase.p
try_set_default $usepop/pop/packages/rclib/auto/rc_defaults.p
try_static_eval $usepop/pop/pml/src/pregen.p
try_status_line $popvedlib/vedfilecomplete.p
tryadd $usepop/pop/packages/rclib/demo/aze.connect4.p
tryaddall $usepop/pop/packages/rclib/demo/aze.connect4.p
tryaliases $usepop/pop/packages/vedmail/auto/ved_alias.p
tryall $usepop/pop/lib/database/forevery.p
tryanswerquestion $usepop/pop/packages/teaching/lib/elizaprog.p
trycompile $popsrc/pop11_compile.p
trygenrules $usepop/pop/packages/teaching/lib/grammar.p
trylisp_compile $usepop/pop/lisp/src/compile.p
trylockfile $usepop/pop/packages/lockfile/lib/lockfiles.p
trynext $popliblib/super.p
trynext $usepop/pop/lib/database/foreach.p
trynospy $usepop/pop/plog/src/spy.p
trynumber $usepop/pop/packages/rclib/auto/rc_popup_query.p
tryreadmailrc $usepop/pop/packages/vedmail/auto/ved_send.p
tryreadmailrc $usepop/pop/packages/vedmail/auto/ved_sendmr.p
tryreserved $usepop/pop/pml/src/lexitems.p
tryrule $popliblib/tparse.p
tryspy $usepop/pop/plog/src/spy.p
trystep $usepop/pop/packages/teaching/lib/rhino.p
tryunlockfile $usepop/pop/packages/lockfile/lib/lockfiles.p
tryvedterminalselect $usepop/pop/ved/src/vdinitseq.p
trywriteline $usepop/pop/packages/rclib/lib/rc_scrolltext.p
ttt $usepop/pop/packages/teaching/auto/ttt.p
tupled_wrapper $usepop/pop/pml/src/vmml.p
tupletype $usepop/pop/pml/src/types.p
turn $usepop/pop/lib/obsolete/graphic.p
turn $usepop/pop/lib/turtle/lturtle.p
turn $usepop/pop/lib/turtle/turn.p
turnang $usepop/pop/lib/turtle/regions.p
turnto $usepop/pop/lib/turtle/turnto.p
turtle $usepop/pop/lib/obsolete/graphic.p
turtle $usepop/pop/lib/turtle/lturtle.p
turtle $usepop/pop/lib/turtle/turtle.p
turtle $usepop/pop/lib/turtle/vturtle.p
turtle_pr $usepop/pop/lib/turtle/turtle_pr.p
tvi $popvedlib/tvi.p
tvi925 $popvedlib/tvi925.p
tw_substringout $usepop/pop/x/ved/src/xvedscreen.p
txt_pause $usepop/pop/packages/neural/src/pop/nui_utils.p
txtedit_menuloop $usepop/pop/packages/neural/src/pop/nui_txtedit.p
txtneural_shutdown $usepop/pop/packages/neural/src/pop/nui_main.p
txtneural_startup $usepop/pop/packages/neural/src/pop/nui_main.p
tycon_arity $usepop/pop/pml/src/types.p
type $popliblib/popprint.p
type $usepop/pop/packages/teaching/lib/gramdemo.p
type_cerror $usepop/pop/lisp/src/util.p
type_definition $popautolib/fortran_dec.p
type_deref $usepop/pop/pml/src/types.p
type_error $popsrc/lispcore.p
type_error $usepop/pop/lisp/src/util.p
type_expand $usepop/pop/lisp/src/types.p
type_expand $usepop/pop/pml/src/types.p
type_expand1 $usepop/pop/lisp/src/types.p
type_expander $usepop/pop/lisp/src/types.p
type_expander updaterof $usepop/pop/lisp/src/types.p
type_generalise $usepop/pop/pml/src/types.p
type_idname $popliblib/typespec_utils.p
type_instance $usepop/pop/pml/src/types.p
type_mishap $usepop/pop/packages/popvision/lib/excall.p
typecheck $usepop/pop/pml/src/typecheck.p
typecheck_abstypedec $usepop/pop/pml/src/typecheck.p
typecheck_clause $usepop/pop/pml/src/typecheck.p
typecheck_conbinds $usepop/pop/pml/src/typecheck.p
typecheck_databind $usepop/pop/pml/src/typecheck.p
typecheck_datatypedec $usepop/pop/pml/src/typecheck.p
typecheck_datatypespec $usepop/pop/pml/src/typecheck.p
typecheck_dec $usepop/pop/pml/src/typecheck.p
typecheck_exceptiondec $usepop/pop/pml/src/typecheck.p
typecheck_exceptionspec $usepop/pop/pml/src/typecheck.p
typecheck_exnbind $usepop/pop/pml/src/typecheck.p
typecheck_exp $usepop/pop/pml/src/typecheck.p
typecheck_external_exception $usepop/pop/pml/src/typecheck.p
typecheck_external_structure $usepop/pop/pml/src/typecheck.p
typecheck_external_val $usepop/pop/pml/src/typecheck.p
typecheck_fbs $usepop/pop/pml/src/typecheck.p
typecheck_fncbind $usepop/pop/pml/src/typecheck.p
typecheck_functordec $usepop/pop/pml/src/typecheck.p
typecheck_fundec $usepop/pop/pml/src/typecheck.p
typecheck_includespec $usepop/pop/pml/src/typecheck.p
typecheck_localdec $usepop/pop/pml/src/typecheck.p
typecheck_localspec $usepop/pop/pml/src/typecheck.p
typecheck_localstrdec $usepop/pop/pml/src/typecheck.p
typecheck_match $usepop/pop/pml/src/typecheck.p
typecheck_pat $usepop/pop/pml/src/typecheck.p
typecheck_recvalbinds $usepop/pop/pml/src/typecheck.p
typecheck_rule $usepop/pop/pml/src/typecheck.p
typecheck_sharingspec $usepop/pop/pml/src/typecheck.p
typecheck_sigbind $usepop/pop/pml/src/typecheck.p
typecheck_sigexp $usepop/pop/pml/src/typecheck.p
typecheck_signaturedec $usepop/pop/pml/src/typecheck.p
typecheck_spec $usepop/pop/pml/src/typecheck.p
typecheck_strbind $usepop/pop/pml/src/typecheck.p
typecheck_strdec $usepop/pop/pml/src/typecheck.p
typecheck_strdesc $usepop/pop/pml/src/typecheck.p
typecheck_strexp $usepop/pop/pml/src/typecheck.p
typecheck_structuredec $usepop/pop/pml/src/typecheck.p
typecheck_structurespec $usepop/pop/pml/src/typecheck.p
typecheck_topdec $usepop/pop/pml/src/typecheck.p
typecheck_tyexp $usepop/pop/pml/src/typecheck.p
typecheck_typebind $usepop/pop/pml/src/typecheck.p
typecheck_typedec $usepop/pop/pml/src/typecheck.p
typecheck_typespec $usepop/pop/pml/src/typecheck.p
typecheck_valbind $usepop/pop/pml/src/typecheck.p
typecheck_valdec $usepop/pop/pml/src/typecheck.p
typecheck_valspec $usepop/pop/pml/src/typecheck.p
typedef_alias $popautolib/kr_newc_dec.p
typedef_alias $popautolib/newc_dec.p
typedef_alias $usepop/pop/packages/newc_dec/auto/newc_dec.p
typedef_alias updaterof $popautolib/kr_newc_dec.p
typedef_alias updaterof $popautolib/newc_dec.p
typedef_alias updaterof $usepop/pop/packages/newc_dec/auto/newc_dec.p
typedef_ident $popautolib/c_dec.p
typename_deref $usepop/pop/pml/src/types.p
typeof $usepop/pop/packages/teaching/lib/picdem.p
typeof $usepop/pop/pml/src/typecheck.p
typeof updaterof $usepop/pop/pml/src/typecheck.p
typep $usepop/pop/lisp/src/typep.p
typespec_from_name $usepop/pop/packages/popvision/lib/excall.p
typespecread $popautolib/typespecread.p
tyvar_chars $usepop/pop/pml/src/print_types.p
u_interpret $usepop/pop/lib/objectclass/src/interpreter.p
u_invoke_call_next_method $usepop/pop/lib/objectclass/src/globals.p
ui_variable_display $usepop/pop/packages/neural/src/pop/nn_activevars.p
ui_variable_display $usepop/pop/packages/neural/src/pop/nui_panels.p
ui_variable_display updaterof $usepop/pop/packages/neural/src/pop/nn_activevars.p
ui_variable_display updaterof $usepop/pop/packages/neural/src/pop/nui_panels.p
uid_of_mess $popliblib/imap.p
unary_+: $popsrc/complex_ops.p
unary_-: $popsrc/complex_ops.p
unbind_cols $popliblib/odbc.p
unbind_params $popliblib/odbc.p
unbind_tyvar $usepop/pop/pml/src/typecheck.p
unbound_error $usepop/pop/pml/src/env.p
undefined $usepop/pop/plog/src/predicate_valof.p
undefword $popsrc/undef.p
undefword updaterof $popsrc/undef.p
underjoin $popliblib/showtree.p
underline_off $usepop/pop/packages/neural/src/pop/nui_utils.p
underline_on $usepop/pop/packages/neural/src/pop/nui_utils.p
undo $usepop/pop/packages/newkit/prb/test/prbriver.p
undo $usepop/pop/packages/newkit/prb/test/prbriver2.p
undraw $usepop/pop/packages/teaching/lib/analogy.p
undraw_links_from $usepop/pop/packages/neural/src/pop/nn_gfxdraw.p
undraw_links_to $usepop/pop/packages/neural/src/pop/nn_gfxdraw.p
unexport $popsrc/lispcore.p
unforcedmatch $usepop/pop/packages/teaching/lib/analogy.p
unftrace $usepop/pop/packages/teaching/lib/facets.p
unftraceall $usepop/pop/packages/teaching/lib/facets.p
unichar_lextype $popsrc/item.p
unify $usepop/pop/plog/src/obsolete.p
unify_array_spec $popautolib/fortran_dec.p
unify_error $usepop/pop/pml/src/type_errors.p
unify_types $usepop/pop/pml/src/types.p
unifyii $popliblib/super.p
unifyxi $popliblib/super.p
unimportant $popliblib/crossref.p
unindent_this_line $usepop/pop/ved/src/vdtidy.p
unintern $popsrc/lispcore.p
union $popliblib/sets.p
union $usepop/pop/lib/lr_parser/lib/lr_gen.p
union $usepop/pop/packages/teaching/lib/newobj.p
unique $usepop/pop/packages/rclib/lib/rc_blocks.p
unique $usepop/pop/packages/teaching/lib/msblocks.p
unique $usepop/pop/packages/teaching/lib/msdemo.p
unique $usepop/pop/packages/teaching/lib/solver.p
uniquelist $popliblib/showarray.p
unix $usepop/pop/packages/rcmenu/menus/menu_unix.p
unless $popsrc/pop11_syntax.p
unlink_all_isas $usepop/pop/lib/objectclass/src/class_isa.p
unlink_all_methods $usepop/pop/lib/objectclass/src/methods.p
unlink_all_methods_of_supers $usepop/pop/lib/objectclass/src/methods.p
unlink_interpreter $usepop/pop/lib/objectclass/src/interpreter.p
unlink_interpreter $usepop/pop/lib/objectclass/src/interpreter.p
unlink_method $usepop/pop/lib/objectclass/src/methods.p
unlockMethodTable $usepop/pop/lib/objectclass/src/method_table.p
unlockfile $usepop/pop/packages/master/auto/newmaster_utils.p
unlockfile $usepop/pop/packages/master/lib/newmaster/utils.p
unlocklog $usepop/pop/packages/master/auto/newmaster_utils.p
unlocklog $usepop/pop/packages/master/lib/newmaster/utils.p
unlocktmpvec $usepop/pop/lib/objectclass/src/tmpvecs.p
unmap_cb $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xm.p
unpack_manpath $usepop/pop/packages/vedutils/auto/ved_vman.p
unpackitem $popautolib/unpackitem.p
unparse_continuous_files $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_continuous_lists $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_discrete_files $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_discrete_lists $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_discrete_singlefiles $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_egs $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_file $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_file $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_proc $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_proc $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_struct $usepop/pop/packages/neural/src/pop/nn_apply.p
unparse_egs_to_struct $usepop/pop/packages/neural/src/pop/nn_apply.p
unread_char $usepop/pop/lisp/src/read.p
unscalex $popliblib/aed.p
unscaley $popliblib/aed.p
unset_current_picture_object $usepop/pop/packages/rclib/lib/rc_linepic.p
unsure $usepop/pop/packages/teaching/lib/elizaprog-2005.p
unsure $usepop/pop/packages/teaching/lib/elizaprog.p
until $popsrc/pop11_loops.p
untrace $popsrc/trace.p
untrace_every_method $usepop/pop/lib/objectclass/auto/trace_method.p
untrace_method $usepop/pop/lib/objectclass/auto/trace_method.p
untraceall $popautolib/untraceall.p
unuse_package $popsrc/lispcore.p
unwrapped $usepop/pop/plog/src/procedures.p
unwrapped updaterof $usepop/pop/plog/src/procedures.p
up $usepop/pop/lib/obsolete/hand.p
upd_erase $popsrc/pop11_syntax.p
updateMethodTable $usepop/pop/lib/objectclass/src/method_table.p
update_action_label $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xol.p
update_copyright $usepop/pop/packages/master/auto/newmaster_header.p
update_copyright $usepop/pop/packages/master/lib/newmaster/header.p
update_dir_items $usepop/pop/packages/neural/src/pop/nui_xpanels.p
update_equations $usepop/pop/packages/teaching/auto/ved_vcalc.p
update_file_list $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xol.p
update_font_specs $usepop/pop/packages/rclib/lib/rc_text_input.p
update_index $popliblib/make_indexes.p
update_instance $usepop/pop/lisp/src/clos.p
update_label $usepop/pop/x/pop/lib/XawTutorial.p
update_list $usepop/pop/lib/objectclass/auto/trace_method.p
update_list_widget $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
update_method $usepop/pop/lib/objectclass/src/methods.p
update_mkimagetool_window $usepop/pop/x/ui/lib/pop_ui_projecttool.p
update_multisheettool_window $usepop/pop/x/ui/lib/pop_ui_projecttool.p
update_prefstool_window $usepop/pop/x/ui/lib/pop_ui_projecttool.p
update_project_file_sheet $usepop/pop/x/ui/lib/pop_ui_projecttool.p
update_project_subwindows $usepop/pop/x/ui/lib/pop_ui_projecttool.p
update_pwmitem $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
update_scale $usepop/pop/x/pop/lib/XmTutorial.p
update_select_cells $usepop/pop/packages/neural/src/pop/nn_gfxutils.p
update_slider $usepop/pop/x/pop/lib/XolTutorial.p
update_slot $usepop/pop/packages/rclib/auto/create_modified_instance.p
update_thumb $usepop/pop/x/pop/lib/XawTutorial.p
update_var $usepop/pop/x/pop/lib/XawTutorial.p
update_win $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
updater $popsrc/pdr_util.p
updater updaterof $popsrc/pdr_util.p
updater_coerce updaterof $usepop/pop/packages/neural/lib/backprop.p
updater_coerce updaterof $usepop/pop/packages/neural/lib/complearn.p
upgrade_method $usepop/pop/lib/objectclass/src/upgrade_method.p
upgrade_methods $usepop/pop/lib/objectclass/src/upgrade_method.p
upgraded_array_element_type $usepop/pop/lisp/src/specs.p
upgraded_complex_part_type $usepop/pop/lisp/src/specs.p
upnode $usepop/pop/packages/teaching/lib/seetree.p
uppertolower $popsrc/uppertolower.p
uppr $usepop/pop/packages/teaching/lib/solver.p
upto $usepop/pop/packages/vedutils/auto/ved_keymap.p
usage $popliblib/crossref.p
use_basewindow $usepop/pop/packages/neural/src/pop/nui_utils.p
use_fail_lab $usepop/pop/pml/src/gencode.p
use_package $popsrc/lispcore.p
user $usepop/pop/packages/rcmenu/menus/menu_user.p
user_char_mac $usepop/pop/lisp/src/umacs.p
user_homedir_pathname $usepop/pop/lisp/src/pathnames.p
user_rc_interpret_key $usepop/pop/packages/rclib/auto/rc_interpret_key.p
user_value $usepop/pop/pml/src/data.p
uses $popautolib/uses.p
uses_lib_idents $popautolib/uses_lib_idents.p
useslib $popautolib/useslib.p
utilities $usepop/pop/packages/rcmenu/menus/menu_utilities.p
