sa_chars $popliblib/showarray.p
sa_decplaces $popliblib/showarray.p
sa_diffchars $popliblib/showarray.p
sa_evenchars $popliblib/showarray.p
sa_figchars $popliblib/showarray.p
sa_histochars $popliblib/showarray.p
sa_limit $popliblib/showarray.p
sa_logchars $popliblib/showarray.p
sa_print $popliblib/showarray.p
sa_print_zeros $popliblib/showarray.p
sa_prnums $popliblib/showarray.p
sa_prpars $popliblib/showarray.p
sa_resize $popliblib/showarray.p
sa_signchars $popliblib/showarray.p
sa_simple_asis $popliblib/showarray.p
sa_simple_fitscreen $popliblib/showarray.p
sa_simple_nums $popliblib/showarray.p
sa_xaxis_nums $popliblib/showarray.p
sa_yaxis_num $popliblib/showarray.p
sad_face $usepop/pop/packages/rclib/auto/sad_face.p
safe_syslibcompile $usepop/pop/lib/flavours/flavesyntax.p
same_constructors $usepop/pop/pml/src/modules.p
same_side_of_line $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
same_side_of_line $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
same_side_of_line $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
same_side_of_line $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
same_side_of_line $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
same_type_function $usepop/pop/pml/src/modules.p
sameline $usepop/pop/packages/teaching/lib/solver.p
sameplace $usepop/pop/packages/teaching/lib/river.p
sametail $popvedlib/ved_nextcsame.p
sametail $usepop/pop/packages/vedutils/auto/ved_nextcsame.p
sample $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sample $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sap $popliblib/aed.p
save $popautolib/save.p
save $popliblib/super.p
save_dt $usepop/pop/packages/neural/src/pop/nui_main.p
save_egs $usepop/pop/packages/neural/src/pop/nui_main.p
save_egs_flags $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_egs_info $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_env $usepop/pop/pml/src/external.p
save_env updaterof $usepop/pop/pml/src/external.p
save_field_dt $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_file_dt $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_file_info $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_general_dt $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_image $popliblib/mkimage.p
save_local_env $usepop/pop/pml/src/env.p
save_needscompiling $usepop/pop/lib/flavours/flavecore.p
save_net $usepop/pop/packages/neural/src/pop/nui_main.p
save_options $usepop/pop/plog/src/prolog_ui.p
save_position $usepop/pop/x/ved/lib/vedxvedmouse.p
save_proc_info $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_project $usepop/pop/x/ui/lib/S-poplog_uiS-guiProjectUtils.p
save_project_wspace $usepop/pop/x/ui/lib/pop_ui_projecttool.p
save_sheet $usepop/pop/x/ui/lib/pop_ui_propertytool.p
save_struct_info $usepop/pop/packages/neural/src/pop/nn_file_io.p
save_undef_token $usepop/pop/lisp/src/plant.p
saveable_selection $usepop/pop/x/ui/lib/pop_ui_projecttool.p
saved_object_names $usepop/pop/packages/neural/src/pop/nn_file_io.p
savelisp $usepop/pop/lisp/src/saved_images.p
saveproc $popsrc/process.p
say $usepop/pop/packages/neural/src/pop/nui_utils.p
sayitback $usepop/pop/packages/teaching/lib/elizaprog-2005.p
sayitback $usepop/pop/packages/teaching/lib/elizaprog.p
sbc $popliblib/aed.p
scale_arrays $usepop/pop/packages/popvision/lib/horn_schunck.p
scalex $popliblib/aed.p
scaley $popliblib/aed.p
scc $popliblib/aed.p
schar $usepop/pop/lisp/src/strings.p
schar updaterof $usepop/pop/lisp/src/strings.p
scheck $usepop/pop/packages/teaching/lib/schema.p
scheck_select $usepop/pop/packages/teaching/lib/schema.p
schedule $popliblib/actor.p
schoose $usepop/pop/packages/teaching/lib/schema.p
scolon $usepop/pop/lisp/src/tmacs.p
scolon $usepop/pop/pml/src/lex.p
scon_value $usepop/pop/pml/src/lexitems.p
scope $usepop/pop/packages/newkit/prb/test/syntaxtests.p
screen_coords $usepop/pop/x/ved/src/xvedselections.p
screencharmode $usepop/pop/x/ved/src/xvedscreen.p
screencharmode updaterof $usepop/pop/x/ved/src/xvedscreen.p
screencooked $usepop/pop/x/ved/src/xvedscreen.p
screencursoron $usepop/pop/x/ved/src/xvedscreen.p
screencursoron updaterof $usepop/pop/x/ved/src/xvedscreen.p
screengraphtrans $popvedlib/term/vedciferscreen.p
screengraphtrans $usepop/pop/x/ved/src/xvedscreen.p
screenleft $usepop/pop/ved/src/vdregexp.p
screenleft $usepop/pop/x/ved/src/xvedscreen.p
screenraw $usepop/pop/x/ved/src/xvedscreen.p
screensize $usepop/pop/packages/popvision/lib/rci_show.p
screenxy $usepop/pop/x/ved/src/xvedscreen.p
scroll $usepop/pop/x/ved/src/xvedscreen.p
scroll_callback $usepop/pop/x/pop/lib/XawTutorial.p
scroll_text_field_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
scrollbar_callback $usepop/pop/x/ved/src/xvedscrollbar.p
scrollbar_moved_handler $usepop/pop/x/ved/src/xvedscrollbar.p
scrolldown $usepop/pop/x/ved/src/xvedscreen.p
scrollregion $usepop/pop/x/ved/src/xvedscreen.p
scrollup $usepop/pop/x/ved/src/xvedscreen.p
sct $popliblib/aed.p
sctr $popliblib/aed.p
search $usepop/pop/packages/rcmenu/menus/menu_search.p
search $usepop/pop/packages/teaching/lib/finger.p
search $usepop/pop/packages/teaching/lib/solvems.p
search $usepop/pop/pml/src/compile.p
search_applier $usepop/pop/x/ui/lib/pop_ui_propertytool.p
search_cb $usepop/pop/x/ved/src/xveddialogs.p
search_default $usepop/pop/x/ui/lib/pop_ui_propertytool.p
search_for $usepop/pop/plog/src/plogved.p
search_whole_words $usepop/pop/x/ved/src/xveddialogs.p
search_whole_words updaterof $usepop/pop/x/ved/src/xveddialogs.p
searchfor $usepop/pop/packages/master/lib/newmaster/utils.p
searchfor_prompt $usepop/pop/packages/master/lib/newmaster/utils.p
searchforhelp $usepop/pop/x/ui/lib/S-poplog_uiS-searchforhelp.p
searchinrange $popvedlib/vedteststartsearch.p
sec $popliblib/aed.p
seconds_left $popvedlib/ved_autosave.p
sect $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sect $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sect $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sect $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
section $popsrc/pop11_sections.p
section_cancel $popsrc/sect_cancel.p
section_export $popsrc/sect_impexp.p
section_import $popsrc/sect_impexp.p
section_name $popsrc/sect_name.p
section_pathname $popsrc/sect_name.p
section_subsect $popsrc/sect_subsect.p
section_supersect $popsrc/sect_subsect.p
see $usepop/pop/plog/src/io.p
seepicture $usepop/pop/lib/turtle/seepicture.p
seetree $usepop/pop/packages/teaching/lib/seetree.p
seglength $popliblib/geometry.p
selectSheep $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
select_apply $popliblib/imap.p
select_command $usepop/pop/packages/rclib/lib/rc_blocks.p
select_command $usepop/pop/packages/teaching/lib/msblocks.p
select_command $usepop/pop/packages/teaching/lib/msdemo.p
select_exec $usepop/pop/packages/neural/src/pop/nui_main.p
select_file $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xol.p
select_node $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
select_row_string $usepop/pop/packages/rclib/lib/rc_scrolltext.p
select_vector_apply $usepop/pop/packages/neural/src/pop/nn_gfxevents.p
select_which_dt $usepop/pop/packages/neural/src/pop/nui_main.p
select_which_egs $usepop/pop/packages/neural/src/pop/nui_main.p
select_which_net $usepop/pop/packages/neural/src/pop/nui_main.p
select_window_dimensions $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
selected $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
selected_list_item $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
selected_list_items $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
selecting_someof $usepop/pop/packages/rclib/teach/rclib_demo.p
selectmenu_cb $usepop/pop/x/ui/lib/pop_ui_projecttool.p
selector $usepop/pop/pml/src/gencode.p
selectors $usepop/pop/pml/src/gencode.p
self $usepop/pop/packages/teaching/lib/elizaprog-2005.p
self $usepop/pop/packages/teaching/lib/elizaprog.p
self_caller $usepop/pop/packages/rclib/auto/self_caller.p
self_inserting $usepop/pop/packages/vedutils/auto/ved_keymap.p
seln_copy $usepop/pop/x/ved/src/xvedselections.p
semrule $usepop/pop/packages/teaching/lib/facets.p
sen $popliblib/aed.p
send_command $popliblib/imap.p
send_process_proc $popliblib/shell_compile.p
send_seq $usepop/pop/x/ved/src/xvedkey.p
sendidseq $usepop/pop/x/ved/src/xvedscreen.p
sendnews $popvedlib/ved_postnews.p
sense_last $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sensor_example $usepop/pop/packages/brait/lib/tutorialsupplement.p
seq_length $usepop/pop/lisp/src/seq.p
seqclose $usepop/pop/lib/objectclass/src/wlist_to_closure.p
sequencep $usepop/pop/lisp/src/seq.p
set $usepop/pop/lisp/src/set.p
set_activation $usepop/pop/packages/newkit/sim/demo/rib/ann_with_examples.p
set_activation $usepop/pop/packages/newkit/sim/demo/rib/orig/ann_with_examples.p
set_arg_list $usepop/pop/x/pop/lib/propsheet_utils.p
set_array $usepop/pop/packages/neural/src/pop/nn_utils.p
set_assoc $popliblib/tparse.p
set_button_label $usepop/pop/x/pop/lib/XmTutorial.p
set_button_label $usepop/pop/x/pop/lib/XolTutorial.p
set_buttons $usepop/pop/x/ui/lib/S-poplog_uiS-confirm_xm.p
set_buttons $usepop/pop/x/ui/lib/S-poplog_uiS-confirm_xol.p
set_bytes $popsrc/move_bytes.p
set_con $usepop/pop/pml/src/env.p
set_configbox_actions $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_contents $usepop/pop/lib/lr_parser/lib/lr_gen.p
set_coords $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_coords $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_coords $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_coords $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_coords $usepop/pop/x/ved/lib/vedxvedmouse.p
set_current_active_object $usepop/pop/packages/rclib/lib/rc_scrolltext.p
set_current_dt $usepop/pop/packages/neural/src/pop/nui_main.p
set_current_egs $usepop/pop/packages/neural/src/pop/nui_main.p
set_current_net $usepop/pop/packages/neural/src/pop/nui_main.p
set_current_picture_object $usepop/pop/packages/rclib/lib/rc_linepic.p
set_current_view $popliblib/current_view.p
set_cursor $popvedlib/ved_draw.p
set_dmac_char $usepop/pop/lisp/src/umacs.p
set_egs_units_needed $usepop/pop/packages/neural/src/pop/nn_examplesets.p
set_entry $usepop/pop/pml/src/env.p
set_execute_permission $usepop/pop/x/ui/lib/S-poplog_uiS-guiProjectUtils.p
set_exn $usepop/pop/pml/src/env.p
set_field_aligned updaterof $usepop/pop/packages/rclib/auto/rc_control_panel.p
set_field_ident updaterof $usepop/pop/packages/rclib/auto/rc_control_panel.p
set_field_value $usepop/pop/packages/teaching/lib/newobj.p
set_file_message $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_file_vals $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_filetype_options $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xm.p
set_filetype_options $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xol.p
set_flavour $usepop/pop/x/ved/src/xved.p
set_fnc $usepop/pop/pml/src/env.p
set_focus $usepop/pop/x/ved/src/xveddialogs.p
set_footer $usepop/pop/x/ui/lib/S-poplog_uiS-filetool_xol.p
set_footer $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xm.p
set_footer $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xol.p
set_global_valof $popautolib/set_global_valof.p
set_gui $usepop/pop/x/pop/lib/propsheet.p
set_gui $usepop/pop/x/ved/src/xvedmenubar.p
set_gui $usepop/pop/x/ved/src/xvedscrollbar.p
set_heading $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
set_heading $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_heading $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_heading $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_heading $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
set_heading $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_index $usepop/pop/x/ui/lib/pop_ui_propertytool.p
set_input $usepop/pop/packages/newkit/sim/demo/rib/ann_with_examples.p
set_input $usepop/pop/packages/newkit/sim/demo/rib/orig/ann_with_examples.p
set_insert_mode $usepop/pop/x/ved/src/xvedscreen.p
set_invokes_call_next_method $usepop/pop/lib/objectclass/src/globals.p
set_list_items $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xm.p
set_locals $popvedlib/ved_draw.p
set_macro_char $usepop/pop/lisp/src/umacs.p
set_maze $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
set_maze $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
set_method_properties $usepop/pop/lib/objectclass/src/methods.p
set_modified $usepop/pop/x/ui/lib/pop_ui_propertytool.p
set_multisheet_values $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_needscompiling $usepop/pop/lib/flavours/flavecore.p
set_nil $usepop/pop/packages/teaching/lib/prodsys.p
set_oldxy $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
set_options $usepop/pop/packages/neural/src/pop/nui_main.p
set_or_unset_someof_buttons_to $usepop/pop/packages/rclib/lib/rc_buttons.p
set_output $usepop/pop/packages/rcmenu/auto/set_output.p
set_pattern $usepop/pop/packages/teaching/lib/prodsys.p
set_pdnargs_mode $usepop/pop/lib/objectclass/src/utils.p
set_pdnargs_raw $usepop/pop/lib/objectclass/src/utils.p
set_pprint_dispatch $usepop/pop/lisp/src/pp-dispatch.p
set_process_entry_term $popsrc/devio.p
set_propbox_attributes $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_random_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_random_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_random_status $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_random_status $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_rel_heading $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_rel_heading $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_rel_heading $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_rel_heading $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_rel_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_rel_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_rel_status $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_rel_status $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_scale_value $usepop/pop/x/pop/lib/XmTutorial.p
set_sensitive $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_server_keys $usepop/pop/x/ved/src/xvedsetup.p
set_sheet_values $usepop/pop/x/ui/lib/pop_ui_projecttool.p
set_sides $usepop/pop/packages/rclib/lib/rc_polypanel.p
set_sig $usepop/pop/pml/src/env.p
set_slider_value $usepop/pop/x/pop/lib/XolTutorial.p
set_sliders $usepop/pop/packages/rclib/lib/rc_polypanel.p
set_slots $usepop/pop/lib/objectclass/auto/set_slots.p
set_spec_slots $usepop/pop/packages/rclib/auto/interpret_specs.p
set_state $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
set_state $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
set_status $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
set_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
set_status $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
set_status $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
set_status $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
set_status $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
set_str $usepop/pop/pml/src/env.p
set_subsystem_options $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xm.p
set_subsystem_options $usepop/pop/x/ui/lib/S-poplog_uiS-helptool_xol.p
set_subvector $popsrc/move_subvector.p
set_syntax_from_char $usepop/pop/lisp/src/readtable.p
set_term_defaults $usepop/pop/ved/src/vdinitseq.p
set_test_proc $usepop/pop/packages/teaching/lib/facets.p
set_timer_field $usepop/pop/x/ved/src/xveddialogs.p
set_tranfns $usepop/pop/packages/popvision/lib/mlp.p
set_tranfns updaterof $usepop/pop/packages/popvision/lib/mlp.p
set_tty_ospeed $popsrc/termcap.p
set_tycon $usepop/pop/pml/src/env.p
set_tyvar $usepop/pop/pml/src/env.p
set_undef_clos $popsrc/lispcore.p
set_unicode_mode $usepop/pop/x/ved/src/xvedscreen.p
set_up $usepop/pop/lib/flavours/advent_flavours.p
set_var $usepop/pop/pml/src/env.p
set_variable_callback $usepop/pop/x/pop/lib/XmTutorial.p
set_variable_callback $usepop/pop/x/pop/lib/XolTutorial.p
set_version_number $usepop/pop/packages/master/lib/newmaster/utils.p
set_work_arrays $usepop/pop/packages/popvision/lib/horn_schunck.p
set_xved_dialog_colours $usepop/pop/x/ved/src/xveddialogs.p
setalpha $popliblib/aed.p
setalpha $usepop/pop/lib/obsolete/graphic.p
setcamp $usepop/pop/packages/teaching/lib/rhino.p
setchanged $usepop/pop/packages/teaching/auto/ved_vcalc.p
setchar $popvedlib/veddrawline.p
setcolortable $popliblib/aed.p
setdiff $popliblib/sets.p
setf_is_updater $usepop/pop/lisp/src/setf.p
setf_method $usepop/pop/lisp/src/setf.p
setf_method updaterof $usepop/pop/lisp/src/setf.p
setframe $popliblib/aed.p
setfrontlist $popsrc/setfrontlist.p
setgin $usepop/pop/lib/obsolete/graphic.p
setgraphic $popliblib/aed.p
setgraphic $usepop/pop/lib/obsolete/graphic.p
sethunter $usepop/pop/packages/teaching/lib/rhino.p
setlisp $usepop/pop/lisp/src/subsystem_procedures.p
setlisp $usepop/pop/packages/teaching/lib/oldlisp.p
setlocation $usepop/pop/packages/teaching/lib/rhino.p
setmeaning $usepop/pop/packages/teaching/lib/gramdemo.p
setnullstatus $usepop/pop/lib/obsolete/graphic.p
setpicture $usepop/pop/lib/turtle/convolve.p
setpop $popsrc/setpop.p
setpop_reset $popsrc/setpop_reset.p
setrmsdepend $usepop/pop/packages/teaching/lib/rms.p
setscope $usepop/pop/lib/obsolete/graphic.p
setscrollregion $popvedlib/term/vedvi55screen.p
setscrollregion $usepop/pop/x/ved/src/xvedscreen.p
setsfloatzero $usepop/pop/packages/popvision/lib/canny.p
setspect24 $usepop/pop/packages/popvision/lib/rc_array.p
setspect8 $usepop/pop/packages/popvision/lib/rc_array.p
setstacklength $popsrc/lispcore.p
settopwindow $usepop/pop/packages/rcmenu/auto/ved_GoMakeTop.p
settrees $usepop/pop/packages/teaching/lib/rhino.p
setup $popliblib/tparse.p
setup $popvedlib/ved_print.p
setup $usepop/pop/lib/database/think.p
setup $usepop/pop/packages/popvision/lib/apppolygon.p
setup $usepop/pop/packages/teaching/lib/eshell.p
setup $usepop/pop/packages/teaching/lib/grammar.p
setup $usepop/pop/packages/teaching/lib/logic.p
setupAnimals $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
setupDog $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
setupPen $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
setupTrees $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
setup_LINE $usepop/pop/lib/include/doc_index.ph
setup_blob $usepop/pop/packages/rclib/auto/rc_slider.p
setup_clause_lvars $usepop/pop/plog/src/gencode.p
setup_colour_map $usepop/pop/packages/neural/src/pop/nn_gfxutils.p
setup_examplefile_descriptors $usepop/pop/packages/neural/src/pop/nn_examplesets.p
setup_file_count_vector $usepop/pop/packages/neural/src/pop/nn_file_utils.p
setup_file_dev $usepop/pop/packages/neural/src/pop/nn_file_utils.p
setup_filename $usepop/pop/packages/vedmail/auto/ved_checkmail.p
setup_finger $usepop/pop/packages/teaching/lib/finger.p
setup_gn $popvedlib/ved_net.p
setup_matchvars $usepop/pop/packages/lib/poprulebase.p
setup_matchvars $usepop/pop/packages/newkit/prb/lib/poprulebase.p
setup_options_file $popvedlib/vedfilecomplete.p
setup_outputfile_descriptors $usepop/pop/packages/neural/src/pop/nn_apply.p
setup_pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
setup_pen $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
setup_pen $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
setup_pen $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
setup_pic $usepop/pop/packages/rclib/auto/rc_transform_pictures.p
setup_pics $usepop/pop/packages/rclib/auto/rc_transform_pictures.p
setup_raw_data_arrays $usepop/pop/packages/neural/src/pop/nn_examplesets.p
setup_raw_data_arrays $usepop/pop/packages/neural/src/pop/nn_examplesets.p
setup_simulation $usepop/pop/packages/newkit/sim/lib/sim_harness.p
setup_sort_preds $usepop/pop/lisp/src/seq.p
setup_std_io $usepop/pop/pml/src/io.p
setup_vedmailfile $usepop/pop/packages/vedmail/auto/ved_getmail.p
setupinference $usepop/pop/packages/teaching/lib/logic.p
setv500screen $popvedlib/v500.p
setvdu $popvedlib/term/vedvi500screen.p
setvdu $usepop/pop/lib/obsolete/graphic.p
setvi500screen $popvedlib/term/vedvi500screen.p
sf_token $popsrc/lispcore.p
sh_compile $popautolib/sh_subsystem.p
sh_send $popautolib/sh_subsystem.p
shadow $popsrc/lispcore.p
shadow_= $popliblib/shadowkey_key.p
shadow_construct $popliblib/consshadowkey.p
shadow_length $popliblib/shadowkey_key.p
shadowclass $popautolib/shadowclass.p
shadowclass_cons $popliblib/shadowclass_data.p
shadowclass_dest $popliblib/shadowclass_data.p
shadowclass_field $popliblib/shadowclass_data.p
shadowclass_fill $popliblib/shadowclass_data.p
shadowclass_import $popliblib/shadowclass_data.p
shadowclass_init $popliblib/shadowclass_data.p
shadowclass_recognise $popliblib/shadowclass_data.p
shadowclass_refresh $popliblib/shadowclass_data.p
shadowclass_subscr $popliblib/shadowclass_data.p
shadowing_import $popsrc/lispcore.p
shadowrec_print $popliblib/shadowkey_key.p
shadowrec_subscr $popliblib/shadowkey_key.p
shadowrec_subscr updaterof $popliblib/shadowkey_key.p
shapetree $popliblib/showtree.p
share_structures $usepop/pop/pml/src/modules.p
share_types $usepop/pop/pml/src/modules.p
shared_initialize $usepop/pop/lisp/src/clos.p
shared_slot $usepop/pop/lib/objectclass/auto/define_shared_slot.p
shared_slot $usepop/pop/lib/objectclass/rt/slots.p
shared_slot updaterof $usepop/pop/lib/objectclass/rt/slots.p
sheepSafeDist $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_action_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_action_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_action_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_action_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_button_1_down $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_button_1_down $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_button_1_drag $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_button_1_drag $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_button_1_up $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_button_3_up $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_graze $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_graze $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheep_graze $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_graze $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_graze $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_graze $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_graze $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_instinct_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_instinct_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_instinct_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_instinct_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_obstacle_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_obstacle_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_obstacle_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_obstacle_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_perception_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_perception_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_perception_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_perception_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_resolve_behaviour_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_setup $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheep_setup $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheep_setup $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_setup $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_setup $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_setup $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheep_setup $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheep_social_rules $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheep_social_rules $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheep_social_rules $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheep_social_rules $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheepdog_panel $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheepdog_panel $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheepdog_panel $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sheepdog_panel $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheepdog_panel $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheepy $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sheepy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sheepy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sheepy $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sheepy $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sheepy $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sheet_string_convert $usepop/pop/packages/neural/src/pop/nui_xpanels.p
sheet_string_convert updaterof $usepop/pop/packages/neural/src/pop/nui_xpanels.p
sheet_title $usepop/pop/x/ui/lib/pop_ui_propertytool.p
sheet_word_convert $usepop/pop/packages/neural/src/pop/nui_xpanels.p
sheet_word_convert updaterof $usepop/pop/packages/neural/src/pop/nui_xpanels.p
shell_compile $popliblib/shell_compile.p
shell_send $popliblib/shell_compile.p
shiftbounds_1d $usepop/pop/packages/popvision/lib/arraysample.p
shiftpos_post $usepop/pop/packages/popvision/lib/rci_show.p
shiftpos_pre $usepop/pop/packages/popvision/lib/rci_show.p
shkP_Cons $popliblib/shadowkey_key.p
shkP_Dest $popliblib/shadowkey_key.p
shkP_Field_swap $popliblib/shadowkey_key.p
shkP_Fill $popliblib/shadowkey_key.p
shkP_Import $popliblib/shadowkey_key.p
shkP_Import updaterof $popliblib/shadowkey_key.p
shkP_Recog $popliblib/shadowkey_key.p
shkP_Refresh $popliblib/shadowkey_key.p
shkP_Refresh_subscr $popliblib/shadowkey_key.p
shkP_Subscr $popliblib/shadowkey_key.p
shkP_Subscr updaterof $popliblib/shadowkey_key.p
shkP_Subscr_check $popliblib/shadowkey_key.p
shlib_error $popsrc/extern_symbols.p
shlib_searchlist $popsrc/unixextern.p
sho $popliblib/aed.p
short $usepop/pop/packages/teaching/lib/elizaprog-2005.p
short $usepop/pop/packages/teaching/lib/elizaprog.p
shorter $usepop/pop/lib/turtle/regions.p
shortpointvec $usepop/pop/x/pop/lib/Xpw/XpwPixmap.p
should $usepop/pop/packages/teaching/lib/elizaprog-2005.p
should $usepop/pop/packages/teaching/lib/elizaprog.p
show $usepop/pop/lib/objectclass/auto/ved_oca.p
show_activs2d $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_and_name_instance $usepop/pop/packages/brait/lib/tools.p
show_banner_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
show_bias2d $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_box $usepop/pop/x/ui/lib/pop_ui_propertytool.p
show_class_tree $usepop/pop/lib/objectclass/auto/ved_oca.p
show_code $usepop/pop/plog/src/gencode.p
show_entries $usepop/pop/pml/src/showdef.p
show_file_vals $usepop/pop/x/ui/lib/pop_ui_projecttool.p
show_finger $usepop/pop/packages/teaching/lib/finger.p
show_fixity $usepop/pop/pml/src/showdef.p
show_ignore $usepop/pop/lib/objectclass/auto/ved_oci.p
show_info $usepop/pop/packages/vedmail/auto/ved_decode.p
show_logoptions $usepop/pop/packages/neural/src/pop/nui_main.p
show_mainpanel_gfx $usepop/pop/packages/neural/src/pop/nui_panels.p
show_mainpanel_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
show_mainpanel_txt $usepop/pop/packages/neural/src/pop/nui_txtpanels.p
show_mainpanel_x $usepop/pop/packages/neural/src/pop/nui_xpanels.p
show_menu_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
show_menu_txt $usepop/pop/packages/neural/src/pop/nui_txtpanels.p
show_multisheet_values $usepop/pop/x/ui/lib/pop_ui_projecttool.p
show_options_gfx $usepop/pop/packages/neural/src/pop/nui_panels.p
show_options_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
show_options_txt $usepop/pop/packages/neural/src/pop/nui_txtpanels.p
show_options_x $usepop/pop/packages/neural/src/pop/nui_xpanels.p
show_panel $usepop/pop/packages/neural/src/pop/nui_main.p
show_panel_gfx $usepop/pop/packages/neural/src/pop/nui_panels.p
show_panel_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
show_panel_txt $usepop/pop/packages/neural/src/pop/nui_txtpanels.p
show_panel_x $usepop/pop/packages/neural/src/pop/nui_xpanels.p
show_project_file_sheet $usepop/pop/x/ui/lib/pop_ui_projecttool.p
show_selected $usepop/pop/packages/rclib/teach/rclib_demo.p
show_sheet $usepop/pop/x/ui/lib/pop_ui_propertytool.p
show_sheet_values $usepop/pop/x/ui/lib/pop_ui_projecttool.p
show_state $usepop/pop/lib/lr_parser/lib/lr_trace.p
show_stims_from $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_stims_to $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_trace_match $usepop/pop/packages/lib/poprulebase.p
show_trace_match $usepop/pop/packages/newkit/prb/lib/poprulebase.p
show_trainoptions $usepop/pop/packages/neural/src/pop/nui_main.p
show_user_result $usepop/pop/packages/neural/src/pop/nui_utils.p
show_weights2d_from $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_weights2d_to $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_weights_from $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
show_weights_to $usepop/pop/packages/neural/src/pop/nn_netdisplay.p
showarray $popliblib/showarray.p
showbox $usepop/pop/packages/teaching/lib/seetree.p
showdata $usepop/pop/lib/obsolete/hand.p
showdata $usepop/pop/packages/rclib/lib/rc_blocks.p
showdata $usepop/pop/packages/teaching/lib/mshand.p
showdata $usepop/pop/packages/teaching/lib/termhand.p
showdef $usepop/pop/pml/src/showdef.p
showfiles $usepop/pop/packages/vedmail/auto/ved_decode.p
showinclude $popautolib/showinclude.p
showinnodes $usepop/pop/packages/teaching/lib/rmsapps.p
showjust $usepop/pop/packages/teaching/lib/rms.p
showlabels $usepop/pop/lib/turtle/lamlabel.p
showlib $popautolib/showlib.p
shownamestring $popvedlib/windows.p
shownode $usepop/pop/packages/teaching/lib/rms.p
shownodedep $usepop/pop/packages/teaching/lib/rms.p
shownodes $usepop/pop/packages/teaching/lib/rmsapps.p
showoutnodes $usepop/pop/packages/teaching/lib/rmsapps.p
showparses $popliblib/tparse.p
showparses $usepop/pop/packages/rclib/lib/rc_blocks.p
showplan $usepop/pop/packages/teaching/lib/solver.p
showstate $usepop/pop/packages/teaching/lib/river.p
showtree $popliblib/showtree.p
showtree_box $popliblib/showtree.p
showtree_box $usepop/pop/packages/rclib/auto/rc_showtree.p
showtree_draw_node $popliblib/showtree.p
showtree_draw_node $usepop/pop/packages/rclib/auto/rc_showtree.p
showtree_graphical $popliblib/showtree.p
showtree_height $popliblib/showtree.p
showtree_height $usepop/pop/packages/rclib/auto/rc_showtree.p
showtree_mess $popliblib/showtree.p
showtree_mid $popliblib/showtree.p
showtree_name_&_subtrees $popliblib/showtree.p
showtree_printable $popliblib/showtree.p
showtree_quit $popliblib/showtree.p
showtree_width $popliblib/showtree.p
showtree_width $usepop/pop/packages/rclib/auto/rc_showtree.p
showvehicle1 $usepop/pop/packages/brait/lib/tutorialsupplement.p
showvehicle2 $usepop/pop/packages/brait/lib/tutorialsupplement.p
shuffle $popautolib/shuffle.p
sidejoin $popliblib/showtree.p
sigmatch_error $usepop/pop/pml/src/type_errors.p
sign $popsrc/arith1.p
signature_instance $usepop/pop/pml/src/modules.p
signature_match $usepop/pop/pml/src/modules.p
silly $popautolib/ARGS.p
silly $usepop/pop/packages/newkit/prb/test/testnewpoprulebase.p
silly $usepop/pop/packages/rclib/auto/ARGS.p
silly_check $usepop/pop/packages/newkit/prb/test/check.p
sim_add_data $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_add_list_to_db $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_add_rule_cluster $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_add_rule_system $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_add_rule_system_startup $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_action_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_action_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_action_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_actions_out_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_actions_out_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_endrun_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_endrun_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_messages_in_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_messages_in_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_messages_out_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_messages_out_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_rulefamily_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_ruleset_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_ruleset_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_ruleset_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_agent_ruleset_trace $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_agent_running_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_running_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_agent_terminated_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_angle_diff $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_angle_xy $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_clear_database $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_control_panel $usepop/pop/packages/newkit/sim/auto/sim_control_panel.p
sim_coords $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_coords updaterof $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_countdatabase $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_data_precedes $usepop/pop/packages/newkit/sim/auto/sim_data_precedes.p
sim_database_assoc $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_degrees_diff $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_delete_data $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_direction $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_direction $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_direction $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_direction $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_direction $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_direction_two $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_direction_two $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_direction_two $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_direction_two $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_direction_two $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_distance $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_distance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_distance $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_distance $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_distance $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_distance $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_distance $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_distance $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_distance $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_distance $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_distance_from $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_do_action $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_do_actions $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_do_actions $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_draw_face $usepop/pop/packages/newkit/sim/lib/sim_faces.p
sim_edit_object_list $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_edit_object_list $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_flush $usepop/pop/packages/newkit/sim/auto/sim_flush.p
sim_flush1 $usepop/pop/packages/newkit/sim/auto/sim_flush1.p
sim_flush_data $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_get_data $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_get_data $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_get_data updaterof $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_get_data updaterof $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_heading_from $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_immobile $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_immobile_agent $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_in_database $usepop/pop/packages/newkit/sim/auto/sim_in_database.p
sim_init_angle $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_intersect_lines $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_intersect_segs $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_interval_test $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_movable $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_movable_agent $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_move_to $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_multiwin $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_multiwin_mobile $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_multiwin_static $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_normalise_angle $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_object $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_picagent_window $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_post_cycle_actions $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_post_cycle_actions $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_post_process $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_post_setup $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_pr_db $usepop/pop/packages/newkit/sim/auto/sim_pr_db.p
sim_present $usepop/pop/packages/newkit/sim/auto/sim_present.p
sim_rotate_angle $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_run_agent $usepop/pop/packages/brait/lib/box_object.p
sim_run_agent $usepop/pop/packages/brait/lib/vehicle_agent.p
sim_run_agent $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_run_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_run_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_run_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_run_agent $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_run_agent $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/teach/armysim.p
sim_run_agent $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_run_agent $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_run_agent $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_run_rulesystem $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_run_sensors $usepop/pop/packages/brait/lib/ball_object.p
sim_run_sensors $usepop/pop/packages/brait/lib/source_object.p
sim_run_sensors $usepop/pop/packages/brait/lib/vehicle_agent.p
sim_run_sensors $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_scheduler $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_scheduler_finished $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_scheduler_finished $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_scheduler_finished $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_scheduler_objects $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_scheduler_pausing_trace $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/lib/sim_harness.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_scheduler_pausing_trace $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_send_message $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_sense_agent $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sim_sense_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sim_sense_agent $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sim_sense_agent $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
sim_sense_agent $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_sense_agent $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sim_sense_agent $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sim_sense_agent $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sim_set_angle $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_set_coords $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_setup $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_setup_scheduler $usepop/pop/packages/brait/lib/braitenberg_sim.p
sim_setup_scheduler $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_shared_data_object $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_stack_check $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_stop_agent $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_stop_scheduler $usepop/pop/packages/newkit/sim/lib/sim_agent.p
sim_subtend_ang $usepop/pop/packages/newkit/sim/lib/sim_geom.p
sim_syspr_db $usepop/pop/packages/newkit/sim/auto/sim_pr_db.p
sim_transxy_from_pic $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
sim_transxy_to_pic $usepop/pop/packages/newkit/sim/lib/sim_picagent.p
simpleTree $usepop/pop/lib/objectclass/src/trees.p
simple_action $popvedlib/ved_draw.p
simple_array_p $usepop/pop/lisp/src/arrays.p
simple_type_error $usepop/pop/lisp/src/util.p
sin $popsrc/trigc.p
single_escape $usepop/pop/lisp/src/itemise.p
singlearr $usepop/pop/packages/neural/lib/convarr.p
singlearr updaterof $usepop/pop/packages/neural/lib/convarr.p
singlechoice_dismiss_cb $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
singlechoice_popdown_cb $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
singlechoice_select_cb $usepop/pop/packages/neural/src/pop/nn_gfxdialogs.p
singleton $popliblib/sets.p
singleton $usepop/pop/lib/objectclass/auto/define_singleton.p
singprec $usepop/pop/packages/popvision/lib/lapack.p
sinh $popsrc/trigh.p
sizeof_spec $popautolib/kr_newc_dec.p
sizeof_spec $popautolib/newc_dec.p
sizeof_spec $usepop/pop/packages/newc_dec/auto/newc_dec.p
skip_trim $usepop/pop/packages/popvision/lib/convolve_2d.p
skipbackover $popliblib/newpop.p
skipchar $popsrc/skipchar.p
skipchar_back $popsrc/skipchar_back.p
skipform $usepop/pop/lisp/src/itemise.p
skipover $popautolib/sys_translate_exlibs.p
skipover $popliblib/newpop.p
skipspace $usepop/pop/packages/master/auto/newmaster_utils.p
skipspace $usepop/pop/packages/master/lib/newmaster/utils.p
skipto $popautolib/sys_translate_exlibs.p
skipto $popliblib/newpop.p
slash $usepop/pop/lisp/src/itemise.p
sleep $usepop/pop/lisp/src/time.p
sleep_delay $usepop/pop/packages/rclib/lib/rc_pythagoras.p
sleepy $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sleepy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sleepy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sleepy $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sleepy $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sleepy $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
slide $popdatalib/domains.p
slider4_reactor $usepop/pop/packages/rclib/lib/rc_polypanel.p
slider_blob_coords_from_value $usepop/pop/packages/rclib/auto/rc_slider.p
slider_coords_from_value $usepop/pop/packages/rclib/auto/rc_slider.p
slider_field_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
slider_reactor $usepop/pop/packages/rclib/teach/newtest.p
slider_value_from_blob_coords $usepop/pop/packages/rclib/auto/rc_slider.p
slider_value_from_coords $usepop/pop/packages/rclib/auto/rc_slider.p
slider_value_of_name $usepop/pop/packages/rclib/auto/rc_control_panel.p
slider_value_of_name updaterof $usepop/pop/packages/rclib/auto/rc_control_panel.p
slot_boundp $usepop/pop/lisp/src/clos.p
slot_exists_p $usepop/pop/lisp/src/clos.p
slot_makunbound $usepop/pop/lisp/src/clos.p
slot_proc_for_key $usepop/pop/lib/objectclass/src/plant_utils.p
slot_value $usepop/pop/lisp/src/clos.p
slot_value updaterof $usepop/pop/lisp/src/clos.p
slowprocs $popliblib/slowprocs.p
smmult $popliblib/geom3d.p
smoothcurve $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
smoothcurve $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
snake_= $usepop/pop/packages/popvision/lib/snakes.p
snake_emergency_imforce $usepop/pop/packages/popvision/lib/snakes.p
snake_imforce $usepop/pop/packages/popvision/lib/snakes.p
snake_nullforce $usepop/pop/packages/popvision/lib/snakes.p
snake_params $usepop/pop/packages/popvision/lib/snakes.p
sneezy $usepop/pop/packages/newkit/sim/demo/pcw.sheep.p
sneezy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
sneezy $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
sneezy $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
sneezy $usepop/pop/packages/newkit/sim/teach/sim_sheep.p
sneezy $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
sockaddr_to_name $popliblib/unix_sockets.p
solve_dilation $usepop/pop/packages/popvision/lib/solve_dilation.p
solve_dilation_arrays $usepop/pop/packages/popvision/lib/solve_dilation.p
solve_dilation_list $usepop/pop/packages/popvision/lib/solve_dilation.p
solve_rules $usepop/pop/packages/newkit/prb/lib/prbriver.p
solve_rules $usepop/pop/packages/newkit/prb/teach/prbrunriver.p
solve_rules $usepop/pop/packages/newkit/prb/test/prbrunriver.p
solvematches $usepop/pop/packages/popvision/lib/warp_2d.p
somebadlabel $usepop/pop/packages/teaching/lib/waltz.p
someof_field_instance $usepop/pop/packages/rclib/auto/rc_control_panel.p
sometrue $usepop/pop/packages/teaching/lib/waltz.p
sort $popautolib/sort.p
sort_and_write $popliblib/buildindex.p
sort_by $usepop/pop/lib/objectclass/lib/oc_utils.p
sort_constrs $usepop/pop/pml/src/parse.p
sort_env $usepop/pop/pml/src/env.p
sort_row $usepop/pop/pml/src/parse.p
sort_seq $usepop/pop/lisp/src/seq.p
sortdata $usepop/pop/packages/teaching/lib/picdem.p
sortdims $usepop/pop/packages/popvision/lib/arraysample.p
source $usepop/pop/packages/brait/lib/source_object.p
sourcefile $usepop/pop/pml/src/compile.p
sp $popautolib/sp.p
speak_espeak $popautolib/speak_espeak.p
speak_espeak $usepop/pop/packages/teaching/auto/haiku_speak.p
speak_flite $popautolib/speak_flite.p
spec $usepop/pop/packages/popvision/lib/arrpack.p
spec_->_etype $usepop/pop/lisp/src/specs.p
spec_->_init $usepop/pop/lisp/src/specs.p
spec_->_key $usepop/pop/lisp/src/specs.p
spec_<= $usepop/pop/lisp/src/specs.p
special $usepop/pop/packages/teaching/lib/oldlisp.p
special_form_p $usepop/pop/lisp/src/tokens.p
special_form_p updaterof $usepop/pop/lisp/src/tokens.p
special_record $usepop/pop/plog/src/predicate_record.p
spectpix24 $usepop/pop/packages/popvision/lib/rc_array.p
spectpix8 $usepop/pop/packages/popvision/lib/rc_array.p
spectrum_rgb $usepop/pop/packages/popvision/lib/rc_array.p
specvec $usepop/pop/packages/popvision/lib/arrpack.p
speedFind $usepop/pop/packages/newkit/sim/lib/hybrid_sheepdog.p
splice $usepop/pop/packages/teaching/lib/solver.p
split $popliblib/context.p
split_chars $popliblib/typespec_utils.p
split_match $usepop/pop/pml/src/gencode.p
split_spec $usepop/pop/plog/src/plogved.p
splitstring $popliblib/buildindex.p
splitstring $usepop/pop/packages/rcmenu/auto/menu_new_menu.p
splitup $usepop/pop/packages/teaching/lib/solver.p
spr $popsrc/print.p
sprintf $popautolib/sprintf.p
spuin $popliblib/aed.p
spuout $popliblib/aed.p
spy $popliblib/super.p
spy $usepop/pop/plog/src/spy.p
spy_action $usepop/pop/plog/src/spy.p
spyall $usepop/pop/plog/src/spy.p
spymessage $usepop/pop/plog/src/spy.p
spyon $usepop/pop/plog/src/spy.p
spypoint $usepop/pop/plog/src/spy.p
spypoints $usepop/pop/plog/src/spy.p
spyread $popliblib/super.p
sql_alloc_statement $popliblib/odbc.p
sql_app_result_set $popliblib/odbc.p
sql_bind_column $popliblib/odbc.p
sql_bind_parameter $popliblib/odbc.p
sql_column_attribute $popliblib/odbc.p
sql_connect $popliblib/odbc.p
sql_connect_attribute $popliblib/odbc.p
sql_connect_functions $popliblib/odbc.p
sql_connect_option $popliblib/odbc.p
sql_connect_option updaterof $popliblib/odbc.p
sql_cons_sql_type $popliblib/odbc.p
sql_cursor_name $popliblib/odbc.p
sql_cursor_name updaterof $popliblib/odbc.p
sql_data_source_repeater $popliblib/odbc.p
sql_describe_column $popliblib/odbc.p
sql_describe_parameter $popliblib/odbc.p
sql_dest_sql_type $popliblib/odbc.p
sql_disconnect $popliblib/odbc.p
sql_driver_repeater $popliblib/odbc.p
sql_environment $popliblib/odbc.p
sql_execute $popliblib/odbc.p
sql_extended_fetch $popliblib/odbc.p
sql_fetch $popliblib/odbc.p
sql_free_statement $popliblib/odbc.p
sql_native_sql $popliblib/odbc.p
sql_num_parameters $popliblib/odbc.p
sql_num_result_columns $popliblib/odbc.p
sql_prepare $popliblib/odbc.p
sql_row_count $popliblib/odbc.p
sql_select_column_privileges $popliblib/odbc.p
sql_select_columns $popliblib/odbc.p
sql_select_foreign_keys $popliblib/odbc.p
sql_select_primary_keys $popliblib/odbc.p
sql_select_special_columns $popliblib/odbc.p
sql_select_statistics $popliblib/odbc.p
sql_select_table_privileges $popliblib/odbc.p
sql_select_tables $popliblib/odbc.p
sql_select_types $popliblib/odbc.p
sql_set_position $popliblib/odbc.p
sql_statement_busy $popliblib/odbc.p
sql_statement_busy updaterof $popliblib/odbc.p
sql_statement_option $popliblib/odbc.p
sql_statement_option updaterof $popliblib/odbc.p
sql_transact $popliblib/odbc.p
sqrt $popsrc/sqrt.p
square $usepop/pop/lib/turtle/square.p
square $usepop/pop/packages/rclib/demo/aze.connect4.p
square $usepop/pop/packages/teaching/lib/evpics.p
squared_gradients $usepop/pop/packages/popvision/lib/squared_gradients.p
squote $usepop/pop/pml/src/lex.p
src $popautolib/src.p
srm $popliblib/aed.p
ss_com_to_label $usepop/pop/x/ui/lib/S-poplog_uiS-guiProjectUtils.p
ss_compile_ved_or_file $usepop/pop/x/ui/lib/pop_ui_projecttool.p
ss_libcompile $usepop/pop/x/ui/lib/pop_ui_librarytool.p
ss_libhelp $usepop/pop/x/ui/lib/pop_ui_librarytool.p
ss_libshow $usepop/pop/x/ui/lib/pop_ui_librarytool.p
ss_to_label $usepop/pop/x/ui/lib/S-poplog_uiS-guiProjectUtils.p
ssintersect $popliblib/geometry.p
stack_chars_from $usepop/pop/packages/rclib/lib/rc_buttons.p
stack_item $usepop/pop/x/pop/auto/XptArgList.p
stack_item $usepop/pop/x/pop/auto/XptCallbackList.p
stack_offset $popsrc/ass.p
stacklength $popsrc/stack.p
stamp $usepop/pop/pml/src/util.p
standard_char_p $usepop/pop/lisp/src/chars.p
standard_featurespec_abbreviations $usepop/pop/packages/rclib/auto/interpret_specs.p
standard_input $usepop/pop/lisp/src/streams.p
standard_input updaterof $usepop/pop/lisp/src/streams.p
standard_output $usepop/pop/lisp/src/streams.p
standard_output updaterof $usepop/pop/lisp/src/streams.p
standardpreclist $usepop/pop/lib/flavours/flavecore.p
star $usepop/pop/pml/src/lex.p
start $usepop/pop/packages/newkit/prb/test/prbriver.p
start $usepop/pop/packages/newkit/prb/test/prbriver2.p
start $usepop/pop/packages/teaching/lib/blocks/driver.p
start $usepop/pop/packages/teaching/lib/finger.p
start $usepop/pop/packages/teaching/lib/river.p
start_coords $usepop/pop/packages/rclib/demo/painting_demo.p
start_coords $usepop/pop/packages/rclib/lib/painting_demo.p
start_easel $usepop/pop/packages/rclib/demo/painting_demo.p
start_easel $usepop/pop/packages/rclib/lib/painting_demo.p
start_record $popautolib/record.p
start_rules $usepop/pop/packages/newkit/prb/auto/prb_saverules.p
start_rules $usepop/pop/packages/newkit/prb/lib/prbriver.p
start_views $popliblib/current_view.p
start_vturtle $usepop/pop/lib/turtle/start_vturtle.p
startactive $usepop/pop/lib/obsolete/active.p
startactor $popliblib/actor.p
startclass $usepop/pop/packages/teaching/lib/newobj.p
startclock $popvedlib/ved_clock.p
startclock $usepop/pop/packages/vedutils/auto/ved_clock.p
startdown $usepop/pop/lib/obsolete/hangman.p
startfindall $popautolib/forall_match.p
startpopprint $popliblib/popprint.p
starts_ok $usepop/pop/packages/vedmail/auto/vedatmailstart.p
starts_with $usepop/pop/lisp/src/util.p
starttryall $usepop/pop/lib/database/forevery.p
startup $usepop/pop/lib/turtle/start_vturtle.p
startup $usepop/pop/packages/rcmenu/teach/menu_demo.p
startup_rib $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
startvec $usepop/pop/packages/popvision/lib/arraysample.p
startwindow $usepop/pop/ved/src/vdregexp.p
startwindow $usepop/pop/x/ved/lib/vedxvedmouse.p
startword $usepop/pop/ved/src/vdregexp.p
startword $usepop/pop/x/ved/lib/vedxvedmouse.p
stat1 $usepop/pop/packages/rclib/teach/rc_linepic.demo.p
statpic $usepop/pop/packages/rclib/lib/rc_linked_pic.p
statusbufferlimit_accepter $usepop/pop/x/ui/lib/pop_ui_propertytool.p
steer $usepop/pop/packages/newkit/sim/demo/sim_sheepdog-old.p
steer $usepop/pop/packages/newkit/sim/demo/sim_sheepdog.p
steer $usepop/pop/packages/newkit/sim/lib/sim_sheepdog.p
steer $usepop/pop/packages/newkit/sim/teach/sim_sheepdog.p
stepacross $usepop/pop/lib/obsolete/hand.p
stmt_sqlstate $popliblib/odbc.p
stop $popautolib/stop.p
stopclock $popvedlib/ved_clock.p
stopclock $usepop/pop/packages/vedutils/auto/ved_clock.p
store $usepop/pop/packages/rclib/demo/aze.connect4.p
storedata $usepop/pop/lib/database/oldstoredata.p
storedata $usepop/pop/lib/database/storedata.p
storepicture $usepop/pop/lib/turtle/storepicture.p
storevar $popliblib/file.p
str_input_name $usepop/pop/lisp/src/streams.p
straight_func $usepop/pop/packages/brait/lib/activation_functions.p
straight_hough $usepop/pop/packages/popvision/lib/straight_hough.p
straight_hough_array $usepop/pop/packages/popvision/lib/straight_hough.p
straight_line_point $usepop/pop/packages/newkit/sim/demo/rib/ijcai95.p
straight_line_point $usepop/pop/packages/newkit/sim/demo/rib/orig/ijcai95.p
straightjoin $popliblib/showtree.p
stream_device $usepop/pop/pml/src/io.p
stream_element_type $usepop/pop/lisp/src/streams.p
stream_error $usepop/pop/lisp/src/streams.p
stream_full_name $usepop/pop/pml/src/io.p
streamdev $usepop/pop/lisp/src/streams.p
string_/= $usepop/pop/lisp/src/strings.p
string_< $usepop/pop/lisp/src/strings.p
string_<= $usepop/pop/lisp/src/strings.p
string_= $usepop/pop/lisp/src/strings.p
string_> $usepop/pop/lisp/src/strings.p
string_>= $usepop/pop/lisp/src/strings.p
string_capitalize $usepop/pop/lisp/src/strings.p
string_char_p $usepop/pop/lisp/src/chars.p
string_downcase $usepop/pop/lisp/src/strings.p
string_equal $usepop/pop/lisp/src/strings.p
string_greaterp $usepop/pop/lisp/src/strings.p
string_input $usepop/pop/packages/neural/src/pop/nui_utils.p
string_left_trim $usepop/pop/lisp/src/strings.p
string_lessp $usepop/pop/lisp/src/strings.p
string_match_score $popvedlib/ved_h.p
string_not_equal $usepop/pop/lisp/src/strings.p
string_not_greaterp $usepop/pop/lisp/src/strings.p
string_not_lessp $usepop/pop/lisp/src/strings.p
string_right_trim $usepop/pop/lisp/src/strings.p
string_to_sym $usepop/pop/lisp/src/util.p
string_trim $usepop/pop/lisp/src/strings.p
string_upcase $usepop/pop/lisp/src/strings.p
stringin $popsrc/stringin.p
stringout $usepop/pop/packages/neural/lib/netfileutil.p
stringp $usepop/pop/lisp/src/seq.p
stringtolist $usepop/pop/packages/teaching/auto/ttt.p
strip_doc_files $popliblib/make_indexes.p
stripfront $popliblib/fmatches.p
stripof $popliblib/matrix.p
stripoutvars $popliblib/crossref.p
strips $usepop/pop/packages/teaching/lib/solver.p
striptail $popliblib/fmatches.p
strlowercase $popautolib/strlowercase.p
strmember $popsrc/locchar.p
strname_deref $usepop/pop/pml/src/modules.p
strnumber $popsrc/item.p
stroppy $usepop/pop/packages/teaching/lib/stroppy.p
struct_field_access $popautolib/kr_newc_dec.p
struct_field_access $popautolib/newc_dec.p
struct_field_access $usepop/pop/packages/newc_dec/auto/newc_dec.p
struct_field_access updaterof $popautolib/kr_newc_dec.p
struct_field_access updaterof $popautolib/newc_dec.p
struct_field_access updaterof $usepop/pop/packages/newc_dec/auto/newc_dec.p
structenv_instance $usepop/pop/pml/src/modules.p
structure_class $usepop/pop/lisp/src/clos-types.p
structure_info $popautolib/kr_newc_dec.p
structure_info $popautolib/newc_dec.p
structure_info $usepop/pop/packages/newc_dec/auto/newc_dec.p
structure_info updaterof $popautolib/kr_newc_dec.p
structure_info updaterof $popautolib/newc_dec.p
structure_info updaterof $usepop/pop/packages/newc_dec/auto/newc_dec.p
struppercase $popautolib/struppercase.p
student $usepop/pop/lib/objectclass/lib/objectclass_example.p
student_course updaterof $usepop/pop/lib/objectclass/lib/objectclass_example.p
stype_->_key $usepop/pop/lisp/src/specs.p
sub_doesmatch $popautolib/doesmatch.p
sub_doesmatch $usepop/pop/packages/newkit/prb/auto/doesmatch.p
sub_equals $popautolib/equals.p
sub_menu $usepop/pop/packages/neural/src/pop/nui_main.p
sub_menu_pwm $usepop/pop/packages/neural/src/pop/nui_pwmpanels.p
sub_repeater $popautolib/sys_obey_linerep.p
subcoords $popliblib/geometry.p
subcosines $popliblib/geometry.p
subdstring $popsrc/dstring.p
subdstring updaterof $popsrc/dstring.p
subgen $usepop/pop/packages/teaching/lib/grammar.p
subject $usepop/pop/lib/objectclass/lib/objectclass_example.p
sublist $usepop/pop/packages/neural/src/pop/nn_utils.p
subpartOn $usepop/pop/x/ved/src/xvedresources.p
subpartOn updaterof $usepop/pop/x/ved/src/xvedresources.p
subpartResource $usepop/pop/x/ved/src/xvedresources.p
subpartResource updaterof $usepop/pop/x/ved/src/xvedresources.p
subs_before_formatting $popliblib/reformat.p
subscr_loop $popautolib/subscr_loop.p
subscr_nbyte $popliblib/item_stream_saver.p
subscr_nbyte updaterof $popliblib/item_stream_saver.p
subscr_stack $popsrc/subscr_stack.p
subscr_stack updaterof $popsrc/subscr_stack.p
subscr_subsystem $popsrc/subsystem.p
subscr_subsystem updaterof $popsrc/subsystem.p
subscrcfloatvec $usepop/pop/packages/popvision/lib/newcfloatarray.p
subscrcfloatvec updaterof $usepop/pop/packages/popvision/lib/newcfloatarray.p
subscrdstring $popsrc/dstring.p
subscrdstring updaterof $popsrc/dstring.p
subscrl $popsrc/subscrl.p
subscrl updaterof $popsrc/subscrl.p
subscrln $usepop/pop/plog/src/dbpreds.p
subscrs $popsrc/string.p
subscrs updaterof $popsrc/string.p
subscrtmpvec $usepop/pop/lib/objectclass/src/tmpvecs.p
subscrv $popsrc/vector.p
subscrv updaterof $popsrc/vector.p
subscrvedstring $popautolib/subscrvedstring.p
subscrvedstring updaterof $popautolib/subscrvedstring.p
subscrw $popsrc/wordutil.p
subscrw updaterof $popsrc/wordutil.p
subscrzfloatvec $usepop/pop/packages/popvision/lib/newzfloatarray.p
subscrzfloatvec updaterof $usepop/pop/packages/popvision/lib/newzfloatarray.p
subseq $usepop/pop/lisp/src/seq.p
subset $popliblib/sets.p
subset $usepop/pop/lib/turtle/findregions.p
subst $usepop/pop/packages/teaching/lib/oldlisp.p
substitute $popautolib/form.p
substring $popsrc/string.p
substring updaterof $popsrc/string.p
substructure $popliblib/reformat.p
subsystem_add_new $popautolib/subsystem_add_new.p
subsystem_button_selectable $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
subsystem_button_selectable updaterof $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
subsystem_button_set $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
subsystem_button_set updaterof $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
subsystem_cb $usepop/pop/x/ui/lib/pop_ui_popcontroltool.p
subsystem_compile $popsrc/subsystem_compile.p
subsystem_datavec $usepop/pop/x/ui/lib/S-poplog_uiS-guiSubsystem.p
subsystem_libcompile $popsrc/subsystem_compile.p
subsystem_nest $popautolib/subsystem_nest.p
subsystem_searchlist $popsrc/subsystem_compile.p
subsystem_searchlist updaterof $popsrc/subsystem_compile.p
subsystem_valof $popautolib/subsystem_valof.p
subsystem_valof updaterof $popautolib/subsystem_valof.p
subtestline $usepop/pop/packages/teaching/auto/ttt.p
subtypep $usepop/pop/lisp/src/subtypep.p
subvedstring $popsrc/vedstring.p
subvedstring updaterof $popsrc/vedstring.p
subword $popsrc/consword.p
suggest $usepop/pop/packages/teaching/lib/stroppy.p
sumangle $usepop/pop/lib/turtle/findregions.p
sumlist $usepop/pop/packages/neural/src/pop/nn_utils.p
summarise_file $usepop/pop/packages/teaching/lib/summarise.p
sumof $usepop/pop/packages/teaching/auto/ved_vcalc.p
sunrasterfile $usepop/pop/packages/popvision/lib/sunrasterfile.p
sunrasterfile updaterof $usepop/pop/packages/popvision/lib/sunrasterfile.p
supers_of_class $usepop/pop/lib/objectclass/src/globals.p
suppnot $usepop/pop/packages/teaching/lib/elizaprog-2005.p
suppnot $usepop/pop/packages/teaching/lib/elizaprog.p
surprised_face $usepop/pop/packages/newkit/sim/lib/sim_faces.p
suspend $popsrc/process.p
suspend_chain $popsrc/process.p
sv_token $popsrc/lispcore.p
svo $popliblib/aed.p
svref $usepop/pop/lisp/src/arrays.p
svref updaterof $usepop/pop/lisp/src/arrays.p
sweep_views $usepop/pop/packages/teaching/lib/views.p
switch_callback $usepop/pop/x/pop/lib/XawTutorial.p
switch_lisp_to $usepop/pop/lisp/src/compile.p
switch_rc_toggle_value $usepop/pop/packages/rclib/lib/rc_buttons.p
switch_scratchpad $usepop/pop/packages/rclib/auto/rc_scratch_window.p
switch_subsystem_to $popautolib/switch_subsystem_to.p
switch_variable_callback $usepop/pop/x/pop/lib/XmTutorial.p
switch_variable_callback $usepop/pop/x/pop/lib/XolTutorial.p
switchon $popautolib/switchon.p
switchval $usepop/pop/packages/teaching/auto/ved_vcalc.p
swleft $popvedlib/ved_swl.p
swm $popliblib/aed.p
sxhash $usepop/pop/lisp/src/hash.p
sym_to_filename $usepop/pop/lisp/src/util.p
sym_to_word $usepop/pop/lisp/src/util.p
symbol $usepop/pop/pml/src/lex.p
symbol_function $usepop/pop/lisp/src/tokens.p
symbol_function updaterof $usepop/pop/lisp/src/tokens.p
symbol_macro $usepop/pop/lisp/src/plant.p
symbol_name $usepop/pop/lib/lr_parser/lib/lr_info.p
symbol_name $usepop/pop/lisp/src/symbols.p
symbol_nresults $usepop/pop/lib/lr_parser/auto/define_parser.p
symbol_nresults updaterof $usepop/pop/lib/lr_parser/auto/define_parser.p
symbol_package $popsrc/lispcore.p
symbol_plist $popsrc/lispcore.p
symbol_plist updaterof $popsrc/lispcore.p
symbol_status $usepop/pop/lisp/src/symbols.p
symbol_string $popsrc/lispcore.p
symbol_value $usepop/pop/lisp/src/tokens.p
symbol_value updaterof $usepop/pop/lisp/src/tokens.p
symtab $usepop/pop/lib/lr_parser/auto/define_parser.p
sync_display $usepop/pop/x/ved/src/xvedwm.p
synonym $popautolib/synonym.p
synonym_stream_symbol $usepop/pop/lisp/src/streams.p
syntax_error $usepop/pop/plog/src/parse.p
sysAND $popsrc/vm_plant.p
sysASSIGN $popautolib/kr_newc_dec.p
sysASSIGN $popautolib/newc_dec.p
sysASSIGN $usepop/pop/packages/newc_dec/auto/newc_dec.p
sysCALL $popsrc/vm_plant.p
sysCALL updaterof $popsrc/vm_plant.p
sysCALLQ $popsrc/vm_plant.p
sysCALLQ updaterof $popsrc/vm_plant.p
sysCALLQ_? $usepop/pop/packages/teaching/lib/newobj.p
sysCALLS $popsrc/vm_plant.p
sysCALLS updaterof $popsrc/vm_plant.p
sysCLOSURE $usepop/pop/lib/objectclass/src/utils.p
sysCOMPILE $popsrc/vm_control.p
sysCONSTANT $popsrc/vm_plant.p
sysCONSTRUCT $popsrc/vm_plant.p
sysDIVARS $usepop/pop/lib/flavours/flavesyntax.p
sysDLABEL $popsrc/vm_plant.p
sysDLVARS $popsrc/vm_plant.p
sysENDLBLOCK $popsrc/vm_control.p
sysENDPROCEDURE $popsrc/vm_control.p
sysERASE $popsrc/vm_plant.p
sysEXECUTE $popsrc/vm_control.p
sysEXEC_COMPILE $popsrc/vm_control.p
sysEXEC_OPTION_COMPILE $popsrc/vm_control.p
sysFIELD $popsrc/vm_fields.p
sysFIELD updaterof $popsrc/vm_fields.p
sysFIELD_VAL $popautolib/sysFIELD_VAL.p
sysGCONSTANT $usepop/pop/lib/objectclass/src/readutils.p
sysGLOBAL $popsrc/vm_global.p
sysGOTO $popsrc/vm_plant.p
sysGO_ON $popsrc/vm_plant.p
sysGVARS $usepop/pop/lib/objectclass/src/readutils.p
sysIDENT $popsrc/vm_plant.p
sysIFNOT $popsrc/vm_plant.p
sysIFSO $popsrc/vm_plant.p
sysLABEL $popsrc/vm_plant.p
sysLBLOCK $popsrc/vm_control.p
sysLCONSTANT $popsrc/vm_plant.p
sysLIVARS $usepop/pop/lib/flavours/flavesyntax.p
sysLOCAL $popsrc/vm_plant.p
sysLVARS $popsrc/vm_plant.p
sysLVARS0 $usepop/pop/lib/objectclass/src/readutils.p
sysNEW_LABEL $popsrc/vm_plant.p
sysNEW_LVAR $popsrc/vm_plant.p
sysNONLOCAL $usepop/pop/lib/objectclass/src/readutils.p
sysOR $popsrc/vm_plant.p
sysPASSIGN $popsrc/vm_plant.p
sysPASSIGN updaterof $popsrc/vm_plant.p
sysPLOG_ARG_PUSH $popsrc/vm_plog.p
sysPLOG_IFNOT_ATOM $popsrc/vm_plog.p
sysPLOG_IFNOT_FAIL $usepop/pop/plog/src/gencode.p
sysPLOG_IFNOT_UNIFY $usepop/pop/plog/src/gencode.p
sysPLOG_RESTART $popsrc/vm_plog.p
sysPLOG_RESTORE $popsrc/vm_plog.p
sysPLOG_SAVE $popsrc/vm_plog.p
sysPLOG_TERM_SWITCH $popsrc/vm_plog.p
sysPOP $popsrc/vm_plant.p
sysPROCEDURE $popsrc/vm_control.p
sysPUSH $popsrc/vm_plant.p
sysPUSH updaterof $popsrc/vm_plant.p
sysPUSHQ $popsrc/vm_plant.p
sysPUSHQ_DISCOUNT_LEX $usepop/pop/lisp/src/plant.p
sysPUSHS $popsrc/vm_plant.p
sysSETLOCALS $usepop/pop/packages/teaching/lib/newobj.p
sysSUBSCR $popautolib/sysFIELD_VAL.p
sysSUBSCR_STACK $usepop/pop/lib/objectclass/src/utils.p
sysSWAP $popsrc/vm_plant.p
sysSYNTAX $popsrc/vm_plant.p
sysUCALL $popsrc/vm_plant.p
sysUCALLQ $popsrc/vm_plant.p
sysUCALLS $popsrc/vm_plant.p
sysUFIELD $popsrc/vm_fields.p
sysUFIELD_VAL $popautolib/sysFIELD_VAL.p
sysUPASSIGN $popsrc/vm_plant.p
sysUSUBSCR $popautolib/sysFIELD_VAL.p
sysVARS $popsrc/vm_plant.p
sys_= $popsrc/data_generic.p
sys_>< $popsrc/print_concat.p
sys_XptGetValues $usepop/pop/x/src/xt_resource.p
sys_async_input $popautolib/sys_async_input.p
sys_async_io $popsrc/sys_async_input.p
sys_async_io updaterof $popsrc/sys_async_input.p
sys_autoload $popsrc/sys_autoload.p
sys_autoload_action $popsrc/sys_autoload.p
sys_class_of $usepop/pop/lisp/src/clos-types.p
sys_clear_input $popsrc/sys_clear_input.p
sys_compiler_subsystem $popautolib/sys_compiler_subsystem.p
sys_compiler_subsystem updaterof $popautolib/sys_compiler_subsystem.p
sys_convert_date $popsrc/sysdate.p
sys_current_ident $popsrc/sys_current_ident.p
sys_current_val $popsrc/sys_current_ident.p
sys_current_val updaterof $popsrc/sys_current_ident.p
sys_decode_string $popsrc/string.p
sys_destroy_isdependent $popsrc/destroy_prop.p
sys_destroy_isdependent updaterof $popsrc/destroy_prop.p
sys_device_wait $popsrc/sys_input_waiting.p
sys_dir_name $usepop/pop/x/ui/lib/S-poplog_uiS-guiFileutils.p
sys_dir_size $popautolib/sys_dir_size.p
sys_encode_string $popsrc/string.p
sys_encode_string_fixed $popsrc/getstore_fixed.p
sys_exception_final $popsrc/errors.p
sys_exception_handler $popsrc/errors.p
sys_file_copy $popsrc/syscreate.p
sys_file_exists $popautolib/sys_file_exists.p
sys_file_match $popautolib/sys_file_match.p
sys_file_move $popsrc/sys_file_move.p
sys_file_owner $usepop/pop/packages/lockfile/lib/ved_lockfile.p
sys_file_owner $usepop/pop/packages/vedutils/lib/ved_lockfile.p
sys_file_stat $popsrc/sys_file_stat.p
sys_finish_matchvars $popsrc/data_generic.p
sys_flavour_read_vars $usepop/pop/lib/flavours/flavesyntax.p
sys_fname $popsrc/sys_fname.p
sys_fname_extn $popsrc/sys_fname.p
sys_fname_nam $popsrc/sys_fname.p
sys_fname_name $popsrc/sys_fname.p
sys_fname_namev $popsrc/sys_fname.p
sys_fname_path $popsrc/sys_fname.p
sys_fork $popsrc/sysfork.p
sys_get_files $usepop/pop/x/ui/lib/S-poplog_uiS-guiFileutils.p
sys_get_files $usepop/pop/x/ui/lib/S-poplog_uiS-guiFileutils.p
sys_get_files $usepop/pop/x/ui/lib/S-poplog_uiS-guiFileutils.p
sys_grbg_closure $popsrc/consclosure.p
sys_grbg_destpair $popsrc/pair.p
sys_grbg_fixed $popsrc/exptr_mem.p
sys_grbg_list $popsrc/pair.p
sys_host_id $popsrc/sys_host_id.p
sys_host_name $popsrc/sys_host_name.p
sys_init_subsystem $popautolib/sys_init_subsystem.p
sys_input_waiting $popsrc/sys_input_waiting.p
sys_install_image $popsrc/sr_sys.p
sys_io_control $popsrc/sys_io_control.p
sys_io_control_check $popliblib/ptyfork.p
sys_is_executable $usepop/pop/packages/rclib/auto/rc_browser_action.p
sys_link_tty_params $popsrc/sysio.p
sys_lock_heap $popsrc/syslock.p
sys_lock_system $popsrc/syslocksys.p
sys_match_filename $popsrc/unixfmatch.p
sys_matchin_dir $popsrc/unixfmatch.p
sys_max_signal $popsrc/sig_max.p
sys_max_signal updaterof $popsrc/sig_max.p
sys_merge_filename $usepop/pop/x/ui/lib/S-poplog_uiS-guiFileutils.p
sys_message_printf $popsrc/print.p
sys_message_sprintf $usepop/pop/lisp/src/errors.p
sys_nonlocal_equals $popautolib/equals.p
sys_obey_linerep $popautolib/sys_obey_linerep.p
sys_open_url $popautolib/sys_open_url.p
sys_parse_doc_index_entry $popsrc/sys_search_doc_index.p
sys_parse_poparglist $popautolib/sys_parse_poparglist.p
sys_parse_string $popsrc/parse_string.p
sys_parse_url $popautolib/sys_parse_url.p
sys_popen $popautolib/sys_popen.p
sys_pr_exception $popsrc/errors.p
sys_pr_external_require_load_warn $popautolib/external_require.p
sys_pr_message $popsrc/errors.p
sys_print_ident $popliblib/readpattern.p
sys_print_ident $usepop/pop/packages/lib/poprulebase.p
sys_print_ident $usepop/pop/packages/newkit/prb/lib/poprulebase.p
sys_print_ident $usepop/pop/packages/newkit/prb/lib/readpattern.p
sys_print_instance $usepop/pop/lib/objectclass/src/objectclasses.p
sys_process_poparg1 $popsrc/init_args.p
sys_raise_ast $popsrc/signals.p
sys_raise_exception $popsrc/errors.p
sys_raise_signal $popautolib/sys_raise_signal.p
sys_read_lines $popsrc/sys_read_lines.p
sys_read_path $popsrc/sys_read_path.p
sys_real_time $popsrc/sys_real_time.p
sys_reset_signal $popsrc/signals.p
sys_restore_matchvars $popautolib/sys_restore_matchvars.p
sys_runtime_apply $popautolib/sys_runtime_apply.p
sys_search_doc_index $popsrc/sys_search_doc_index.p
sys_search_unix_path $popautolib/sys_search_unix_path.p
sys_send_signal $popsrc/sig_async.p
sys_show_mem_segs $popsrc/memseg.p
sys_signal_flag $popsrc/signals.p
sys_signal_flag updaterof $popsrc/signals.p
sys_signal_handler $popsrc/signals.p
sys_signal_handler updaterof $popsrc/signals.p
sys_signal_queue $popautolib/sys_signal_queue.p
sys_signals_enabled $popautolib/sys_signals_enabled.p
sys_socket $popliblib/unix_sockets.p
sys_socket_accept $popliblib/unix_sockets.p
sys_socket_name $popliblib/unix_sockets.p
sys_socket_name updaterof $popliblib/unix_sockets.p
sys_socket_name_trans $popliblib/unix_sockets.p
sys_socket_option $popliblib/unix_sockets.p
sys_socket_option updaterof $popliblib/unix_sockets.p
sys_socket_pair $popliblib/unix_sockets.p
sys_socket_peername $popliblib/unix_sockets.p
sys_socket_peername updaterof $popliblib/unix_sockets.p
sys_socket_recv $popliblib/unix_sockets.p
sys_socket_send $popliblib/unix_sockets.p
sys_socket_shutdown $popliblib/unix_sockets.p
sys_socket_to_service $popliblib/unix_sockets.p
sys_split_url $popautolib/sys_split_url.p
sys_subsystems_init $popsrc/syssetup.p
sys_symbol $popliblib/newpop.p
sys_symbol updaterof $popliblib/newpop.p
sys_syspr $popsrc/print.p
sys_timer $popsrc/sys_timer.p
sys_timer updaterof $popsrc/sys_timer.p
sys_translate_exlibs $popautolib/sys_translate_exlibs.p
sys_type_of $usepop/pop/lisp/src/clos-types.p
sys_unlock_heap $popsrc/syslock.p
sys_use_current_ident $popsrc/sys_current_ident.p
sys_vfork $popsrc/sysfork.p
sys_wait $popsrc/syswait.p
sys_wait $popsrc/syswait.p
sysachieve $usepop/pop/packages/teaching/lib/planet.p
sysallpresent $usepop/pop/lib/database/allpresent.p
sysanyvecons $popsrc/vec_generic.p
sysassoc $popautolib/assoc.p
sysassoc updaterof $popautolib/assoc.p
syscallers $popautolib/syscallers.p
syscancel $popsrc/perm_ident.p
syscancelword $popsrc/syscancelword.p
syscantimer $popsrc/sys_timer.p
syscanvtimer $popliblib/itimer_virtual.p
sysclose $popsrc/sysio.p
sysconslist $popsrc/pair.p
sysconslist_onto $popsrc/pair.p
syscreate $popsrc/syscreate.p
sysdaytime $popsrc/sysdate.p
sysdebug $popliblib/debug.p
sysdeclare $popsrc/perm_ident.p
sysdeclare $usepop/pop/lisp/src/tokens.p
sysdelete $popsrc/sysdelete.p
sysdirectory $popautolib/sysdirectory.p
sysdisplay $usepop/pop/lib/obsolete/active.p
sysdisplay $usepop/pop/lib/turtle/sysdisplay.p
sysexecute $popsrc/sysexecute.p
sysexit $popsrc/sysexit.p
sysfilecomplete $popvedlib/vedfilecomplete.p
sysfiledir $popautolib/sysfiledir.p
sysfiledisk $popautolib/sysfiledisk.p
sysfileextension $popautolib/sysfileextension.p
sysfilefield $popautolib/sysfileparse.p
sysfilehost $popautolib/sysfilehost.p
sysfileinode $popautolib/sysfileinode.p
sysfilemode $popautolib/sysfilemode.p
sysfilemode updaterof $popautolib/sysfilemode.p
sysfilename $popautolib/sysfilename.p
sysfileok $popsrc/sysfileok.p
sysfileowner $popautolib/sysfileowner.p
sysfileowner updaterof $popautolib/sysfileowner.p
sysfileparse $popautolib/sysfileparse.p
sysfilesize $popautolib/sysfilesize.p
sysfiletype $popautolib/sysfiletype.p
sysfileversion $popautolib/sysfileversion.p
sysflavour $usepop/pop/lib/flavours/flavecore.p
sysflush $popsrc/sysio.p
sysfork $popautolib/sysfork.p
sysfullfilename $popautolib/sysfullfilename.p
sysgarbage $popsrc/getstore.p
sysgetmailname $usepop/pop/packages/vedmail/auto/sysgetmailname.p
sysgetpasswdentry $popsrc/sysutil.p
sysgetusername $popautolib/sysgetusername.p
syshash $popsrc/data_generic.p
syshibernate $popsrc/sys_timer.p
sysinfo $popsrc/sysutil.p
sysinitcomp $popsrc/pop11_compile.p
sysintern $popsrc/lispcore.p
sysiomessage $popautolib/sysiomessage.p
sysisdirectory $popsrc/sysisdirectory.p
sysisprogfile $popautolib/sysisprogfile.p
syskill $popautolib/syskill.p
syslibcompile $popsrc/syslibcompile.p
syslibwarning $popautolib/syslibwarning.p
syslink $popsrc/syslink.p
sysloadwarning $popautolib/load.p
syslock $popliblib/lockf.p
syslock $usepop/pop/packages/lockfile/lib/lockf.p
syslockf $popliblib/lockf.p
syslockf $usepop/pop/packages/lockfile/lib/lockf.p
sysmatch $popsrc/sysmatch.p
sysmodtime $popautolib/sysmodtime.p
sysnvariable $popautolib/sysnvariable.p
sysobey $popsrc/sysobey.p
sysobeylist $popautolib/sysobeylist.p
sysobjectfile $popautolib/sysobjectfile.p
sysopen $popsrc/sysopen.p
sysparse_string $popautolib/sysparse_string.p
syspipe $popsrc/syspipe.p
syspr $popsrc/print.p
sysprarrow $popsrc/sysprarrow.p
sysprautoloadwarn $popautolib/sysprautoloadwarn.p
sysprincludewarn $popautolib/include.p
sysprmessage $popautolib/sysprmessage.p
sysprmishap $popsrc/errors.p
sysprotect $popsrc/sysprotect.p
sysprwarning $popsrc/errors.p
sysread $popsrc/sysreadwrite.p
sysrepeat $popautolib/sysrepeat.p
sysrestore $popsrc/sr_sys.p
sysrestoreincr $popsrc/sr_incr.p
syssave $popsrc/sr_sys.p
syssaveincr $popsrc/sr_incr.p
syssearchpath $popsrc/syssearchpath.p
sysseek $popsrc/sysseek.p
syssendmessage $usepop/pop/lib/flavours/flavecore.p
syssendmessage updaterof $usepop/pop/lib/flavours/flavecore.p
syssettimer $popsrc/sys_timer.p
syssetup $popsrc/syssetup.p
syssetvtimer $popliblib/itimer_virtual.p
syssleep $popsrc/sys_timer.p
syssocket $popautolib/syssocket.p
syssort $popautolib/syssort.p
syssubclass_responsibility $usepop/pop/lib/flavours/subclass_responsibility_message.p
syssymlink $popsrc/syslink.p
syssymlink $popsrc/syslink.p
syssynonym $popautolib/syssynonym.p
systime $popsrc/systime.p
systmpfile $popsrc/systmpfile.p
systrace $popsrc/trace.p
systrace updaterof $popsrc/trace.p
systrace_method $usepop/pop/lib/objectclass/auto/trace_method.p
systrace_method updaterof $usepop/pop/lib/objectclass/auto/trace_method.p
systrace_pr $popsrc/trace.p
systrace_proc $popsrc/trace.p
systranslate $popsrc/sysutil.p
systranslate updaterof $popsrc/sysutil.p
systrmdev $popsrc/miscio.p
systryall $usepop/pop/lib/database/forevery.p
sysunlink $popsrc/syslink.p
sysunlock $popliblib/lockf.p
sysunlock $usepop/pop/packages/lockfile/lib/lockf.p
sysunprotect $popsrc/sysprotect.p
sysvaries $usepop/pop/lib/database/add.p
sysvecons $popsrc/vector.p
sysvfork $popautolib/sysvfork.p
syswait $popautolib/syswait.p
syswrite $popsrc/sysreadwrite.p
sysxsqcomp $popautolib/sysxsqcomp.p
szr $popliblib/aed.p
