#!/bin/sh -e
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:             C.unix/src/newpop
# Purpose:          Install a new Poplog system
# Author:           Robert John Duncan, May 28 1991 (see revisions)
# Documentation:    HELP * NEWPOP
# Related Files:    LIB * NEWPOP

# Set up the standard Poplog environment
. $usepop/pop/com/poplog.sh

# Add a flag to indicate we're running NEWPOP
POPNEWPOP=
export POPNEWPOP

# Run the NEWPOP saved image based on corepop
if [ $# -eq 0 ]; then
	corepop +$popsys/newpop.psv
else
	corepop +$popsys/newpop.psv "$@"
fi

# --- Revision History ---------------------------------------------------
# --- John Gibson, Jul 10 1993  Changed to use corepop
# --- Robert John Duncan, Dec 10 1991
#		Usual hack for buggy "$@"
# --- Robert John Duncan, Sep 23 1991
#       Changed to use the newpop saved image
