#!/bin/csh -ef
# --- Copyright University of Sussex 1995. All rights reserved. ----------
# File:				C.unix/com/buildobjlib
# Purpose:			Build (non-basepop11) object libraries in $popobjlib
# Author:			John Gibson, Aug 31 1993 (see revisions)
# Documentation:
# Related Files:    C.vms/com/buildobjlib.com

	# N.B. The ordering of these directories MATTERS (a lot).
	# In general, the popc.args files in later dirs assume the existence
	# of the w-libraries from previous ones for extracting declarations.
	# (They also rely on the w-libs for src, ved/src and x/src having
	# been built already.)

set DIRS = ( 			\
	lib/auto			\
	lib/lib				\
	lib/ved				\
	lib/sun				\
	lib/ved/term		\
	lib/objectclass/rt	\
						\
	x/pop/auto			\
	x/pop/lib			\
						\
	x/pop/lib/Xpw		\
	x/pop/lib/Xm		\
	x/pop/lib/Xol		\
	x/pop/lib/Xaw		\
						\
	x/ved/src			\
	x/ved/lib			\
	x/ved/auto			\
						\
	x/ui/lib			\
)

foreach d ($DIRS)
	cd $usepop/pop/$d
	echo "------------ "`pwd`
	popc -createwlib ./ -norec *.p
end


# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, Nov 21 1995
#		Added lib/objectclass/rt
# --- John Gibson, Nov  9 1995
#		Removed lib/pw*m
# --- John Gibson, Jul 31 1995
#		Makes lib/pw*m only for SunOS 4
