#!/bin/sh
# --- Copyright University of Sussex 1996. All rights reserved. ----------
# File:             C.unix/com/makeindexes
# Purpose:          Build standard Poplog documentation indexes
# Author:           Simon Nichols, Sep 30 1990 (see revisions)

$popsys/basepop11 make_indexes $usepop/pop "$@"

# --- Revision History ---------------------------------------------------
# --- John Gibson, Mar 29 1996  Changed to use basepop11
# --- John Gibson, Sep 17 1992
#		Made it pass on any args
# --- Adrian Howard, Feb  6 1992
#       Altered to use LIB *MAKE_INDEXES
# --- Robert John Duncan, Jan 27 1992
#		Extended mkrefindex to all X ref directories
# --- Adrian Howard, Aug 20 1991
#		xpopindex --> xindex
