#!/bin/csh -f
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:             C.unix/com/make_manual
# Purpose:          Allow the REFORMAT manual making package to be run
# Author:           Dermot M. McIntyre, May 21 1993
# Documentation:    HELP * REFORMAT REF * REFORMAT
# Related Files:    LIB * REFORMAT
					C.all/lib/lib/reformat/rf.start.tex
					C.all/lib/lib/reformat/rf.end.tex
					C.all/lib/lib/reformat/Master.tex
					C.all/lib/lib/reformat/makemanual


if ("$1" == "") then
	set Master = $usepop/pop/lib/lib/reformat/Master.tex
else
	set Master = "$1"
endif

$popsys/basepop11 ":lib reformat; make_manual('$Master'); "
