#!/bin/sh
# --- Copyright University of Sussex 1991.  All rights reserved. ---------
# File:            C.unix/com/mkct
# Purpose:         Make saved image of prolog for beginners
# Author:          Mark Rubinstein, Mar 25 1986 (see revisions)
# Documentation:   $usepop/pop/plog/teach/tracer $usepop/pop/plog/teach/why
# Related Files:   $usepop/pop/plog/lib/ct.pl $usepop/pop/plog/lib/tracer.pl

# Make saved image of prolog for beginners

$popsys/pop11 +$popsavelib/prolog %nort %noinit << \\\\

:- library(ct).
:- library(tracer).
:- version('CT saved image').
:- prolog_eval(apply(valof(ved_notrace))).
:- save('$poplocalbin/ct', [lock, share, init, banner]) -> ct_start ; true.

\\

rm -f $poplocalbin/ct.psv-
echo "CT saved image made"


# --- Revision History ---------------------------------------------------
# --- Robert John Duncan, Sep 10 1991 - made each goal a directive
# --- John Gibson, May 24 1991		Added %nort arg
# --- Simon Nichols, Oct 12 1990 - rewritten to use save/2
# --- John Williams, Oct  9 1990 - %noinit instead of =noinit
# --- John Williams, Oct  4 1990 - now uses -syssetup-
# --- Simon Nichols, Sep 10 1990 - changed "noinit" to "=noinit"
# --- Simon Nichols, Jul 18 1990 - revised for new LIB SUBSYSTEM
