#!/bin/sh
# --- Copyright University of Sussex 1993.  All rights reserved. ---------
# File:            C.unix/com/mkind
# Purpose:         Run LIB * MKIND from the shell
# Author:          Chris Slymon, June 1983 (see revisions)
# Documentation:   HELP * POPINDEX, HELP * SOURCEFILE
# Related Files:   LIB * MKIND

$popsys/basepop11 %noinit $popliblib/mkind


# --- Revision History ---------------------------------------------------
# --- John Gibson, Apr 29 1993  Removed inappropriate %nort arg
# --- John Williams, Sep 17 1992
#       Split into this file and LIB * MKIND
