#!/bin/sh
# --- Copyright University of Sussex 1993. All rights reserved. ----------
# File:             C.unix/com/mklispplog
# Purpose:          Build a Lisp+Prolog saved image
# Author:           John Williams, Jul 18 1990 (see revisions)
# Documentation:    HELP * MKLISPPLOG
# Related Files:    C.vms/com/mklispplog.com, C.unix/com/mkploglisp

$popsys/pop11 +$popsavelib/clisp %nort \
	mkimage -subsystem lisp $popsavelib/lispplog prolog

rm -f $popsavelib/lispplog.psv-

# --- Revision History ---------------------------------------------------
# --- John Gibson, Jan 19 1993		Added -subsystem arg
# --- John Gibson, May 24 1991		Added %nort arg
# --- Robert John Duncan, May 20 1991 - now uses LIB MKIMAGE
# --- John Williams, Oct  9 1990 - %noinit instead of =noinit
# --- John Williams, Oct  4 1990 - now uses -syssetup-
# --- Simon Nichols, Sep 10 1990 - changed "noinit" to "=noinit"
