#!/bin/sh
# --- Copyright University of Sussex 1996. All rights reserved. ----------
# File:             C.unix/com/mkXpm
# Purpose:          Build the Xpm library
# Author:           Julian Clinton (from $popcom/mkXpw) (see revisions)
# Documentation:
# Related Files:

# Usage: mkXpm [ -I<directory> ... ]

eval `$popcom/get_archive_args sh "$@"`

IDIRS="$IDIRS -I$POP_X_INCLUDE"
LIBNAME=libXpm$LIBEXTN
if [ -n "$LDLIBS" ]; then
	LDLIBS="-lXt -lX11 $LDLIBS"
fi

cd $usepop/pop/x/Xpm

$CC -c $CFLAGS $IDIRS *.c   && \
eval $AR *.o $LDLIBS        && \
eval $RANLIB                && \
rm *.o                      && \
mv $LIBNAME $popexternlib


# --- Revision History ---------------------------------------------------
# --- Julian Clinton, Aug  7 1998 -- brought up to date with mkXpw
# --- Robert Duncan, Nov  5 1996 -- brought up to date with mkXpw
# --- Robert Duncan, Mar  4 1996 -- added -DSVR4 for Solaris & Irix
