#!/bin/csh
# $usepop/bin/poplog
# Aaron Sloman
# The files $usepop/INSTALL/poplog1 and $usepop/INSTALL/poplog2 are used
# by the installation script to create $usepop/bin/poplog

## Poplog startup script for csh and tcsh users (sourced or run as a script)
## Created automatically by installation script

# Purpose:
# Script which sets up poplog environment variables, and then runs
# The command given as argument (e.g. pop11, xved, clisp, etc.)
# When used like this it sets the environment variables only in the
# process that runs the script.

# Can be "sourced" instead, to set environment variables for a whole
# login session, or in an xterm, e.g. in the user's startup file


## In the first mode, it can be invoked with commands such as
##
##    poplog pop11
##    poplog ved
##    poplog xved <file>
##    poplog prolog
##    poplog clisp
##    poplog pml
##    poplog pop11 +eliza

## In the second mode, invoke this as something like this:
##    source $usepop/bin/poplog
##    rehash

# setup local directory tree for poplog root
# may be a symbolic link to something else
